import { E, type HistEvent } from './events';

/**
 * Curated event list following the conventional Czech upper-secondary
 * (gymnázium / maturita) history canon — Czech history in full, world history
 * core. The national RVP G prescribes no date list, so this is the curated
 * convention, and every entry stands on its cited reference. Locations are
 * approximate by nature (the layer's disclaimer says so); where a location is
 * genuinely unknown or traditional, the description says that too.
 */
export const EVENTS: HistEvent[] = [
  /* ---------------- antiquity ---------------- */
  E('giza', -2560, 29.98, 31.13,
    ['Velká pyramida v Gíze', 'Great Pyramid of Giza', 'Gran Pirámide de Guiza'],
    ['Dokončena hrobka faraona Chufua, po tisíciletí nejvyšší stavba světa.', 'Pharaoh Khufu’s tomb completed — the world’s tallest structure for millennia.', 'Se completa la tumba del faraón Keops, la construcción más alta del mundo durante milenios.'],
    'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza'),
  E('hammurabi', -1754, 32.54, 44.42,
    ['Chammurapiho zákoník', 'Code of Hammurabi', 'Código de Hammurabi'],
    ['V Babylónu sepsán jeden z nejstarších zákoníků („oko za oko“).', 'One of the oldest law codes written down in Babylon (“an eye for an eye”).', 'En Babilonia se redacta uno de los códigos legales más antiguos («ojo por ojo»).'],
    'https://en.wikipedia.org/wiki/Code_of_Hammurabi'),
  E('kadesh', -1274, 34.56, 36.51,
    ['Bitva u Kadeše', 'Battle of Kadesh', 'Batalla de Qadesh'],
    ['Ramesse II. proti Chetitům; vedla k nejstarší dochované mírové smlouvě.', 'Ramesses II against the Hittites; led to the oldest surviving peace treaty.', 'Ramsés II contra los hititas; llevó al tratado de paz más antiguo conservado.'],
    'https://en.wikipedia.org/wiki/Battle_of_Kadesh'),
  E('olympics', -776, 37.64, 21.63,
    ['První olympijské hry', 'First Olympic Games', 'Primeros Juegos Olímpicos'],
    ['Tradiční datum prvních her v Olympii; Řekové podle nich počítali čas.', 'Traditional date of the first games at Olympia; Greeks counted time by them.', 'Fecha tradicional de los primeros juegos en Olimpia; los griegos contaban el tiempo por ellos.'],
    'https://en.wikipedia.org/wiki/Ancient_Olympic_Games'),
  E('rome-founded', -753, 41.89, 12.48,
    ['Založení Říma (tradice)', 'Founding of Rome (traditional)', 'Fundación de Roma (tradicional)'],
    ['Podle pověsti Romulus zakládá město; historicky jde o legendu.', 'Romulus founds the city according to legend; historically a tradition, not a record.', 'Según la leyenda, Rómulo funda la ciudad; históricamente es una tradición.'],
    'https://en.wikipedia.org/wiki/Founding_of_Rome'),
  E('jerusalem-586', -586, 31.78, 35.23,
    ['Zničení jeruzalémského chrámu', 'Destruction of the First Temple', 'Destrucción del Primer Templo'],
    ['Babylóňané dobyli Jeruzalém; začíná babylonské zajetí Židů.', 'The Babylonians take Jerusalem; the Babylonian captivity of the Jews begins.', 'Los babilonios toman Jerusalén; comienza el cautiverio babilónico de los judíos.'],
    'https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(587_BC)'),
  E('cyrus', -550, 30.2, 53.17,
    ['Kýros zakládá Perskou říši', 'Cyrus founds the Persian Empire', 'Ciro funda el Imperio persa'],
    ['Kýros II. Veliký sjednocuje Peršany; vzniká achaimenovská velmoc.', 'Cyrus the Great unites the Persians; the Achaemenid power is born.', 'Ciro el Grande une a los persas; nace la potencia aqueménida.'],
    'https://en.wikipedia.org/wiki/Cyrus_the_Great'),
  E('roman-republic', -509, 41.9, 12.47,
    ['Vznik římské republiky (tradice)', 'Roman Republic established (traditional)', 'Instauración de la República romana (tradicional)'],
    ['Řím podle tradice vyhání krále a zavádí republiku.', 'Rome by tradition expels its kings and becomes a republic.', 'Roma, según la tradición, expulsa a sus reyes y se convierte en república.'],
    'https://en.wikipedia.org/wiki/Roman_Republic'),
  E('marathon', -490, 38.15, 23.96,
    ['Bitva u Marathónu', 'Battle of Marathon', 'Batalla de Maratón'],
    ['Athéňané odrazili první perskou invazi do Řecka.', 'The Athenians repel the first Persian invasion of Greece.', 'Los atenienses repelen la primera invasión persa de Grecia.'],
    'https://en.wikipedia.org/wiki/Battle_of_Marathon'),
  E('thermopylae', -480, 38.8, 22.53,
    ['Thermopyly', 'Battle of Thermopylae', 'Batalla de las Termópilas'],
    ['Leónidás a Sparťané padli v soutěsce proti Xerxově přesile.', 'Leonidas and the Spartans fall holding the pass against Xerxes.', 'Leónidas y los espartanos caen defendiendo el paso frente a Jerjes.'],
    'https://en.wikipedia.org/wiki/Battle_of_Thermopylae'),
  E('salamis', -480, 37.95, 23.5,
    ['Bitva u Salamíny', 'Battle of Salamis', 'Batalla de Salamina'],
    ['Řecké loďstvo rozdrtilo perské; obrat řecko-perských válek.', 'The Greek fleet crushes the Persian one; the turning point of the wars.', 'La flota griega aplasta a la persa; el punto de inflexión de las guerras médicas.'],
    'https://en.wikipedia.org/wiki/Battle_of_Salamis'),
  E('peloponnesian', -431, 37.08, 22.43,
    ['Začátek peloponéské války', 'Peloponnesian War begins', 'Comienza la guerra del Peloponeso'],
    ['Sparta proti Athénám; třicetiletý zápas vyčerpal celé Řecko.', 'Sparta against Athens; three decades that exhausted all of Greece.', 'Esparta contra Atenas; tres décadas que agotaron a toda Grecia.'],
    'https://en.wikipedia.org/wiki/Peloponnesian_War'),
  E('chaeronea', -338, 38.49, 22.84,
    ['Bitva u Chairóneie', 'Battle of Chaeronea', 'Batalla de Queronea'],
    ['Filip II. Makedonský ovládl Řecko; konec svobody městských států.', 'Philip II of Macedon masters Greece; the end of city-state independence.', 'Filipo II de Macedonia domina Grecia; fin de la independencia de las polis.'],
    'https://en.wikipedia.org/wiki/Battle_of_Chaeronea_(338_BC)'),
  E('granicus', -334, 40.0, 27.3,
    ['Alexandr vstupuje do Asie', 'Alexander enters Asia', 'Alejandro entra en Asia'],
    ['Vítězstvím na řece Gráníku začíná Alexandrovo tažení proti Persii.', 'Victory at the Granicus opens Alexander’s campaign against Persia.', 'La victoria en el Gránico abre la campaña de Alejandro contra Persia.'],
    'https://en.wikipedia.org/wiki/Battle_of_the_Granicus'),
  E('gaugamela', -331, 36.56, 43.44,
    ['Bitva u Gaugamél', 'Battle of Gaugamela', 'Batalla de Gaugamela'],
    ['Alexandr definitivně porazil Dareia III.; perská říše padla.', 'Alexander decisively defeats Darius III; the Persian empire falls.', 'Alejandro derrota definitivamente a Darío III; cae el Imperio persa.'],
    'https://en.wikipedia.org/wiki/Battle_of_Gaugamela'),
  E('alexander-death', -323, 32.54, 44.43,
    ['Smrt Alexandra Velikého', 'Death of Alexander the Great', 'Muerte de Alejandro Magno'],
    ['Alexandr umírá v Babylónu; říši si rozdělili diadochové.', 'Alexander dies in Babylon; his generals carve up the empire.', 'Alejandro muere en Babilonia; sus generales se reparten el imperio.'],
    'https://en.wikipedia.org/wiki/Alexander_the_Great'),
  E('punic1', -264, 38.19, 15.55,
    ['První punská válka', 'First Punic War', 'Primera guerra púnica'],
    ['Řím a Kartágo se střetly o Sicílii; začátek zápasu o Středomoří.', 'Rome and Carthage clash over Sicily; the struggle for the Mediterranean begins.', 'Roma y Cartago chocan por Sicilia; empieza la lucha por el Mediterráneo.'],
    'https://en.wikipedia.org/wiki/First_Punic_War'),
  E('cannae', -216, 41.3, 16.13,
    ['Bitva u Kann', 'Battle of Cannae', 'Batalla de Cannas'],
    ['Hannibal uštědřil Římu nejtěžší porážku jeho dějin.', 'Hannibal deals Rome the worst defeat in its history.', 'Aníbal inflige a Roma la peor derrota de su historia.'],
    'https://en.wikipedia.org/wiki/Battle_of_Cannae'),
  E('zama', -202, 36.3, 9.45,
    ['Bitva u Zamy', 'Battle of Zama', 'Batalla de Zama'],
    ['Scipio porazil Hannibala; Kartágo přestalo být velmocí.', 'Scipio defeats Hannibal; Carthage ceases to be a great power.', 'Escipión derrota a Aníbal; Cartago deja de ser una gran potencia.'],
    'https://en.wikipedia.org/wiki/Battle_of_Zama'),
  E('carthage-146', -146, 36.85, 10.32,
    ['Zničení Kartága', 'Destruction of Carthage', 'Destrucción de Cartago'],
    ['Řím srovnal Kartágo se zemí; téhož roku padl i Korint.', 'Rome razes Carthage to the ground; Corinth falls the same year.', 'Roma arrasa Cartago; el mismo año cae Corinto.'],
    'https://en.wikipedia.org/wiki/Third_Punic_War'),
  E('spartacus', -73, 41.08, 14.25,
    ['Spartakovo povstání', 'Spartacus uprising', 'Rebelión de Espartaco'],
    ['Z gladiátorské školy v Capui vypuklo největší povstání otroků.', 'From the gladiator school at Capua erupts Rome’s greatest slave revolt.', 'De la escuela de gladiadores de Capua estalla la mayor revuelta de esclavos.'],
    'https://en.wikipedia.org/wiki/Third_Servile_War'),
  E('alesia', -52, 47.54, 4.5,
    ['Bitva u Alesie', 'Battle of Alesia', 'Batalla de Alesia'],
    ['Caesar porazil Vercingetorika; Galie se stala římskou.', 'Caesar defeats Vercingetorix; Gaul becomes Roman.', 'César derrota a Vercingétorix; la Galia se hace romana.'],
    'https://en.wikipedia.org/wiki/Battle_of_Alesia'),
  E('caesar-44', -44, 41.895, 12.48,
    ['Zavraždění Caesara', 'Assassination of Caesar', 'Asesinato de César'],
    ['O březnových idách zavražděn Caesar; republika míří k zániku.', 'Caesar is murdered on the Ides of March; the republic heads for its end.', 'César es asesinado en los idus de marzo; la república camina a su fin.'],
    'https://en.wikipedia.org/wiki/Assassination_of_Julius_Caesar'),
  E('actium', -31, 38.96, 20.77,
    ['Bitva u Aktia', 'Battle of Actium', 'Batalla de Accio'],
    ['Octavianus porazil Antonia a Kleopatru; nastává císařství.', 'Octavian defeats Antony and Cleopatra; the empire begins.', 'Octavio vence a Antonio y Cleopatra; comienza el imperio.'],
    'https://en.wikipedia.org/wiki/Battle_of_Actium'),
  E('teutoburg', 9, 52.4, 8.13,
    ['Bitva v Teutoburském lese', 'Battle of the Teutoburg Forest', 'Batalla del bosque de Teutoburgo'],
    ['Germáni zničili tři římské legie; Řím rezignoval na Germánii.', 'Germanic tribes destroy three Roman legions; Rome gives up on Germania.', 'Los germanos destruyen tres legiones; Roma renuncia a Germania.'],
    'https://en.wikipedia.org/wiki/Battle_of_the_Teutoburg_Forest'),
  E('crucifixion', 33, 31.78, 35.22,
    ['Ukřižování Ježíše (tradice)', 'Crucifixion of Jesus (traditional)', 'Crucifixión de Jesús (tradicional)'],
    ['Tradiční datace kolem let 30–33; počátek dějin křesťanství.', 'Traditionally dated around AD 30–33; the beginning of Christian history.', 'Fecha tradicional hacia 30–33 d. C.; el comienzo de la historia cristiana.'],
    'https://en.wikipedia.org/wiki/Crucifixion_of_Jesus'),
  E('pompeii', 79, 40.75, 14.49,
    ['Výbuch Vesuvu — zkáza Pompejí', 'Vesuvius erupts — Pompeii destroyed', 'Erupción del Vesubio: destrucción de Pompeya'],
    ['Popel pohřbil Pompeje a Herculaneum a zakonzervoval antické město.', 'Ash buries Pompeii and Herculaneum, preserving a Roman city whole.', 'La ceniza sepulta Pompeya y Herculano, conservando una ciudad romana entera.'],
    'https://en.wikipedia.org/wiki/Eruption_of_Mount_Vesuvius_in_79_AD'),
  E('milan-313', 313, 45.46, 9.19,
    ['Edikt milánský', 'Edict of Milan', 'Edicto de Milán'],
    ['Konstantin povolil křesťanství; z pronásledované víry státní.', 'Constantine legalizes Christianity; a persecuted faith becomes official.', 'Constantino legaliza el cristianismo; una fe perseguida se vuelve oficial.'],
    'https://en.wikipedia.org/wiki/Edict_of_Milan'),
  E('constantinople-330', 330, 41.01, 28.98,
    ['Založení Konstantinopole', 'Founding of Constantinople', 'Fundación de Constantinopla'],
    ['Konstantin přenesl těžiště říše na Bospor — „Nový Řím“.', 'Constantine moves the empire’s centre to the Bosphorus — a “New Rome”.', 'Constantino traslada el centro del imperio al Bósforo: una «Nueva Roma».'],
    'https://en.wikipedia.org/wiki/Constantinople'),
  E('huns-375', 375, 47.0, 45.0,
    ['Vpád Hunů do Evropy', 'Huns enter Europe', 'Los hunos entran en Europa'],
    ['Hunové překročili Volhu a spustili stěhování národů.', 'The Huns cross the Volga, setting off the Migration Period.', 'Los hunos cruzan el Volga y desencadenan las Grandes Migraciones.'],
    'https://en.wikipedia.org/wiki/Huns'),
  E('empire-split-395', 395, 41.0, 28.95,
    ['Rozdělení římské říše', 'Division of the Roman Empire', 'División del Imperio romano'],
    ['Po smrti Theodosia I. se říše natrvalo dělí na Západ a Východ.', 'After Theodosius I dies, the empire splits for good into West and East.', 'Tras la muerte de Teodosio I, el imperio se divide definitivamente en Occidente y Oriente.'],
    'https://en.wikipedia.org/wiki/Theodosius_I'),
  E('rome-410', 410, 41.9, 12.49,
    ['Alarich plení Řím', 'Alaric sacks Rome', 'Alarico saquea Roma'],
    ['Vizigóti poprvé po osmi staletích dobyli Věčné město.', 'The Visigoths take the Eternal City for the first time in eight centuries.', 'Los visigodos toman la Ciudad Eterna por primera vez en ocho siglos.'],
    'https://en.wikipedia.org/wiki/Sack_of_Rome_(410)'),
  E('catalaunian', 451, 48.32, 4.08,
    ['Bitva na Katalaunských polích', 'Battle of the Catalaunian Plains', 'Batalla de los Campos Cataláunicos'],
    ['Řím s Vizigóty zastavil Attilovy Huny v Galii.', 'Rome and the Visigoths stop Attila’s Huns in Gaul.', 'Roma y los visigodos frenan a los hunos de Atila en la Galia.'],
    'https://en.wikipedia.org/wiki/Battle_of_the_Catalaunian_Plains'),
  E('rome-fall-476', 476, 44.42, 12.2,
    ['Zánik západořímské říše', 'Fall of the Western Roman Empire', 'Caída del Imperio romano de Occidente'],
    ['Odoaker sesadil Romula Augustula; tradiční konec starověku.', 'Odoacer deposes Romulus Augustulus; the traditional end of antiquity.', 'Odoacro depone a Rómulo Augústulo; el final tradicional de la Antigüedad.'],
    'https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire'),

  /* ---------------- middle ages ---------------- */
  E('benedict-529', 529, 41.49, 13.81,
    ['Založení Monte Cassina', 'Monte Cassino founded', 'Fundación de Montecasino'],
    ['Benedikt z Nursie zakládá klášter; vzor západního mnišství.', 'Benedict of Nursia founds his monastery, the model of Western monasticism.', 'Benito de Nursia funda su monasterio, modelo del monacato occidental.'],
    'https://en.wikipedia.org/wiki/Monte_Cassino'),
  E('justinian-529', 529, 41.008, 28.976,
    ['Justiniánův zákoník', 'Justinian’s Code', 'Código de Justiniano'],
    ['V Konstantinopoli začíná kodifikace římského práva (Corpus iuris civilis).', 'In Constantinople begins the codification of Roman law (Corpus iuris civilis).', 'En Constantinopla comienza la codificación del derecho romano (Corpus iuris civilis).'],
    'https://en.wikipedia.org/wiki/Corpus_Juris_Civilis'),
  E('hijra', 622, 24.47, 39.61,
    ['Hidžra — počátek islámského letopočtu', 'Hijra — start of the Islamic calendar', 'Hégira: inicio del calendario islámico'],
    ['Mohamed odešel z Mekky do Medíny; islám se stává obcí i mocí.', 'Muhammad moves from Mecca to Medina; Islam becomes a community and a power.', 'Mahoma se traslada de La Meca a Medina; el islam se vuelve comunidad y poder.'],
    'https://en.wikipedia.org/wiki/Hegira'),
  E('wogastisburg', 631, 50.0, 13.5,
    ['Sámo odráží Franky (Wogastisburg)', 'Samo repels the Franks (Wogastisburg)', 'Samo rechaza a los francos (Wogastisburg)'],
    ['První doložený státní útvar Slovanů ubránil svou nezávislost; poloha bitvy není známa.', 'The first recorded Slavic polity defends its independence; the battle site is unknown.', 'La primera entidad eslava documentada defiende su independencia; el lugar de la batalla se desconoce.'],
    'https://en.wikipedia.org/wiki/Battle_of_Wogastisburg'),
  E('iberia-711', 711, 36.14, -5.35,
    ['Arabové v Hispánii', 'Arab conquest of Iberia begins', 'Comienza la conquista árabe de Iberia'],
    ['Tárikovo vylodění u Gibraltaru; vzniká al-Andalus.', 'Tariq lands near Gibraltar; al-Andalus is born.', 'Táriq desembarca junto a Gibraltar; nace al-Ándalus.'],
    'https://en.wikipedia.org/wiki/Umayyad_conquest_of_Hispania'),
  E('tours-732', 732, 46.58, 0.34,
    ['Bitva u Poitiers (Tours)', 'Battle of Tours (Poitiers)', 'Batalla de Poitiers (Tours)'],
    ['Karel Martel zastavil arabský postup do západní Evropy.', 'Charles Martel halts the Arab advance into western Europe.', 'Carlos Martel detiene el avance árabe en Europa occidental.'],
    'https://en.wikipedia.org/wiki/Battle_of_Tours'),
  E('charlemagne-800', 800, 41.902, 12.457,
    ['Korunovace Karla Velikého', 'Coronation of Charlemagne', 'Coronación de Carlomagno'],
    ['Papež korunoval Karla císařem; obnova císařství na Západě.', 'The pope crowns Charlemagne emperor; the empire returns to the West.', 'El papa corona emperador a Carlomagno; el imperio vuelve a Occidente.'],
    'https://en.wikipedia.org/wiki/Charlemagne'),
  E('moravia-833', 833, 48.8, 17.09,
    ['Vznik Velké Moravy', 'Rise of Great Moravia', 'Surgimiento de la Gran Moravia'],
    ['Mojmír I. připojil Nitransko; první velký státní útvar západních Slovanů.', 'Mojmir I annexes Nitra; the first major West Slavic state.', 'Mojmir I anexiona Nitra; el primer gran estado eslavo occidental.'],
    'https://en.wikipedia.org/wiki/Great_Moravia'),
  E('verdun-843', 843, 49.16, 5.38,
    ['Verdunská smlouva', 'Treaty of Verdun', 'Tratado de Verdún'],
    ['Vnuci Karla Velikého si rozdělili franskou říši na tři díly.', 'Charlemagne’s grandsons split the Frankish realm in three.', 'Los nietos de Carlomagno dividen el reino franco en tres.'],
    'https://en.wikipedia.org/wiki/Treaty_of_Verdun'),
  E('regensburg-845', 845, 49.02, 12.1,
    ['Křest 14 českých knížat', 'Baptism of 14 Bohemian princes', 'Bautismo de 14 príncipes bohemios'],
    ['V Řezně pokřtěno čtrnáct českých knížat — první krok christianizace Čech.', 'Fourteen Bohemian princes baptized at Regensburg — Christianization of Bohemia begins.', 'Catorce príncipes bohemios son bautizados en Ratisbona: comienza la cristianización de Bohemia.'],
    'https://en.wikipedia.org/wiki/Christianization_of_Bohemia'),
  E('cyril-methodius-863', 863, 49.11, 17.4,
    ['Příchod Cyrila a Metoděje', 'Cyril and Methodius arrive', 'Llegada de Cirilo y Metodio'],
    ['Byzantská misie přinesla na Moravu písmo a slovanskou liturgii.', 'The Byzantine mission brings Moravia a script and Slavic liturgy.', 'La misión bizantina trae a Moravia una escritura y la liturgia eslava.'],
    'https://en.wikipedia.org/wiki/Cyril_and_Methodius'),
  E('moravia-fall-907', 907, 48.14, 17.11,
    ['Zánik Velké Moravy', 'Fall of Great Moravia', 'Caída de la Gran Moravia'],
    ['Maďarský tlak smetl oslabenou říši; bitva u Bratislavy 907.', 'Magyar pressure sweeps away the weakened realm; battle of Pressburg, 907.', 'La presión magiar barre el reino debilitado; batalla de Presburgo, 907.'],
    'https://en.wikipedia.org/wiki/Battle_of_Pressburg'),
  E('ludmila-921', 921, 49.95, 14.1,
    ['Zavraždění kněžny Ludmily', 'Murder of Princess Ludmila', 'Asesinato de la princesa Ludmila'],
    ['Na Tetíně uškrcena babička sv. Václava, první česká světice.', 'St Wenceslas’s grandmother, the first Czech saint, strangled at Tetín.', 'La abuela de san Venceslao, primera santa checa, es estrangulada en Tetín.'],
    'https://en.wikipedia.org/wiki/Ludmila_of_Bohemia'),
  E('wenceslas-935', 935, 50.23, 14.68,
    ['Zavraždění knížete Václava', 'Murder of Duke Wenceslas', 'Asesinato del duque Venceslao'],
    ['Ve Staré Boleslavi zabit bratrem Boleslavem; stal se patronem země.', 'Killed at Stará Boleslav by his brother Boleslav; became the land’s patron saint.', 'Muerto en Stará Boleslav por su hermano Boleslao; se convirtió en patrón del país.'],
    'https://en.wikipedia.org/wiki/Wenceslaus_I,_Duke_of_Bohemia'),
  E('lechfeld-955', 955, 48.3, 10.9,
    ['Bitva na Lechu', 'Battle of Lechfeld', 'Batalla de Lechfeld'],
    ['Ota I. (s českou pomocí) zastavil maďarské nájezdy do Evropy.', 'Otto I (with Bohemian help) ends the Magyar raids into Europe.', 'Otón I (con ayuda bohemia) pone fin a las incursiones magiares en Europa.'],
    'https://en.wikipedia.org/wiki/Battle_of_Lechfeld'),
  E('otto-962', 962, 41.9, 12.455,
    ['Ota I. císařem — Svatá říše římská', 'Otto I emperor — Holy Roman Empire', 'Otón I emperador: Sacro Imperio'],
    ['Korunovací Oty I. vzniká říše, k níž české země patřily po staletí.', 'Otto I’s coronation creates the empire the Czech lands belonged to for centuries.', 'La coronación de Otón I crea el imperio al que las tierras checas pertenecieron durante siglos.'],
    'https://en.wikipedia.org/wiki/Otto_the_Great'),
  E('poland-966', 966, 52.53, 17.6,
    ['Křest Polska', 'Baptism of Poland', 'Bautismo de Polonia'],
    ['Kníže Měšek I. přijal křesťanství; Polsko vstupuje do latinské Evropy.', 'Duke Mieszko I accepts Christianity; Poland joins Latin Europe.', 'El duque Miecislao I acepta el cristianismo; Polonia entra en la Europa latina.'],
    'https://en.wikipedia.org/wiki/Baptism_of_Poland'),
  E('prague-bishopric-973', 973, 50.09, 14.4,
    ['Založení pražského biskupství', 'Prague bishopric founded', 'Fundación del obispado de Praga'],
    ['Čechy získaly vlastní biskupství, nezávislé na Řezně.', 'Bohemia gains its own bishopric, independent of Regensburg.', 'Bohemia obtiene su propio obispado, independiente de Ratisbona.'],
    'https://en.wikipedia.org/wiki/Archdiocese_of_Prague'),
  E('slavnikovci-995', 995, 50.12, 15.18,
    ['Vyvraždění Slavníkovců', 'Massacre of the Slavník dynasty', 'Matanza de los Slavník'],
    ['Přemyslovci vybili konkurenční rod na Libici; sjednocení Čech.', 'The Přemyslids wipe out their rivals at Libice; Bohemia is unified.', 'Los Premislidas exterminan a sus rivales en Libice; Bohemia queda unificada.'],
    'https://en.wikipedia.org/wiki/Slavn%C3%ADk_dynasty'),
  E('hungary-1000', 1000, 47.79, 18.74,
    ['Korunovace sv. Štěpána', 'Coronation of St Stephen', 'Coronación de san Esteban'],
    ['Vzniká Uherské království, soused českých zemí na dalších 900 let.', 'The Kingdom of Hungary is born — the Czech lands’ neighbour for 900 years.', 'Nace el Reino de Hungría, vecino de las tierras checas durante 900 años.'],
    'https://en.wikipedia.org/wiki/Stephen_I_of_Hungary'),
  E('schism-1054', 1054, 41.005, 28.98,
    ['Velké schizma', 'Great Schism', 'Gran Cisma'],
    ['Rozkol mezi Římem a Konstantinopolí rozdělil křesťanstvo dodnes.', 'The split between Rome and Constantinople divides Christendom to this day.', 'La ruptura entre Roma y Constantinopla divide la cristiandad hasta hoy.'],
    'https://en.wikipedia.org/wiki/East%E2%80%93West_Schism'),
  E('hastings-1066', 1066, 50.91, 0.49,
    ['Bitva u Hastingsu', 'Battle of Hastings', 'Batalla de Hastings'],
    ['Vilém Dobyvatel ovládl Anglii; normanská éra ostrovů.', 'William the Conqueror takes England; the Norman era begins.', 'Guillermo el Conquistador toma Inglaterra; comienza la era normanda.'],
    'https://en.wikipedia.org/wiki/Battle_of_Hastings'),
  E('vratislav-1085', 1085, 50.088, 14.402,
    ['Vratislav II. prvním českým králem', 'Vratislav II, first Czech king', 'Vratislav II, primer rey checo'],
    ['První královská koruna pro Přemyslovce (zatím jen pro jeho osobu).', 'The first royal crown for a Přemyslid — for his person only, as yet.', 'La primera corona real para un Premislida, aún solo a título personal.'],
    'https://en.wikipedia.org/wiki/Vratislaus_II_of_Bohemia'),
  E('clermont-1095', 1095, 45.78, 3.08,
    ['Vyhlášení první křížové výpravy', 'First Crusade proclaimed', 'Proclamación de la Primera Cruzada'],
    ['Urban II. v Clermontu vyzval k tažení za osvobození Jeruzaléma.', 'Urban II at Clermont calls for a campaign to free Jerusalem.', 'Urbano II llama en Clermont a liberar Jerusalén.'],
    'https://en.wikipedia.org/wiki/Council_of_Clermont'),
  E('jerusalem-1099', 1099, 31.78, 35.225,
    ['Dobytí Jeruzaléma křižáky', 'Crusaders take Jerusalem', 'Los cruzados toman Jerusalén'],
    ['První výprava dobyla město; vznikají křižácké státy.', 'The First Crusade takes the city; the crusader states are founded.', 'La Primera Cruzada toma la ciudad; nacen los estados cruzados.'],
    'https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(1099)'),
  E('worms-1122', 1122, 49.63, 8.36,
    ['Konkordát wormský', 'Concordat of Worms', 'Concordato de Worms'],
    ['Kompromis císaře a papeže ukončil boj o investituru.', 'Emperor and pope compromise, ending the Investiture Controversy.', 'El emperador y el papa pactan y cierran la querella de las investiduras.'],
    'https://en.wikipedia.org/wiki/Concordat_of_Worms'),
  E('vladislav-1158', 1158, 50.086, 14.398,
    ['Královský titul pro Vladislava II.', 'Royal title for Vladislav II', 'Título real para Vladislav II'],
    ['Druhý český král — odměna Fridricha Barbarossy za vojenskou pomoc.', 'Bohemia’s second king — Frederick Barbarossa’s reward for military aid.', 'Segundo rey de Bohemia: recompensa de Federico Barbarroja por la ayuda militar.'],
    'https://en.wikipedia.org/wiki/Vladislaus_II,_Duke_of_Bohemia'),
  E('constantinople-1204', 1204, 41.012, 28.976,
    ['Křižáci plení Konstantinopol', 'Crusaders sack Constantinople', 'Los cruzados saquean Constantinopla'],
    ['Čtvrtá výprava dobyla křesťanské město; Byzanc se už nevzpamatovala.', 'The Fourth Crusade takes a Christian city; Byzantium never recovers.', 'La Cuarta Cruzada toma una ciudad cristiana; Bizancio nunca se recupera.'],
    'https://en.wikipedia.org/wiki/Sack_of_Constantinople'),
  E('genghis-1206', 1206, 47.8, 108.8,
    ['Čingischán sjednocuje Mongoly', 'Genghis Khan unites the Mongols', 'Gengis Kan une a los mongoles'],
    ['Temüdžin prohlášen Čingischánem; začíná největší souvislá říše dějin.', 'Temüjin is proclaimed Genghis Khan; history’s largest land empire begins.', 'Temuyín es proclamado Gengis Kan; comienza el mayor imperio continuo de la historia.'],
    'https://en.wikipedia.org/wiki/Genghis_Khan'),
  E('golden-bull-1212', 1212, 47.56, 7.59,
    ['Zlatá bula sicilská', 'Golden Bull of Sicily', 'Bula de Oro de Sicilia'],
    ['Fridrich II. v Basileji potvrdil dědičný královský titul českých panovníků.', 'Frederick II at Basel confirms the hereditary royal title of Bohemia’s rulers.', 'Federico II confirma en Basilea el título real hereditario de los soberanos bohemios.'],
    'https://en.wikipedia.org/wiki/Golden_Bull_of_Sicily'),
  E('magna-carta-1215', 1215, 51.44, -0.56,
    ['Magna charta libertatum', 'Magna Carta', 'Carta Magna'],
    ['Jan Bezzemek uznal meze královské moci; základ ústavních svobod.', 'King John concedes limits to royal power; a foundation of constitutional liberty.', 'Juan sin Tierra acepta límites al poder real; fundamento de las libertades constitucionales.'],
    'https://en.wikipedia.org/wiki/Magna_Carta'),
  E('legnica-1241', 1241, 51.21, 16.16,
    ['Mongolové u Lehnice', 'Mongols at Legnica', 'Los mongoles en Legnica'],
    ['Mongolský vpád rozdrtil slezské vojsko a otřásl střední Evropou.', 'The Mongol invasion crushes a Silesian army and shakes central Europe.', 'La invasión mongola aplasta a un ejército silesio y sacude Europa Central.'],
    'https://en.wikipedia.org/wiki/Battle_of_Legnica'),
  E('marchfeld-1278', 1278, 48.48, 16.85,
    ['Bitva na Moravském poli', 'Battle on the Marchfeld', 'Batalla de Marchfeld'],
    ['Přemysl Otakar II., „král železný a zlatý“, padl v boji s Rudolfem Habsburským.', 'Přemysl Otakar II, “king of iron and gold”, falls fighting Rudolf of Habsburg.', 'Otakar II, «rey de hierro y oro», cae luchando contra Rodolfo de Habsburgo.'],
    'https://en.wikipedia.org/wiki/Battle_on_the_Marchfeld'),
  E('rutli-1291', 1291, 46.97, 8.6,
    ['Vznik švýcarského spříseženstva', 'Swiss Confederacy founded', 'Fundación de la Confederación Suiza'],
    ['Tři lesní kantony uzavřely věčný spolek proti Habsburkům.', 'Three forest cantons swear an everlasting league against the Habsburgs.', 'Tres cantones forestales juran una liga perpetua contra los Habsburgo.'],
    'https://en.wikipedia.org/wiki/Old_Swiss_Confederacy'),
  E('gros-1300', 1300, 49.95, 15.27,
    ['Pražský groš', 'Prague groschen', 'Grosche de Praga'],
    ['Václav II. zahájil v Kutné Hoře ražbu stříbrné mince evropského významu.', 'Wenceslas II starts minting a silver coin of European standing at Kutná Hora.', 'Venceslao II acuña en Kutná Hora una moneda de plata de alcance europeo.'],
    'https://en.wikipedia.org/wiki/Prague_groschen'),
  E('vaclav3-1306', 1306, 49.59, 17.25,
    ['Vymření Přemyslovců po meči', 'End of the Přemyslid male line', 'Fin de la línea masculina Premislida'],
    ['Václav III. zavražděn v Olomouci; dynastie po 400 letech končí.', 'Wenceslas III murdered at Olomouc; the dynasty ends after 400 years.', 'Venceslao III es asesinado en Olomouc; la dinastía se extingue tras 400 años.'],
    'https://en.wikipedia.org/wiki/Wenceslaus_III_of_Bohemia'),
  E('lucemburk-1310', 1310, 50.089, 14.4,
    ['Lucemburkové na český trůn', 'The Luxembourgs take the Czech throne', 'Los Luxemburgo en el trono checo'],
    ['Jan Lucemburský se sňatkem s Eliškou Přemyslovnou ujímá vlády.', 'John of Luxembourg takes power through marriage to Elizabeth Přemyslid.', 'Juan de Luxemburgo asume el poder al casarse con Isabel Premislida.'],
    'https://en.wikipedia.org/wiki/John_of_Bohemia'),
  E('hundred-years-1337', 1337, 50.0, 2.0,
    ['Začátek stoleté války', 'Hundred Years’ War begins', 'Comienza la guerra de los Cien Años'],
    ['Anglie a Francie zahájily zápas o francouzskou korunu (1337–1453).', 'England and France begin their struggle over the French crown (1337–1453).', 'Inglaterra y Francia inician su pugna por la corona francesa (1337–1453).'],
    'https://en.wikipedia.org/wiki/Hundred_Years%27_War'),
  E('crecy-1346', 1346, 50.25, 1.88,
    ['Kresčak — smrt Jana Lucemburského', 'Crécy — death of John of Bohemia', 'Crécy: muerte de Juan de Bohemia'],
    ['Slepý český král padl v bitvě; na trůn nastupuje Karel IV.', 'The blind Czech king falls in battle; Charles IV succeeds him.', 'El rey checo ciego cae en combate; le sucede Carlos IV.'],
    'https://en.wikipedia.org/wiki/Battle_of_Cr%C3%A9cy'),
  E('university-1348', 1348, 50.088, 14.416,
    ['Založení pražské univerzity', 'Charles University founded', 'Fundación de la Universidad Carolina'],
    ['Karel IV. zakládá první univerzitu na sever od Alp; téhož roku i Nové Město.', 'Charles IV founds the first university north of the Alps; the New Town too, the same year.', 'Carlos IV funda la primera universidad al norte de los Alpes; el mismo año, la Ciudad Nueva.'],
    'https://en.wikipedia.org/wiki/Charles_University'),
  E('golden-bull-1356', 1356, 49.45, 11.08,
    ['Zlatá bula Karla IV.', 'Golden Bull of 1356', 'Bula de Oro de 1356'],
    ['Říšský základní zákon: sedm kurfiřtů volí krále, český král mezi nimi.', 'The empire’s basic law: seven electors choose the king, Bohemia’s king among them.', 'Ley fundamental del imperio: siete electores eligen al rey, el de Bohemia entre ellos.'],
    'https://en.wikipedia.org/wiki/Golden_Bull_of_1356'),
  E('schism-1378', 1378, 43.95, 4.81,
    ['Papežské schizma', 'Western Schism', 'Cisma de Occidente'],
    ['Dva (později tři) papežové zároveň; krize autority církve. Téhož roku zemřel Karel IV.', 'Two (later three) rival popes; a crisis of church authority. Charles IV died the same year.', 'Dos (luego tres) papas rivales; crisis de la autoridad eclesial. Ese año murió Carlos IV.'],
    'https://en.wikipedia.org/wiki/Western_Schism'),
  E('kosovo-1389', 1389, 42.63, 21.12,
    ['Bitva na Kosově poli', 'Battle of Kosovo', 'Batalla de Kosovo'],
    ['Osmané zlomili srbský odpor; klíčové místo srbské paměti.', 'The Ottomans break Serbian resistance; a cornerstone of Serbian memory.', 'Los otomanos quiebran la resistencia serbia; piedra angular de la memoria serbia.'],
    'https://en.wikipedia.org/wiki/Battle_of_Kosovo'),
  E('kutna-hora-1409', 1409, 49.949, 15.268,
    ['Dekret kutnohorský', 'Decree of Kutná Hora', 'Decreto de Kutná Hora'],
    ['Václav IV. změnil poměr hlasů na univerzitě ve prospěch Čechů.', 'Wenceslas IV shifts the university’s votes in favour of the Bohemians.', 'Venceslao IV cambia los votos de la universidad a favor de los bohemios.'],
    'https://en.wikipedia.org/wiki/Decree_of_Kutn%C3%A1_Hora'),
  E('grunwald-1410', 1410, 53.48, 20.1,
    ['Bitva u Grunwaldu', 'Battle of Grunwald', 'Batalla de Grunwald'],
    ['Polsko-litevské vojsko zlomilo moc řádu německých rytířů.', 'The Polish–Lithuanian army breaks the power of the Teutonic Order.', 'El ejército polaco-lituano quiebra el poder de la Orden Teutónica.'],
    'https://en.wikipedia.org/wiki/Battle_of_Grunwald'),
  E('hus-1415', 1415, 47.66, 9.18,
    ['Upálení mistra Jana Husa', 'Jan Hus burned at the stake', 'Jan Hus muere en la hoguera'],
    ['Kostnický koncil odsoudil Husa jako kacíře; jiskra husitské revoluce.', 'The Council of Constance condemns Hus as a heretic; the spark of the Hussite revolution.', 'El Concilio de Constanza condena a Hus por hereje; la chispa de la revolución husita.'],
    'https://en.wikipedia.org/wiki/Jan_Hus'),
  E('defenestration-1419', 1419, 50.079, 14.43,
    ['První pražská defenestrace', 'First Defenestration of Prague', 'Primera Defenestración de Praga'],
    ['Dav vedený Želivským vyházel konšely z oken Novoměstské radnice; začíná husitská revoluce.', 'A crowd led by Želivský throws the councillors from the New Town Hall; the Hussite revolution begins.', 'Una multitud guiada por Želivský arroja a los concejales del ayuntamiento; empieza la revolución husita.'],
    'https://en.wikipedia.org/wiki/Defenestrations_of_Prague'),
  E('vitkov-1420', 1420, 50.088, 14.45,
    ['Bitva na Vítkově', 'Battle of Vítkov Hill', 'Batalla de la colina de Vítkov'],
    ['Žižka odrazil první křížovou výpravu proti husitské Praze.', 'Žižka repels the first crusade against Hussite Prague.', 'Žižka repele la primera cruzada contra la Praga husita.'],
    'https://en.wikipedia.org/wiki/Battle_of_V%C3%ADtkov_Hill'),
  E('domazlice-1431', 1431, 49.44, 12.93,
    ['Křižáci prchají od Domažlic', 'Crusaders flee at Domažlice', 'Los cruzados huyen en Domažlice'],
    ['Pátá výprava se rozutekla prý už při zvuku husitského chorálu.', 'The fifth crusade scatters — reputedly at the mere sound of the Hussite hymn.', 'La quinta cruzada se dispersa, según la fama, al solo oír el himno husita.'],
    'https://en.wikipedia.org/wiki/Battle_of_Doma%C5%BElice'),
  E('lipany-1434', 1434, 50.0, 14.87,
    ['Bitva u Lipan', 'Battle of Lipany', 'Batalla de Lipany'],
    ['Umírnění husité porazili polní vojska; konec radikální fáze revoluce.', 'Moderate Hussites defeat the radical field armies; the revolution’s radical phase ends.', 'Los husitas moderados vencen a los ejércitos radicales; termina la fase radical de la revolución.'],
    'https://en.wikipedia.org/wiki/Battle_of_Lipany'),
  E('jihlava-1436', 1436, 49.4, 15.59,
    ['Vyhlášení basilejských kompaktát', 'Compacts of Basel proclaimed', 'Proclamación de las Compactatas de Basilea'],
    ['V Jihlavě stvrzen smír husitů s církví — kalich pro Čechy povolen.', 'The settlement between Hussites and the Church is sealed at Jihlava — the chalice allowed for Bohemia.', 'En Jihlava se sella el acuerdo entre husitas e Iglesia: se permite el cáliz para Bohemia.'],
    'https://en.wikipedia.org/wiki/Compacts_of_Basel'),
  E('constantinople-1453', 1453, 41.013, 28.98,
    ['Pád Konstantinopole', 'Fall of Constantinople', 'Caída de Constantinopla'],
    ['Mehmed II. dobyl město; konec Byzance, tradiční předěl epoch.', 'Mehmed II takes the city; Byzantium ends — a traditional turn of eras.', 'Mehmed II toma la ciudad; fin de Bizancio, un cambio de época tradicional.'],
    'https://en.wikipedia.org/wiki/Fall_of_Constantinople'),
  E('gutenberg-1455', 1455, 50.0, 8.27,
    ['Gutenbergova bible', 'Gutenberg Bible', 'Biblia de Gutenberg'],
    ['V Mohuči dotištěna první velká kniha tištěná pohyblivými literami.', 'The first major book printed with movable type is completed at Mainz.', 'En Maguncia se termina el primer gran libro impreso con tipos móviles.'],
    'https://en.wikipedia.org/wiki/Gutenberg_Bible'),
  E('podebrady-1458', 1458, 50.0875, 14.4215,
    ['Jiří z Poděbrad českým králem', 'George of Poděbrady elected king', 'Jorge de Podiebrad, rey de Bohemia'],
    ['„Husitský král“ zvolen sněmem; navrhl i mírový spolek evropských panovníků.', 'The “Hussite king” is elected by the diet; he even proposed a league of European rulers.', 'El «rey husita» es elegido por la dieta; propuso incluso una liga de soberanos europeos.'],
    'https://en.wikipedia.org/wiki/George_of_Pod%C4%9Bbrady'),

  /* ---------------- early modern ---------------- */
  E('granada-1492', 1492, 37.18, -3.6,
    ['Dokončení reconquisty', 'Reconquista completed', 'Fin de la Reconquista'],
    ['Pád Granady ukončil muslimskou vládu na Pyrenejském poloostrově.', 'The fall of Granada ends Muslim rule in Iberia.', 'La caída de Granada pone fin al dominio musulmán en la península ibérica.'],
    'https://en.wikipedia.org/wiki/Granada_War'),
  E('columbus-1492', 1492, 24.07, -74.48,
    ['Kolumbus v Americe', 'Columbus reaches America', 'Colón llega a América'],
    ['12. října 1492 přistál u ostrova Guanahani; tradiční počátek novověku.', 'On 12 October 1492 he lands at Guanahani; the traditional start of the modern age.', 'El 12 de octubre de 1492 desembarca en Guanahaní; inicio tradicional de la Edad Moderna.'],
    'https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus'),
  E('gama-1498', 1498, 11.25, 75.78,
    ['Vasco da Gama v Indii', 'Vasco da Gama reaches India', 'Vasco da Gama llega a la India'],
    ['Obeplutím Afriky do Kalikatu otevřel námořní cestu ke koření.', 'Rounding Africa to Calicut, he opens the sea route to the spices.', 'Bordeando África hasta Calicut abre la ruta marítima de las especias.'],
    'https://en.wikipedia.org/wiki/Vasco_da_Gama'),
  E('luther-1517', 1517, 51.87, 12.65,
    ['Lutherových 95 tezí', 'Luther’s Ninety-five Theses', 'Las 95 tesis de Lutero'],
    ['Vystoupením ve Wittenbergu začíná evropská reformace.', 'The Wittenberg protest begins the European Reformation.', 'La protesta de Wittenberg inicia la Reforma europea.'],
    'https://en.wikipedia.org/wiki/Ninety-five_Theses'),
  E('magellan-1519', 1519, 37.39, -5.99,
    ['Magalhãesova výprava vyplouvá', 'Magellan’s expedition sets sail', 'Zarpa la expedición de Magallanes'],
    ['Ze Sevilly vyplulo pět lodí; jediná se roku 1522 vrátila — první obeplutí světa.', 'Five ships leave Seville; one returns in 1522 — the first circumnavigation.', 'Cinco naves salen de Sevilla; una vuelve en 1522: la primera circunnavegación.'],
    'https://en.wikipedia.org/wiki/Magellan_expedition'),
  E('tenochtitlan-1521', 1521, 19.43, -99.13,
    ['Pád Tenochtitlánu', 'Fall of Tenochtitlan', 'Caída de Tenochtitlan'],
    ['Cortés dobyl hlavní město Aztéků; začíná španělské Mexiko.', 'Cortés takes the Aztec capital; Spanish Mexico begins.', 'Cortés toma la capital azteca; comienza el México español.'],
    'https://en.wikipedia.org/wiki/Fall_of_Tenochtitlan'),
  E('mohacs-1526', 1526, 45.94, 18.68,
    ['Moháč — Habsburkové na český trůn', 'Mohács — Habsburgs gain the Czech throne', 'Mohács: los Habsburgo llegan al trono checo'],
    ['Ludvík Jagellonský padl v bitvě s Osmany; české země připadly Habsburkům (do 1918).', 'Louis Jagiellon falls to the Ottomans; the Czech lands pass to the Habsburgs (until 1918).', 'Luis Jagellón cae ante los otomanos; las tierras checas pasan a los Habsburgo (hasta 1918).'],
    'https://en.wikipedia.org/wiki/Battle_of_Moh%C3%A1cs'),
  E('cajamarca-1532', 1532, -7.16, -78.51,
    ['Pizarro zajal Atahualpu', 'Pizarro captures Atahualpa', 'Pizarro captura a Atahualpa'],
    ['Přepad v Cajamarce rozhodl o osudu incké říše.', 'The ambush at Cajamarca seals the Inca empire’s fate.', 'La emboscada de Cajamarca sella el destino del Imperio inca.'],
    'https://en.wikipedia.org/wiki/Battle_of_Cajamarca'),
  E('supremacy-1534', 1534, 51.5, -0.125,
    ['Vznik anglikánské církve', 'Church of England breaks with Rome', 'La Iglesia de Inglaterra rompe con Roma'],
    ['Jindřich VIII. se prohlásil hlavou církve v Anglii.', 'Henry VIII declares himself head of the church in England.', 'Enrique VIII se proclama cabeza de la Iglesia en Inglaterra.'],
    'https://en.wikipedia.org/wiki/Acts_of_Supremacy'),
  E('copernicus-1543', 1543, 54.36, 19.68,
    ['Koperníkovo dílo o oběhu těles', 'Copernicus publishes De revolutionibus', 'Copérnico publica De revolutionibus'],
    ['Heliocentrismus vyšel tiskem v roce Koperníkovy smrti.', 'Heliocentrism appears in print in the year of Copernicus’s death.', 'El heliocentrismo se imprime el año de la muerte de Copérnico.'],
    'https://en.wikipedia.org/wiki/De_revolutionibus_orbium_coelestium'),
  E('trent-1545', 1545, 46.07, 11.12,
    ['Tridentský koncil', 'Council of Trent', 'Concilio de Trento'],
    ['Katolická odpověď na reformaci; program protireformace (1545–63).', 'The Catholic answer to the Reformation; the Counter-Reformation programme (1545–63).', 'La respuesta católica a la Reforma; el programa de la Contrarreforma (1545–63).'],
    'https://en.wikipedia.org/wiki/Council_of_Trent'),
  E('augsburg-1555', 1555, 48.37, 10.9,
    ['Augšpurský mír', 'Peace of Augsburg', 'Paz de Augsburgo'],
    ['„Čí země, toho náboženství“ — příměří katolíků a luteránů v říši.', '“Whose realm, his religion” — a truce of Catholics and Lutherans in the empire.', '«De quien es el reino, de él la religión»: tregua entre católicos y luteranos.'],
    'https://en.wikipedia.org/wiki/Peace_of_Augsburg'),
  E('lepanto-1571', 1571, 38.25, 21.32,
    ['Bitva u Lepanta', 'Battle of Lepanto', 'Batalla de Lepanto'],
    ['Svatá liga zlomila mýtus osmanské nepřemožitelnosti na moři.', 'The Holy League breaks the myth of Ottoman invincibility at sea.', 'La Liga Santa quiebra el mito de la invencibilidad otomana en el mar.'],
    'https://en.wikipedia.org/wiki/Battle_of_Lepanto'),
  E('bartholomew-1572', 1572, 48.86, 2.35,
    ['Bartolomějská noc', 'St Bartholomew’s Day massacre', 'Matanza de San Bartolomé'],
    ['V Paříži povražděny tisíce hugenotů; vrchol francouzských náboženských válek.', 'Thousands of Huguenots murdered in Paris; the peak of France’s wars of religion.', 'Miles de hugonotes asesinados en París; cúspide de las guerras de religión francesas.'],
    'https://en.wikipedia.org/wiki/St._Bartholomew%27s_Day_massacre'),
  E('armada-1588', 1588, 50.99, 2.13,
    ['Porážka španělské Armady', 'Defeat of the Spanish Armada', 'Derrota de la Armada Invencible'],
    ['Nezdar invaze do Anglie; počátek anglické námořní převahy.', 'The invasion of England fails; English sea power begins its rise.', 'Fracasa la invasión de Inglaterra; empieza el ascenso naval inglés.'],
    'https://en.wikipedia.org/wiki/Spanish_Armada'),
  E('bruno-1600', 1600, 41.895, 12.472,
    ['Upálení Giordana Bruna', 'Giordano Bruno burned', 'Giordano Bruno en la hoguera'],
    ['Filozof nekonečného vesmíru skončil na hranici v Římě.', 'The philosopher of an infinite universe dies at the stake in Rome.', 'El filósofo del universo infinito muere en la hoguera en Roma.'],
    'https://en.wikipedia.org/wiki/Giordano_Bruno'),
  E('majestat-1609', 1609, 50.0905, 14.4,
    ['Rudolfův majestát', 'Rudolf II’s Letter of Majesty', 'Carta de Majestad de Rodolfo II'],
    ['Císař zaručil českým nekatolíkům svobodu vyznání.', 'The emperor guarantees religious freedom to Bohemia’s non-Catholics.', 'El emperador garantiza libertad religiosa a los no católicos de Bohemia.'],
    'https://en.wikipedia.org/wiki/Letter_of_Majesty'),
  E('defenestration-1618', 1618, 50.0902, 14.3995,
    ['Třetí pražská defenestrace', 'Defenestration of Prague, 1618', 'Defenestración de Praga de 1618'],
    ['Vyhození místodržících z oken Hradu zažehlo třicetiletou válku.', 'Governors thrown from the Castle windows ignite the Thirty Years’ War.', 'Los gobernadores arrojados por las ventanas del Castillo encienden la guerra de los Treinta Años.'],
    'https://en.wikipedia.org/wiki/Defenestrations_of_Prague'),
  E('bila-hora-1620', 1620, 50.078, 14.318,
    ['Bitva na Bílé hoře', 'Battle of White Mountain', 'Batalla de la Montaña Blanca'],
    ['Porážka stavovského povstání; začíná rekatolizace a exil nekatolíků.', 'The estates’ revolt is crushed; re-Catholicization and Protestant exile follow.', 'La revuelta de los estamentos es aplastada; siguen la recatolización y el exilio protestante.'],
    'https://en.wikipedia.org/wiki/Battle_of_White_Mountain'),
  E('execution-1621', 1621, 50.0875, 14.4205,
    ['Staroměstská exekuce', 'Old Town Square execution', 'Ejecución de la Plaza de la Ciudad Vieja'],
    ['21. června popraveno 27 vůdců stavovského povstání.', 'On 21 June, 27 leaders of the estates’ revolt are executed.', 'El 21 de junio son ejecutados 27 líderes de la revuelta estamental.'],
    'https://en.wikipedia.org/wiki/Old_Town_Square_execution'),
  E('verneuerte-1627', 1627, 50.092, 14.404,
    ['Obnovené zřízení zemské', 'Renewed Land Ordinance', 'Constitución Renovada'],
    ['Absolutismus, dědičný trůn Habsburků a jediné povolené vyznání.', 'Absolutism, a hereditary Habsburg throne and one permitted faith.', 'Absolutismo, trono hereditario Habsburgo y una sola fe permitida.'],
    'https://en.wikipedia.org/wiki/Verneuerte_Landesordnung'),
  E('lutzen-1632', 1632, 51.25, 12.14,
    ['Bitva u Lützenu', 'Battle of Lützen', 'Batalla de Lützen'],
    ['Švédové zvítězili, ale padl král Gustav II. Adolf.', 'The Swedes win, but King Gustavus Adolphus falls.', 'Los suecos vencen, pero cae el rey Gustavo Adolfo.'],
    'https://en.wikipedia.org/wiki/Battle_of_L%C3%BCtzen'),
  E('valdstejn-1634', 1634, 50.08, 12.37,
    ['Zavraždění Albrechta z Valdštejna', 'Assassination of Wallenstein', 'Asesinato de Wallenstein'],
    ['Císařský generalissimus zabit v Chebu vlastními důstojníky.', 'The imperial generalissimo is killed at Cheb by his own officers.', 'El generalísimo imperial muere en Cheb a manos de sus oficiales.'],
    'https://en.wikipedia.org/wiki/Albrecht_von_Wallenstein'),
  E('westphalia-1648', 1648, 51.96, 7.63,
    ['Vestfálský mír', 'Peace of Westphalia', 'Paz de Westfalia'],
    ['Konec třicetileté války; počátek novodobého systému suverénních států.', 'The Thirty Years’ War ends; the modern system of sovereign states begins.', 'Termina la guerra de los Treinta Años; nace el sistema moderno de estados soberanos.'],
    'https://en.wikipedia.org/wiki/Peace_of_Westphalia'),
  E('charles-i-1649', 1649, 51.504, -0.127,
    ['Poprava Karla I.', 'Execution of Charles I', 'Ejecución de Carlos I'],
    ['Anglická revoluce dala popravit krále; nastává Cromwellova republika.', 'The English revolution executes its king; Cromwell’s republic follows.', 'La revolución inglesa ejecuta a su rey; sigue la república de Cromwell.'],
    'https://en.wikipedia.org/wiki/Execution_of_Charles_I'),
  E('vienna-1683', 1683, 48.21, 16.37,
    ['Bitva u Vídně', 'Battle of Vienna', 'Batalla de Viena'],
    ['Jan III. Sobieski zlomil osmanské obléhání; obrat ve prospěch Evropy.', 'Jan III Sobieski breaks the Ottoman siege; the tide turns for Europe.', 'Juan III Sobieski rompe el asedio otomano; la marea cambia a favor de Europa.'],
    'https://en.wikipedia.org/wiki/Battle_of_Vienna'),
  E('principia-1687', 1687, 51.53, -0.1,
    ['Newtonova Principia', 'Newton’s Principia', 'Principia de Newton'],
    ['Zákony pohybu a gravitace — základ moderní fyziky.', 'The laws of motion and gravitation — the foundation of modern physics.', 'Las leyes del movimiento y la gravitación: fundamento de la física moderna.'],
    'https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica'),
  E('bill-of-rights-1689', 1689, 51.4995, -0.1245,
    ['Anglická Listina práv', 'English Bill of Rights', 'Declaración de Derechos inglesa'],
    ['Po „slavné revoluci“ parlament natrvalo omezil moc koruny.', 'After the Glorious Revolution, Parliament permanently limits the crown.', 'Tras la Revolución Gloriosa, el Parlamento limita la corona para siempre.'],
    'https://en.wikipedia.org/wiki/Bill_of_Rights_1689'),
  E('union-1707', 1707, 55.95, -3.19,
    ['Unie Anglie a Skotska', 'Union of England and Scotland', 'Unión de Inglaterra y Escocia'],
    ['Vzniká Království Velké Británie.', 'The Kingdom of Great Britain is created.', 'Se crea el Reino de Gran Bretaña.'],
    'https://en.wikipedia.org/wiki/Acts_of_Union_1707'),
  E('pragmatic-1713', 1713, 48.208, 16.373,
    ['Pragmatická sankce', 'Pragmatic Sanction', 'Pragmática Sanción'],
    ['Karel VI. zajistil nedělitelnost monarchie a nástupnictví i po přeslici.', 'Charles VI secures the monarchy’s unity and female succession.', 'Carlos VI asegura la unidad de la monarquía y la sucesión femenina.'],
    'https://en.wikipedia.org/wiki/Pragmatic_Sanction_of_1713'),
  E('maria-theresa-1740', 1740, 48.205, 16.365,
    ['Nástup Marie Terezie', 'Maria Theresa’s accession', 'Ascenso de María Teresa'],
    ['Nástupnictví napadly evropské mocnosti; války o rakouské dědictví.', 'Her succession is challenged; the wars of the Austrian succession follow.', 'Su sucesión es impugnada; siguen las guerras de sucesión austriaca.'],
    'https://en.wikipedia.org/wiki/Maria_Theresa'),
  E('silesia-1742', 1742, 51.11, 17.03,
    ['Ztráta Slezska', 'Loss of Silesia', 'Pérdida de Silesia'],
    ['Většina Slezska připadla Prusku — nejbohatší země Koruny české pryč.', 'Most of Silesia passes to Prussia — the Bohemian Crown’s richest land lost.', 'La mayor parte de Silesia pasa a Prusia: se pierde la tierra más rica de la Corona checa.'],
    'https://en.wikipedia.org/wiki/First_Silesian_War'),
  E('lisbon-1755', 1755, 38.71, -9.14,
    ['Zemětřesení v Lisabonu', 'Lisbon earthquake', 'Terremoto de Lisboa'],
    ['Katastrofa otřásla i osvícenskou vírou v dobrotivý řád světa.', 'The catastrophe shakes Enlightenment faith in a benign world order.', 'La catástrofe sacude la fe ilustrada en un orden benévolo del mundo.'],
    'https://en.wikipedia.org/wiki/1755_Lisbon_earthquake'),
  E('lobositz-1756', 1756, 50.51, 14.05,
    ['Začátek sedmileté války', 'Seven Years’ War begins', 'Comienza la guerra de los Siete Años'],
    ['První bitva se odehrála u Lovosic v Čechách; válčilo se na třech kontinentech.', 'Its first battle is fought at Lobositz in Bohemia; the war spans three continents.', 'Su primera batalla se libra en Lobositz, Bohemia; la guerra abarca tres continentes.'],
    'https://en.wikipedia.org/wiki/Battle_of_Lobositz'),
  E('boston-1773', 1773, 42.36, -71.05,
    ['Bostonské pití čaje', 'Boston Tea Party', 'Motín del té de Boston'],
    ['Kolonisté naházeli čaj do moře; cesta k americké revoluci.', 'Colonists dump the tea into the harbour; the road to revolution.', 'Los colonos arrojan el té al mar; el camino a la revolución.'],
    'https://en.wikipedia.org/wiki/Boston_Tea_Party'),
  E('school-1774', 1774, 48.211, 16.36,
    ['Všeobecný školní řád', 'General School Ordinance', 'Reglamento escolar general'],
    ['Marie Terezie zavedla vzdělávací povinnost v monarchii.', 'Maria Theresa introduces compulsory schooling across the monarchy.', 'María Teresa introduce la escolarización obligatoria en la monarquía.'],
    'https://en.wikipedia.org/wiki/Education_in_Austria'),
  E('chlumec-1775', 1775, 50.15, 15.46,
    ['Nevolnické povstání', 'Peasant uprising of 1775', 'Levantamiento campesino de 1775'],
    ['Selská rebelie poražená u Chlumce („dopadli jak sedláci u Chlumce“).', 'The peasant revolt crushed at Chlumec — proverbial in Czech to this day.', 'La revuelta campesina aplastada en Chlumec, proverbial en checo hasta hoy.'],
    'https://en.wikipedia.org/wiki/Peasant_uprising_of_1775'),
  E('independence-1776', 1776, 39.95, -75.16,
    ['Deklarace nezávislosti USA', 'US Declaration of Independence', 'Declaración de Independencia de EE. UU.'],
    ['4. července vyhlášeno, že „všichni lidé jsou stvořeni sobě rovni“.', 'On 4 July it proclaims that “all men are created equal”.', 'El 4 de julio proclama que «todos los hombres son creados iguales».'],
    'https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence'),
  E('patents-1781', 1781, 48.207, 16.37,
    ['Zrušení nevolnictví a toleranční patent', 'Serfdom abolished; Patent of Toleration', 'Abolición de la servidumbre; Patente de Tolerancia'],
    ['Josef II. zrušil nevolnictví a povolil nekatolická vyznání.', 'Joseph II ends serfdom and tolerates non-Catholic faiths.', 'José II suprime la servidumbre y tolera las confesiones no católicas.'],
    'https://en.wikipedia.org/wiki/Serfdom_Patent_(1781)'),
  E('bastille-1789', 1789, 48.853, 2.369,
    ['Dobytí Bastily', 'Storming of the Bastille', 'Toma de la Bastilla'],
    ['14. červenec 1789 — začátek Velké francouzské revoluce.', '14 July 1789 — the French Revolution begins.', '14 de julio de 1789: comienza la Revolución francesa.'],
    'https://en.wikipedia.org/wiki/Storming_of_the_Bastille'),
  E('louis-1793', 1793, 48.8656, 2.3212,
    ['Poprava Ludvíka XVI.', 'Execution of Louis XVI', 'Ejecución de Luis XVI'],
    ['Gilotina na náměstí Revoluce; následoval jakobínský teror.', 'The guillotine on the Place de la Révolution; the Terror follows.', 'La guillotina en la plaza de la Revolución; sigue el Terror.'],
    'https://en.wikipedia.org/wiki/Execution_of_Louis_XVI'),

  /* ---------------- long 19th century ---------------- */
  E('napoleon-1804', 1804, 48.8529, 2.3499,
    ['Napoleon císařem; Code civil', 'Napoleon emperor; Code civil', 'Napoleón emperador; Código civil'],
    ['Korunovace v Notre-Dame; občanský zákoník ovlivnil právo celé Evropy.', 'Crowned at Notre-Dame; his civil code shaped law across Europe.', 'Coronado en Notre-Dame; su código civil marcó el derecho de toda Europa.'],
    'https://en.wikipedia.org/wiki/Coronation_of_Napoleon'),
  E('trafalgar-1805', 1805, 36.28, -6.24,
    ['Bitva u Trafalgaru', 'Battle of Trafalgar', 'Batalla de Trafalgar'],
    ['Nelson zničil francouzsko-španělské loďstvo; Británie vládne mořím.', 'Nelson destroys the Franco-Spanish fleet; Britannia rules the waves.', 'Nelson destruye la flota franco-española; Britania domina los mares.'],
    'https://en.wikipedia.org/wiki/Battle_of_Trafalgar'),
  E('austerlitz-1805', 1805, 49.13, 16.76,
    ['Bitva u Slavkova', 'Battle of Austerlitz', 'Batalla de Austerlitz'],
    ['„Bitva tří císařů“ na Moravě — Napoleonovo mistrovské vítězství.', 'The “battle of the three emperors” in Moravia — Napoleon’s masterpiece.', 'La «batalla de los tres emperadores» en Moravia: la obra maestra de Napoleón.'],
    'https://en.wikipedia.org/wiki/Battle_of_Austerlitz'),
  E('hre-end-1806', 1806, 48.2085, 16.3735,
    ['Zánik Svaté říše římské', 'End of the Holy Roman Empire', 'Fin del Sacro Imperio'],
    ['František II. složil říšskou korunu; tisíciletá říše skončila.', 'Francis II lays down the imperial crown; the thousand-year empire ends.', 'Francisco II depone la corona imperial; el imperio milenario se acaba.'],
    'https://en.wikipedia.org/wiki/Dissolution_of_the_Holy_Roman_Empire'),
  E('borodino-1812', 1812, 55.52, 35.82,
    ['Napoleonovo tažení do Ruska', 'Napoleon’s Russian campaign', 'Campaña rusa de Napoleón'],
    ['Bitva u Borodina, požár Moskvy a zkáza Velké armády v zimě.', 'Borodino, the burning of Moscow and the Grande Armée’s winter ruin.', 'Borodinó, el incendio de Moscú y la ruina invernal de la Grande Armée.'],
    'https://en.wikipedia.org/wiki/French_invasion_of_Russia'),
  E('leipzig-1813', 1813, 51.34, 12.37,
    ['Bitva národů u Lipska', 'Battle of the Nations at Leipzig', 'Batalla de las Naciones en Leipzig'],
    ['Největší bitva napoleonských válek; Napoleon vytlačen z Německa.', 'The largest battle of the Napoleonic wars; Napoleon is driven from Germany.', 'La mayor batalla de las guerras napoleónicas; Napoleón es expulsado de Alemania.'],
    'https://en.wikipedia.org/wiki/Battle_of_Leipzig'),
  E('waterloo-1815', 1815, 50.68, 4.41,
    ['Waterloo', 'Waterloo', 'Waterloo'],
    ['Napoleonova konečná porážka; sto dní skončilo.', 'Napoleon’s final defeat; the Hundred Days end.', 'La derrota final de Napoleón; terminan los Cien Días.'],
    'https://en.wikipedia.org/wiki/Battle_of_Waterloo'),
  E('vienna-congress-1815', 1815, 48.2065, 16.368,
    ['Vídeňský kongres', 'Congress of Vienna', 'Congreso de Viena'],
    ['Metternichova Evropa: obnova starých pořádků a rovnováhy sil.', 'Metternich’s Europe: restoration and the balance of power.', 'La Europa de Metternich: restauración y equilibrio de poder.'],
    'https://en.wikipedia.org/wiki/Congress_of_Vienna'),
  E('greece-1821', 1821, 37.94, 22.93,
    ['Řecké povstání', 'Greek War of Independence', 'Guerra de independencia griega'],
    ['Řekové povstali proti Osmanům; první úspěšné národní hnutí éry.', 'The Greeks rise against the Ottomans; the era’s first successful national movement.', 'Los griegos se alzan contra los otomanos; el primer movimiento nacional triunfante de la era.'],
    'https://en.wikipedia.org/wiki/Greek_War_of_Independence'),
  E('july-1830', 1830, 48.87, 2.35,
    ['Červencová revoluce', 'July Revolution', 'Revolución de Julio'],
    ['Paříž svrhla Bourbony; vlna revolucí (Belgie, Polsko).', 'Paris topples the Bourbons; a wave of revolutions follows (Belgium, Poland).', 'París derriba a los Borbones; sigue una ola de revoluciones (Bélgica, Polonia).'],
    'https://en.wikipedia.org/wiki/July_Revolution'),
  E('paris-1848', 1848, 48.856, 2.341,
    ['Revoluce 1848 („jaro národů“)', 'Revolutions of 1848 (Springtime of Nations)', 'Revoluciones de 1848 (Primavera de los Pueblos)'],
    ['Z Paříže se revoluce rozlila do Vídně, Berlína, Itálie i Uher.', 'From Paris the revolution spreads to Vienna, Berlin, Italy and Hungary.', 'Desde París la revolución se extiende a Viena, Berlín, Italia y Hungría.'],
    'https://en.wikipedia.org/wiki/Revolutions_of_1848'),
  E('prague-1848', 1848, 50.0865, 14.4185,
    ['Slovanský sjezd a červnové povstání', 'Slavic Congress and June uprising', 'Congreso Eslavo y levantamiento de junio'],
    ['Praha 1848: sjezd Slovanů, barikády, potlačení Windischgrätzem; robota zrušena.', 'Prague 1848: the Slavic Congress, barricades, Windischgrätz’s crackdown; corvée labour abolished.', 'Praga 1848: congreso eslavo, barricadas, represión de Windischgrätz; se abolió la corvea.'],
    'https://en.wikipedia.org/wiki/Prague_Slavic_Congress,_1848'),
  E('crimea-1853', 1853, 44.6, 33.53,
    ['Krymská válka', 'Crimean War', 'Guerra de Crimea'],
    ['Rusko proti Osmanům, Británii a Francii; zrodila se moderní válečná medicína.', 'Russia against the Ottomans, Britain and France; modern war medicine is born.', 'Rusia contra otomanos, británicos y franceses; nace la medicina de guerra moderna.'],
    'https://en.wikipedia.org/wiki/Crimean_War'),
  E('darwin-1859', 1859, 51.497, -0.1425,
    ['O původu druhů', 'On the Origin of Species', 'El origen de las especies'],
    ['Darwin publikoval evoluční teorii přírodním výběrem.', 'Darwin publishes evolution by natural selection.', 'Darwin publica la evolución por selección natural.'],
    'https://en.wikipedia.org/wiki/On_the_Origin_of_Species'),
  E('solferino-1859', 1859, 45.37, 10.57,
    ['Solferino — zrod Červeného kříže', 'Solferino — birth of the Red Cross', 'Solferino: nace la Cruz Roja'],
    ['Hrůzy bitvy přivedly Dunanta k založení Červeného kříže (1863).', 'The battle’s horrors lead Dunant to found the Red Cross (1863).', 'Los horrores de la batalla llevan a Dunant a fundar la Cruz Roja (1863).'],
    'https://en.wikipedia.org/wiki/Battle_of_Solferino'),
  E('serfdom-1861', 1861, 59.94, 30.31,
    ['Zrušení nevolnictví v Rusku', 'Emancipation of the Russian serfs', 'Emancipación de los siervos rusos'],
    ['Alexandr II. osvobodil přes 20 milionů nevolníků.', 'Alexander II frees over 20 million serfs.', 'Alejandro II libera a más de 20 millones de siervos.'],
    'https://en.wikipedia.org/wiki/Emancipation_reform_of_1861'),
  E('italy-1861', 1861, 45.07, 7.69,
    ['Sjednocení Itálie', 'Unification of Italy', 'Unificación de Italia'],
    ['Viktor Emanuel II. prohlášen králem Itálie (Řím připojen 1870).', 'Victor Emmanuel II proclaimed king of Italy (Rome joined in 1870).', 'Víctor Manuel II proclamado rey de Italia (Roma se unió en 1870).'],
    'https://en.wikipedia.org/wiki/Italian_unification'),
  E('sumter-1861', 1861, 32.75, -79.87,
    ['Americká občanská válka', 'American Civil War', 'Guerra de Secesión'],
    ['Útokem na Fort Sumter začala válka Severu proti Jihu (1861–65).', 'The attack on Fort Sumter opens the war between North and South (1861–65).', 'El ataque a Fort Sumter abre la guerra entre el Norte y el Sur (1861–65).'],
    'https://en.wikipedia.org/wiki/American_Civil_War'),
  E('lincoln-1865', 1865, 38.897, -77.026,
    ['Konec občanské války; atentát na Lincolna', 'Civil war ends; Lincoln assassinated', 'Fin de la guerra; asesinato de Lincoln'],
    ['Kapitulace Jihu a zrušení otroctví; prezident zastřelen pět dní poté.', 'The South surrenders and slavery ends; the president is shot five days later.', 'El Sur capitula y se abole la esclavitud; el presidente es asesinado cinco días después.'],
    'https://en.wikipedia.org/wiki/Assassination_of_Abraham_Lincoln'),
  E('koniggratz-1866', 1866, 50.29, 15.76,
    ['Bitva u Hradce Králové', 'Battle of Königgrätz', 'Batalla de Sadowa'],
    ['Prusko rozdrtilo Rakousko na českém bojišti; cesta k německé jednotě.', 'Prussia crushes Austria on Bohemian soil; the road to German unity.', 'Prusia aplasta a Austria en suelo bohemio; el camino a la unidad alemana.'],
    'https://en.wikipedia.org/wiki/Battle_of_K%C3%B6niggr%C3%A4tz'),
  E('ausgleich-1867', 1867, 47.5, 19.05,
    ['Rakousko-uherské vyrovnání', 'Austro-Hungarian Compromise', 'Compromiso austrohúngaro'],
    ['Monarchie se rozdělila na dvě poloviny; české naděje na vyrovnání zklamány.', 'The monarchy splits in two; Czech hopes of a similar deal are dashed.', 'La monarquía se divide en dos; las esperanzas checas de un pacto similar se frustran.'],
    'https://en.wikipedia.org/wiki/Austro-Hungarian_Compromise_of_1867'),
  E('theatre-1868', 1868, 50.081, 14.4135,
    ['Základní kámen Národního divadla', 'National Theatre foundation stone', 'Primera piedra del Teatro Nacional'],
    ['„Národ sobě“ — vyvrcholení českého obrozeneckého hnutí (otevřeno 1881/1883).', '“The nation to itself” — the Czech revival’s crowning effort (opened 1881/1883).', '«La nación para sí misma»: culminación del renacimiento checo (abierto en 1881/1883).'],
    'https://en.wikipedia.org/wiki/National_Theatre_(Prague)'),
  E('sedan-1870', 1870, 49.7, 4.94,
    ['Bitva u Sedanu', 'Battle of Sedan', 'Batalla de Sedán'],
    ['Kapitulace Napoleona III.; pád francouzského císařství.', 'Napoleon III capitulates; the French empire falls.', 'Napoleón III capitula; cae el imperio francés.'],
    'https://en.wikipedia.org/wiki/Battle_of_Sedan'),
  E('versailles-1871', 1871, 48.8, 2.13,
    ['Vyhlášení Německého císařství', 'German Empire proclaimed', 'Proclamación del Imperio alemán'],
    ['V zrcadlovém sále ve Versailles sjednoceno Německo pod Pruskem.', 'In the Hall of Mirrors, Germany is united under Prussia.', 'En la Galería de los Espejos, Alemania se unifica bajo Prusia.'],
    'https://en.wikipedia.org/wiki/Proclamation_of_the_German_Empire'),
  E('berlin-1878', 1878, 52.52, 13.4,
    ['Berlínský kongres', 'Congress of Berlin', 'Congreso de Berlín'],
    ['Přerozdělení Balkánu; Rakousko-Uhersko obsadilo Bosnu.', 'The Balkans redrawn; Austria-Hungary occupies Bosnia.', 'Se redibujan los Balcanes; Austria-Hungría ocupa Bosnia.'],
    'https://en.wikipedia.org/wiki/Congress_of_Berlin'),
  E('university-1882', 1882, 50.0885, 14.4175,
    ['Rozdělení pražské univerzity', 'Prague university divided', 'División de la universidad de Praga'],
    ['Karlo-Ferdinandova univerzita rozdělena na českou a německou.', 'The university splits into Czech and German institutions.', 'La universidad se divide en una checa y otra alemana.'],
    'https://en.wikipedia.org/wiki/Charles_University'),
  E('berlin-1885', 1885, 52.517, 13.39,
    ['Berlínská konference o Africe', 'Berlin Conference on Africa', 'Conferencia de Berlín sobre África'],
    ['Evropské mocnosti si rozdělily pravidla pro „dělení Afriky“.', 'The European powers set the rules for the Scramble for Africa.', 'Las potencias europeas fijan las reglas del reparto de África.'],
    'https://en.wikipedia.org/wiki/Berlin_Conference'),
  E('olympics-1896', 1896, 37.97, 23.74,
    ['Obnovení olympijských her', 'Modern Olympics revived', 'Renacen los Juegos Olímpicos'],
    ['V Athénách se po půldruhém tisíciletí opět konaly hry.', 'After a millennium and a half, the games return at Athens.', 'Tras milenio y medio, los juegos vuelven en Atenas.'],
    'https://en.wikipedia.org/wiki/1896_Summer_Olympics'),
  E('russia-1905', 1905, 59.93, 30.33,
    ['Revoluce 1905 v Rusku', 'Russian Revolution of 1905', 'Revolución rusa de 1905'],
    ['„Krvavá neděle“ a porážka od Japonska vynutily první dumu.', '“Bloody Sunday” and defeat by Japan force the first Duma.', 'El «Domingo Sangriento» y la derrota ante Japón fuerzan la primera Duma.'],
    'https://en.wikipedia.org/wiki/1905_Russian_Revolution'),

  /* ---------------- 20th century ---------------- */
  E('sarajevo-1914', 1914, 43.858, 18.428,
    ['Sarajevský atentát', 'Assassination in Sarajevo', 'Atentado de Sarajevo'],
    ['28. června zastřelen následník trůnu Ferdinand d’Este; rozbuška první světové války.', 'On 28 June the heir Franz Ferdinand is shot; the fuse of the First World War.', 'El 28 de junio es asesinado el heredero Francisco Fernando; la mecha de la Gran Guerra.'],
    'https://en.wikipedia.org/wiki/Assassination_of_Archduke_Franz_Ferdinand'),
  E('verdun-1916', 1916, 49.2, 5.43,
    ['Verdun', 'Battle of Verdun', 'Batalla de Verdún'],
    ['Deset měsíců mlýnku na maso; symbol zákopové války (spolu se Sommou).', 'Ten months of slaughter; the emblem of trench warfare (with the Somme).', 'Diez meses de matanza; el emblema de la guerra de trincheras (junto al Somme).'],
    'https://en.wikipedia.org/wiki/Battle_of_Verdun'),
  E('zborov-1917', 1917, 49.67, 25.1,
    ['Bitva u Zborova', 'Battle of Zborov', 'Batalla de Zborov'],
    ['Českoslovenští legionáři se poprvé prosadili jako samostatná síla.', 'The Czechoslovak Legions first prove themselves as a force of their own.', 'Las legiones checoslovacas se afirman por primera vez como fuerza propia.'],
    'https://en.wikipedia.org/wiki/Battle_of_Zborov_(1917)'),
  E('october-1917', 1917, 59.95, 30.35,
    ['Říjnová revoluce', 'October Revolution', 'Revolución de Octubre'],
    ['Bolševici svrhli prozatímní vládu; vzniká sovětské Rusko.', 'The Bolsheviks topple the Provisional Government; Soviet Russia is born.', 'Los bolcheviques derriban al Gobierno provisional; nace la Rusia soviética.'],
    'https://en.wikipedia.org/wiki/October_Revolution'),
  E('czechoslovakia-1918', 1918, 50.087, 14.428,
    ['28. říjen — vznik Československa', '28 October — Czechoslovakia founded', '28 de octubre: nace Checoslovaquia'],
    ['V Praze vyhlášen samostatný stát; prezidentem T. G. Masaryk.', 'The independent state is proclaimed in Prague; T. G. Masaryk becomes president.', 'En Praga se proclama el estado independiente; T. G. Masaryk, presidente.'],
    'https://en.wikipedia.org/wiki/First_Czechoslovak_Republic'),
  E('armistice-1918', 1918, 49.43, 2.9,
    ['Konec první světové války', 'First World War ends', 'Fin de la Primera Guerra Mundial'],
    ['11. 11. v 11 hodin podepsáno příměří v Compiègne.', 'The armistice is signed at Compiègne — the 11th hour of the 11th day of the 11th month.', 'El armisticio se firma en Compiègne: la hora 11 del día 11 del mes 11.'],
    'https://en.wikipedia.org/wiki/Armistice_of_11_November_1918'),
  E('versailles-1919', 1919, 48.805, 2.12,
    ['Versailleská smlouva', 'Treaty of Versailles', 'Tratado de Versalles'],
    ['Mír s Německem překreslil Evropu — a zasel hořkost.', 'The peace with Germany redraws Europe — and sows resentment.', 'La paz con Alemania redibuja Europa y siembra resentimiento.'],
    'https://en.wikipedia.org/wiki/Treaty_of_Versailles'),
  E('ussr-1922', 1922, 55.75, 37.62,
    ['Vznik SSSR', 'USSR founded', 'Fundación de la URSS'],
    ['Sovětský svaz ustaven jako federace republik pod vládou bolševiků.', 'The Soviet Union is constituted as a federation under Bolshevik rule.', 'La Unión Soviética se constituye como federación bajo dominio bolchevique.'],
    'https://en.wikipedia.org/wiki/Treaty_on_the_Creation_of_the_USSR'),
  E('rome-1922', 1922, 41.9, 12.5,
    ['Pochod na Řím', 'March on Rome', 'Marcha sobre Roma'],
    ['Mussolini se chopil moci; první fašistický režim v Evropě.', 'Mussolini seizes power; Europe’s first Fascist regime.', 'Mussolini toma el poder; el primer régimen fascista de Europa.'],
    'https://en.wikipedia.org/wiki/March_on_Rome'),
  E('crash-1929', 1929, 40.706, -74.009,
    ['Krach na newyorské burze', 'Wall Street Crash', 'Crac de Wall Street'],
    ['„Černý čtvrtek“ spustil světovou hospodářskou krizi.', '“Black Thursday” sets off the Great Depression.', 'El «Jueves Negro» desata la Gran Depresión.'],
    'https://en.wikipedia.org/wiki/Wall_Street_crash_of_1929'),
  E('hitler-1933', 1933, 52.52, 13.38,
    ['Hitler kancléřem', 'Hitler becomes chancellor', 'Hitler llega a canciller'],
    ['30. ledna jmenován; demokracie zlikvidována během měsíců.', 'Appointed on 30 January; democracy is dismantled within months.', 'Nombrado el 30 de enero; la democracia es desmantelada en meses.'],
    'https://en.wikipedia.org/wiki/Adolf_Hitler%27s_rise_to_power'),
  E('nuremberg-1935', 1935, 49.45, 11.08,
    ['Norimberské zákony', 'Nuremberg Laws', 'Leyes de Núremberg'],
    ['Rasové zákony zbavily židovské obyvatele občanských práv.', 'The racial laws strip Jewish citizens of their civil rights.', 'Las leyes raciales privan a los judíos de sus derechos civiles.'],
    'https://en.wikipedia.org/wiki/Nuremberg_Laws'),
  E('spain-1936', 1936, 40.42, -3.7,
    ['Španělská občanská válka', 'Spanish Civil War', 'Guerra civil española'],
    ['Frankovo povstání proti republice; zkušebna sil před světovou válkou.', 'Franco’s rising against the republic; a proving ground before the world war.', 'El alzamiento de Franco contra la república; banco de pruebas antes de la guerra mundial.'],
    'https://en.wikipedia.org/wiki/Spanish_Civil_War'),
  E('masaryk-1937', 1937, 50.12, 13.95,
    ['Úmrtí T. G. Masaryka', 'Death of T. G. Masaryk', 'Muerte de T. G. Masaryk'],
    ['Prezident Osvoboditel zemřel v Lánech; truchlil celý stát.', 'The President-Liberator dies at Lány; the whole state mourns.', 'El presidente libertador muere en Lány; todo el estado lo llora.'],
    'https://en.wikipedia.org/wiki/Tom%C3%A1%C5%A1_Garrigue_Masaryk'),
  E('anschluss-1938', 1938, 48.203, 16.36,
    ['Anšlus Rakouska', 'Anschluss of Austria', 'Anschluss de Austria'],
    ['Německo pohltilo Rakousko; Československo v kleštích.', 'Germany absorbs Austria; Czechoslovakia is caught in pincers.', 'Alemania absorbe Austria; Checoslovaquia queda atenazada.'],
    'https://en.wikipedia.org/wiki/Anschluss'),
  E('munich-1938', 1938, 48.14, 11.58,
    ['Mnichovská dohoda', 'Munich Agreement', 'Acuerdo de Múnich'],
    ['„O nás bez nás“ — pohraničí odstoupeno Německu 30. září 1938.', '“About us, without us” — the borderlands ceded to Germany, 30 September 1938.', '«Sobre nosotros, sin nosotros»: los Sudetes cedidos a Alemania el 30 de septiembre de 1938.'],
    'https://en.wikipedia.org/wiki/Munich_Agreement'),
  E('occupation-1939', 1939, 50.09, 14.4,
    ['15. březen — okupace zbytku Česka', '15 March — occupation of the Czech rump', '15 de marzo: ocupación del resto checo'],
    ['Wehrmacht obsadil Prahu; vyhlášen Protektorát Čechy a Morava.', 'The Wehrmacht enters Prague; the Protectorate of Bohemia and Moravia is declared.', 'La Wehrmacht entra en Praga; se proclama el Protectorado de Bohemia y Moravia.'],
    'https://en.wikipedia.org/wiki/German_occupation_of_Czechoslovakia'),
  E('westerplatte-1939', 1939, 54.41, 18.67,
    ['1. září — začátek druhé světové války', '1 September — Second World War begins', '1 de septiembre: comienza la Segunda Guerra Mundial'],
    ['Německý útok na Polsko; Británie a Francie vyhlásily válku.', 'Germany attacks Poland; Britain and France declare war.', 'Alemania ataca Polonia; Gran Bretaña y Francia declaran la guerra.'],
    'https://en.wikipedia.org/wiki/Invasion_of_Poland'),
  E('britain-1940', 1940, 51.51, -0.11,
    ['Bitva o Británii', 'Battle of Britain', 'Batalla de Inglaterra'],
    ['RAF (i s čs. letci) odrazila Luftwaffe; první Hitlerova porážka.', 'The RAF — Czechoslovak pilots included — repels the Luftwaffe; Hitler’s first defeat.', 'La RAF, con pilotos checoslovacos, repele a la Luftwaffe; la primera derrota de Hitler.'],
    'https://en.wikipedia.org/wiki/Battle_of_Britain'),
  E('barbarossa-1941', 1941, 52.08, 23.65,
    ['Operace Barbarossa', 'Operation Barbarossa', 'Operación Barbarroja'],
    ['22. června napadlo Německo Sovětský svaz — největší invaze dějin.', 'On 22 June Germany invades the Soviet Union — history’s largest invasion.', 'El 22 de junio Alemania invade la URSS: la mayor invasión de la historia.'],
    'https://en.wikipedia.org/wiki/Operation_Barbarossa'),
  E('pearl-harbor-1941', 1941, 21.36, -157.95,
    ['Pearl Harbor', 'Pearl Harbor', 'Pearl Harbor'],
    ['Japonský útok vtáhl USA do války.', 'The Japanese attack brings the United States into the war.', 'El ataque japonés mete a Estados Unidos en la guerra.'],
    'https://en.wikipedia.org/wiki/Attack_on_Pearl_Harbor'),
  E('wannsee-1942', 1942, 52.43, 13.16,
    ['Konference ve Wannsee', 'Wannsee Conference', 'Conferencia de Wannsee'],
    ['Nacistická byrokracie koordinovala „konečné řešení“ — vyvraždění evropských Židů.', 'Nazi bureaucrats coordinate the “Final Solution” — the murder of Europe’s Jews.', 'Los burócratas nazis coordinan la «solución final»: el exterminio de los judíos de Europa.'],
    'https://en.wikipedia.org/wiki/Wannsee_Conference'),
  E('heydrich-1942', 1942, 50.11, 14.46,
    ['Atentát na Heydricha', 'Assassination of Heydrich', 'Atentado contra Heydrich'],
    ['Gabčík s Kubišem zaútočili 27. května; následoval teror heydrichiády.', 'Gabčík and Kubiš strike on 27 May; a wave of terror follows.', 'Gabčík y Kubiš atacan el 27 de mayo; sigue una ola de terror.'],
    'https://en.wikipedia.org/wiki/Assassination_of_Reinhard_Heydrich'),
  E('lidice-1942', 1942, 50.143, 14.19,
    ['Vyhlazení Lidic', 'Destruction of Lidice', 'Destrucción de Lidice'],
    ['Obec srovnána se zemí jako odveta; muži zastřeleni, ženy a děti odvlečeny.', 'The village is razed in reprisal; the men shot, women and children deported.', 'La aldea es arrasada en represalia; los hombres fusilados, mujeres y niños deportados.'],
    'https://en.wikipedia.org/wiki/Lidice_massacre'),
  E('stalingrad-1943', 1943, 48.7, 44.52,
    ['Stalingrad', 'Stalingrad', 'Stalingrado'],
    ['Kapitulace 6. armády v únoru 1943; obrat celé války.', 'The Sixth Army surrenders in February 1943; the war’s turning point.', 'El Sexto Ejército capitula en febrero de 1943; el punto de inflexión de la guerra.'],
    'https://en.wikipedia.org/wiki/Battle_of_Stalingrad'),
  E('tehran-1943', 1943, 35.69, 51.42,
    ['Teheránská konference', 'Tehran Conference', 'Conferencia de Teherán'],
    ['Stalin, Roosevelt a Churchill poprvé společně o poválečném světě.', 'Stalin, Roosevelt and Churchill first meet over the postwar world.', 'Stalin, Roosevelt y Churchill se reúnen por primera vez sobre la posguerra.'],
    'https://en.wikipedia.org/wiki/Tehran_Conference'),
  E('dday-1944', 1944, 49.34, -0.6,
    ['Den D — vylodění v Normandii', 'D-Day — Normandy landings', 'Día D: desembarco de Normandía'],
    ['6. června otevřeli Spojenci západní frontu.', 'On 6 June the Allies open the western front.', 'El 6 de junio los Aliados abren el frente occidental.'],
    'https://en.wikipedia.org/wiki/Normandy_landings'),
  E('snp-1944', 1944, 48.74, 19.15,
    ['Slovenské národní povstání', 'Slovak National Uprising', 'Levantamiento Nacional Eslovaco'],
    ['Povstání proti kolaborantskému režimu a německé okupaci.', 'A rising against the collaborationist regime and German occupation.', 'Un alzamiento contra el régimen colaboracionista y la ocupación alemana.'],
    'https://en.wikipedia.org/wiki/Slovak_National_Uprising'),
  E('warsaw-1944', 1944, 52.23, 21.01,
    ['Varšavské povstání', 'Warsaw Uprising', 'Levantamiento de Varsovia'],
    ['63 dní boje; město poté Němci srovnali se zemí.', 'Sixty-three days of fighting; the Germans then raze the city.', 'Sesenta y tres días de lucha; después los alemanes arrasan la ciudad.'],
    'https://en.wikipedia.org/wiki/Warsaw_Uprising'),
  E('yalta-1945', 1945, 44.47, 34.15,
    ['Jaltská konference', 'Yalta Conference', 'Conferencia de Yalta'],
    ['Velká trojka rýsovala poválečnou Evropu — a sféry vlivu.', 'The Big Three sketch postwar Europe — and spheres of influence.', 'Los Tres Grandes trazan la Europa de posguerra y las esferas de influencia.'],
    'https://en.wikipedia.org/wiki/Yalta_Conference'),
  E('prague-uprising-1945', 1945, 50.0873, 14.4213,
    ['Pražské povstání a konec války', 'Prague Uprising and war’s end', 'Levantamiento de Praga y fin de la guerra'],
    ['5.–9. května bojovala Praha na barikádách; 8. května kapitulovalo Německo.', 'Prague fights on the barricades 5–9 May; Germany capitulates on the 8th.', 'Praga lucha en las barricadas del 5 al 9 de mayo; Alemania capitula el día 8.'],
    'https://en.wikipedia.org/wiki/Prague_uprising'),
  E('potsdam-1945', 1945, 52.4, 13.07,
    ['Postupimská konference', 'Potsdam Conference', 'Conferencia de Potsdam'],
    ['Rozdělení Německa a souhlas s odsunem německého obyvatelstva.', 'Germany divided; the transfer of German populations approved.', 'Alemania dividida; se aprueba el traslado de las poblaciones alemanas.'],
    'https://en.wikipedia.org/wiki/Potsdam_Conference'),
  E('hiroshima-1945', 1945, 34.39, 132.45,
    ['Hirošima', 'Hiroshima', 'Hiroshima'],
    ['6. srpna svržena první atomová bomba; o tři dny později Nagasaki.', 'The first atomic bomb falls on 6 August; Nagasaki three days later.', 'La primera bomba atómica cae el 6 de agosto; Nagasaki tres días después.'],
    'https://en.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki'),
  E('fulton-1946', 1946, 38.85, -91.95,
    ['Projev o „železné oponě“', 'The “Iron Curtain” speech', 'El discurso del «telón de acero»'],
    ['Churchill ve Fultonu pojmenoval rozdělení Evropy.', 'Churchill at Fulton names the division of Europe.', 'Churchill en Fulton da nombre a la división de Europa.'],
    'https://en.wikipedia.org/wiki/Iron_Curtain'),
  E('india-1947', 1947, 28.61, 77.21,
    ['Nezávislost Indie', 'Indian independence', 'Independencia de la India'],
    ['Konec britského panství; rozdělení na Indii a Pákistán.', 'The British Raj ends; partition into India and Pakistan.', 'Termina el Raj británico; partición en India y Pakistán.'],
    'https://en.wikipedia.org/wiki/Indian_independence_movement'),
  E('february-1948', 1948, 50.086, 14.42,
    ['Únor 1948', 'February 1948 coup', 'Golpe de febrero de 1948'],
    ['Komunisté převzali moc; čtyři dekády diktatury KSČ.', 'The Communists seize power; four decades of party dictatorship follow.', 'Los comunistas toman el poder; siguen cuatro décadas de dictadura del partido.'],
    'https://en.wikipedia.org/wiki/1948_Czechoslovak_coup_d%27%C3%A9tat'),
  E('israel-1948', 1948, 32.08, 34.78,
    ['Vznik Izraele', 'Founding of Israel', 'Fundación de Israel'],
    ['Vyhlášení státu; hned poté první arabsko-izraelská válka.', 'The state is proclaimed; the first Arab–Israeli war follows at once.', 'Se proclama el estado; de inmediato estalla la primera guerra árabe-israelí.'],
    'https://en.wikipedia.org/wiki/Israeli_Declaration_of_Independence'),
  E('berlin-blockade-1948', 1948, 52.52, 13.4,
    ['Berlínská blokáda', 'Berlin Blockade', 'Bloqueo de Berlín'],
    ['Stalin odřízl západní Berlín; západ ho rok zásoboval letecky.', 'Stalin cuts off West Berlin; the West supplies it by air for a year.', 'Stalin aísla Berlín Oeste; Occidente lo abastece por aire durante un año.'],
    'https://en.wikipedia.org/wiki/Berlin_Blockade'),
  E('nato-1949', 1949, 38.9, -77.04,
    ['Založení NATO', 'NATO founded', 'Fundación de la OTAN'],
    ['Dvanáct zemí podepsalo Severoatlantickou smlouvu.', 'Twelve nations sign the North Atlantic Treaty.', 'Doce países firman el Tratado del Atlántico Norte.'],
    'https://en.wikipedia.org/wiki/NATO'),
  E('prc-1949', 1949, 39.9, 116.4,
    ['Vyhlášení ČLR', 'People’s Republic of China proclaimed', 'Proclamación de la RPC'],
    ['Mao Ce-tung vyhlásil lidovou republiku; Čankajšek ustoupil na Tchaj-wan.', 'Mao proclaims the People’s Republic; Chiang Kai-shek withdraws to Taiwan.', 'Mao proclama la República Popular; Chiang Kai-shek se retira a Taiwán.'],
    'https://en.wikipedia.org/wiki/Proclamation_of_the_People%27s_Republic_of_China'),
  E('korea-1950', 1950, 38.0, 127.0,
    ['Korejská válka', 'Korean War', 'Guerra de Corea'],
    ['Sever napadl Jih; první horký konflikt studené války (1950–53).', 'The North invades the South; the Cold War’s first hot conflict (1950–53).', 'El Norte invade el Sur; el primer conflicto caliente de la Guerra Fría (1950–53).'],
    'https://en.wikipedia.org/wiki/Korean_War'),
  E('horakova-1950', 1950, 50.083, 14.44,
    ['Justiční vražda Milady Horákové', 'Judicial murder of Milada Horáková', 'Asesinato judicial de Milada Horáková'],
    ['Zinscenovaný proces poslal na šibenici demokratickou političku.', 'A show trial sends the democratic politician to the gallows.', 'Un juicio amañado manda a la horca a la política demócrata.'],
    'https://en.wikipedia.org/wiki/Milada_Hor%C3%A1kov%C3%A1'),
  E('stalin-1953', 1953, 55.752, 37.617,
    ['Smrt Stalina', 'Death of Stalin', 'Muerte de Stalin'],
    ['Konec diktátora otevřel cestu k částečnému „tání“.', 'The dictator’s death opens the way to a partial “thaw”.', 'La muerte del dictador abre paso a un «deshielo» parcial.'],
    'https://en.wikipedia.org/wiki/Death_and_state_funeral_of_Joseph_Stalin'),
  E('reforma-1953', 1953, 49.75, 13.38,
    ['Měnová reforma a plzeňské povstání', 'Currency reform and the Plzeň revolt', 'Reforma monetaria y revuelta de Pilsen'],
    ['Reforma připravila lidi o úspory; v Plzni vypuklo dělnické povstání.', 'The reform wipes out savings; a workers’ revolt erupts in Plzeň.', 'La reforma borra los ahorros; en Pilsen estalla una revuelta obrera.'],
    'https://en.wikipedia.org/wiki/1953_Czechoslovak_monetary_reform'),
  E('warsaw-pact-1955', 1955, 52.23, 21.0,
    ['Varšavská smlouva', 'Warsaw Pact', 'Pacto de Varsovia'],
    ['Vojenský blok sovětského tábora jako protiváha NATO.', 'The Soviet bloc’s military alliance, counterweight to NATO.', 'La alianza militar del bloque soviético, contrapeso de la OTAN.'],
    'https://en.wikipedia.org/wiki/Warsaw_Pact'),
  E('hungary-1956', 1956, 47.5, 19.04,
    ['Maďarské povstání', 'Hungarian Revolution', 'Revolución húngara'],
    ['Sovětské tanky utopily povstání v krvi; tisíce mrtvých.', 'Soviet tanks drown the revolution in blood; thousands die.', 'Los tanques soviéticos ahogan la revolución en sangre; miles de muertos.'],
    'https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1956'),
  E('suez-1956', 1956, 30.6, 32.3,
    ['Suezská krize', 'Suez Crisis', 'Crisis de Suez'],
    ['Fiasko Británie a Francie ukázalo konec starých koloniálních velmocí.', 'The Anglo-French fiasco marks the end of the old colonial powers.', 'El fiasco anglo-francés marca el fin de las viejas potencias coloniales.'],
    'https://en.wikipedia.org/wiki/Suez_Crisis'),
  E('sputnik-1957', 1957, 45.92, 63.34,
    ['Sputnik', 'Sputnik', 'Sputnik'],
    ['První umělá družice Země; začíná kosmický věk.', 'The first artificial satellite; the space age begins.', 'El primer satélite artificial; comienza la era espacial.'],
    'https://en.wikipedia.org/wiki/Sputnik_1'),
  E('rome-1957', 1957, 41.9, 12.49,
    ['Římské smlouvy', 'Treaty of Rome', 'Tratados de Roma'],
    ['Šest zemí založilo EHS — zárodek Evropské unie.', 'Six nations found the EEC — the seed of the European Union.', 'Seis países fundan la CEE, el germen de la Unión Europea.'],
    'https://en.wikipedia.org/wiki/Treaty_of_Rome'),
  E('gagarin-1961', 1961, 45.96, 63.3,
    ['Let Jurije Gagarina', 'Yuri Gagarin\'s spaceflight', 'El vuelo de Yuri Gagarin'],
    ['První člověk ve vesmíru odstartoval z Bajkonuru.', 'The first human in space launched from Baikonur.', 'El primer ser humano en el espacio despegó de Baikonur.'],
    'https://en.wikipedia.org/wiki/Yuri_Gagarin'),
  E('berlin-wall-1961', 1961, 52.516, 13.377,
    ['Stavba Berlínské zdi', 'Berlin Wall built', 'Construcción del Muro de Berlín'],
    ['NDR přes noc rozdělila Berlín; symbol železné opony.', 'The GDR divided Berlin overnight; the symbol of the Iron Curtain.', 'La RDA dividió Berlín de la noche a la mañana; símbolo del Telón de Acero.'],
    'https://en.wikipedia.org/wiki/Berlin_Wall'),
  E('cuba-1962', 1962, 23.11, -82.37,
    ['Karibská krize', 'Cuban Missile Crisis', 'Crisis de los misiles de Cuba'],
    ['Sovětské rakety na Kubě přivedly svět na práh jaderné války.', 'Soviet missiles in Cuba brought the world to the brink of nuclear war.', 'Los misiles soviéticos en Cuba llevaron al mundo al borde de la guerra nuclear.'],
    'https://en.wikipedia.org/wiki/Cuban_Missile_Crisis'),
  E('jfk-1963', 1963, 32.78, -96.8,
    ['Atentát na J. F. Kennedyho', 'Assassination of John F. Kennedy', 'Asesinato de John F. Kennedy'],
    ['Americký prezident byl zastřelen v Dallasu.', 'The US president was shot in Dallas.', 'El presidente estadounidense fue asesinado en Dallas.'],
    'https://en.wikipedia.org/wiki/Assassination_of_John_F._Kennedy'),
  E('vietnam-1965', 1965, 16.07, 108.22,
    ['Eskalace války ve Vietnamu', 'Vietnam War escalation', 'Escalada de la guerra de Vietnam'],
    ['U Da Nangu se vylodily první americké bojové jednotky.', 'The first US combat troops landed at Da Nang.', 'Las primeras tropas de combate estadounidenses desembarcaron en Da Nang.'],
    'https://en.wikipedia.org/wiki/Vietnam_War'),
  E('prague-spring-1968', 1968, 50.088, 14.421,
    ['Pražské jaro a srpnová invaze', 'Prague Spring and the August invasion', 'La Primavera de Praga y la invasión de agosto'],
    ['Pokus o „socialismus s lidskou tváří" ukončila 21. srpna invaze vojsk Varšavské smlouvy.', 'The attempt at "socialism with a human face" was crushed by the Warsaw Pact invasion of 21 August.', 'El intento de un «socialismo con rostro humano» fue aplastado por la invasión del Pacto de Varsovia el 21 de agosto.'],
    'https://en.wikipedia.org/wiki/Prague_Spring'),
  E('palach-1969', 1969, 50.079, 14.43,
    ['Jan Palach', 'Jan Palach', 'Jan Palach'],
    ['Student se upálil na Václavském náměstí na protest proti okupaci.', 'A student burned himself to death in Wenceslas Square in protest against the occupation.', 'Un estudiante se inmoló en la plaza de Wenceslao en protesta contra la ocupación.'],
    'https://en.wikipedia.org/wiki/Jan_Palach'),
  E('moon-1969', 1969, 28.6, -80.6,
    ['Přistání na Měsíci', 'Moon landing', 'Llegada a la Luna'],
    ['Apollo 11 odstartovalo z Floridy; Armstrong a Aldrin stanuli na Měsíci.', 'Apollo 11 launched from Florida; Armstrong and Aldrin walked on the Moon.', 'El Apolo 11 despegó de Florida; Armstrong y Aldrin pisaron la Luna.'],
    'https://en.wikipedia.org/wiki/Apollo_11'),
  E('helsinki-1975', 1975, 60.17, 24.94,
    ['Helsinský závěrečný akt', 'Helsinki Accords', 'Acuerdos de Helsinki'],
    ['35 států uznalo lidská práva jako mezinárodní závazek; opora pozdějšího disentu.', '35 states recognized human rights as an international commitment; a foothold for later dissent.', '35 estados reconocieron los derechos humanos como compromiso internacional; apoyo para la disidencia posterior.'],
    'https://en.wikipedia.org/wiki/Helsinki_Accords'),
  E('charta-1977', 1977, 50.084, 14.418,
    ['Charta 77', 'Charter 77', 'Carta 77'],
    ['Českoslovenští občané v čele s Havlem žádali dodržování lidských práv.', 'Czechoslovak citizens led by Havel demanded respect for human rights.', 'Ciudadanos checoslovacos encabezados por Havel exigieron el respeto de los derechos humanos.'],
    'https://en.wikipedia.org/wiki/Charter_77'),
  E('solidarity-1980', 1980, 54.37, 18.65,
    ['Solidarita v Gdaňsku', 'Solidarity founded in Gdańsk', 'Solidaridad en Gdańsk'],
    ['V loděnicích vznikl první nezávislý odborový svaz sovětského bloku.', 'The Soviet bloc\'s first independent trade union was born in the shipyards.', 'En los astilleros nació el primer sindicato independiente del bloque soviético.'],
    'https://en.wikipedia.org/wiki/Solidarity_(Polish_trade_union)'),
  E('gorbachev-1985', 1985, 55.755, 37.62,
    ['Gorbačov: perestrojka', 'Gorbachev: perestroika', 'Gorbachov: la perestroika'],
    ['Nový sovětský vůdce zahájil reformy perestrojku a glasnosť.', 'The new Soviet leader launched the perestroika and glasnost reforms.', 'El nuevo líder soviético lanzó las reformas de la perestroika y la glásnost.'],
    'https://en.wikipedia.org/wiki/Mikhail_Gorbachev'),
  E('chernobyl-1986', 1986, 51.39, 30.1,
    ['Havárie v Černobylu', 'Chernobyl disaster', 'Catástrofe de Chernóbil'],
    ['Výbuch reaktoru způsobil nejhorší jadernou havárii v dějinách.', 'A reactor explosion caused the worst nuclear accident in history.', 'La explosión de un reactor causó el peor accidente nuclear de la historia.'],
    'https://en.wikipedia.org/wiki/Chernobyl_disaster'),
  E('velvet-1989', 1989, 50.081, 14.425,
    ['Sametová revoluce', 'Velvet Revolution', 'Revolución de Terciopelo'],
    ['Po 17. listopadu padl komunistický režim v Československu bez krveprolití.', 'After 17 November, the communist regime in Czechoslovakia fell without bloodshed.', 'Tras el 17 de noviembre, el régimen comunista de Checoslovaquia cayó sin derramamiento de sangre.'],
    'https://en.wikipedia.org/wiki/Velvet_Revolution'),
  E('wall-falls-1989', 1989, 52.516, 13.38,
    ['Pád Berlínské zdi', 'Fall of the Berlin Wall', 'Caída del Muro de Berlín'],
    ['9. listopadu se otevřely hranice NDR; konec rozdělené Evropy začal.', 'On 9 November the GDR borders opened; the end of a divided Europe began.', 'El 9 de noviembre se abrieron las fronteras de la RDA; comenzó el fin de la Europa dividida.'],
    'https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall'),
  E('ussr-end-1991', 1991, 55.75, 37.61,
    ['Rozpad Sovětského svazu', 'Dissolution of the Soviet Union', 'Disolución de la Unión Soviética'],
    ['SSSR zanikl; vzniklo 15 nástupnických států.', 'The USSR ceased to exist; 15 successor states emerged.', 'La URSS dejó de existir; surgieron 15 estados sucesores.'],
    'https://en.wikipedia.org/wiki/Dissolution_of_the_Soviet_Union'),
  E('yugoslavia-1991', 1991, 45.35, 19.0,
    ['Války v Jugoslávii', 'Yugoslav Wars', 'Guerras yugoslavas'],
    ['Rozpad Jugoslávie přerostl ve válku; Vukovar byl prvním obleženým městem.', 'Yugoslavia\'s breakup turned to war; Vukovar was the first besieged city.', 'La desintegración de Yugoslavia derivó en guerra; Vukovar fue la primera ciudad sitiada.'],
    'https://en.wikipedia.org/wiki/Yugoslav_Wars'),
  E('maastricht-1992', 1992, 50.85, 5.69,
    ['Maastrichtská smlouva', 'Maastricht Treaty', 'Tratado de Maastricht'],
    ['Z EHS se stala Evropská unie; dohodnuta společná měna.', 'The EEC became the European Union; a common currency was agreed.', 'La CEE se convirtió en la Unión Europea; se acordó una moneda común.'],
    'https://en.wikipedia.org/wiki/Maastricht_Treaty'),
  E('czech-1993', 1993, 50.087, 14.42,
    ['Vznik České republiky', 'Foundation of the Czech Republic', 'Fundación de la República Checa'],
    ['Československo se 1. ledna pokojně rozdělilo na Česko a Slovensko.', 'Czechoslovakia peacefully split into the Czech Republic and Slovakia on 1 January.', 'Checoslovaquia se dividió pacíficamente en Chequia y Eslovaquia el 1 de enero.'],
    'https://en.wikipedia.org/wiki/Dissolution_of_Czechoslovakia'),
  E('nato-1999', 1999, 50.09, 14.424,
    ['ČR vstoupila do NATO', 'Czech Republic joins NATO', 'Chequia entra en la OTAN'],
    ['Česko, Polsko a Maďarsko se staly prvními postkomunistickými členy NATO.', 'The Czech Republic, Poland and Hungary became NATO\'s first post-communist members.', 'Chequia, Polonia y Hungría fueron los primeros miembros poscomunistas de la OTAN.'],
    'https://en.wikipedia.org/wiki/Enlargement_of_NATO'),
  E('sept11-2001', 2001, 40.71, -74.01,
    ['Útoky 11. září', 'September 11 attacks', 'Atentados del 11 de septiembre'],
    ['Teroristické útoky v USA zabily téměř 3 000 lidí a zahájily „válku proti terorismu".', 'Terrorist attacks in the US killed nearly 3,000 people and launched the "war on terror".', 'Los atentados terroristas en EE. UU. mataron a casi 3000 personas e iniciaron la «guerra contra el terrorismo».'],
    'https://en.wikipedia.org/wiki/September_11_attacks'),
  E('eu-2004', 2004, 50.086, 14.426,
    ['ČR vstoupila do EU', 'Czech Republic joins the EU', 'Chequia entra en la UE'],
    ['1. května se EU rozšířila o deset zemí včetně Česka.', 'On 1 May the EU expanded by ten countries, including the Czech Republic.', 'El 1 de mayo la UE se amplió con diez países, incluida Chequia.'],
    'https://en.wikipedia.org/wiki/2004_enlargement_of_the_European_Union'),
];
