import type { Fact } from './facts';

/**
 * The curated "interesting facts" list.
 *
 * Provenance: drafted with Gemini, then reviewed by hand — eight factual
 * errors were corrected against reference sources (see the repository history)
 * and legend-shaped claims are phrased as legends. Every entry links a
 * checkable reference. Years follow one rule: a fact appears on the FIRST
 * snapshot at or after its anchor date, never earlier, so nothing shows on a
 * map that predates it; the real date is stated in the text itself.
 */
export const FACTS: Fact[] = [
  {
    id: 'hypogeum-hal-saflieni',
    years: [-4000],
    territory: 'Ħal Saflieni',
    text: {
      cs: 'Malta: Podzemní megalitický chrám z doby kolem 4000 př. n. l., vysekaný do skály, ukrýval tisíce lidských koster a má komoru, která silně rezonuje v hloubce mužského hlasu.',
      en: 'Malta: An underground megalithic sanctuary from around 4000 BC, cut into the rock, held thousands of human skeletons and has a chamber that resonates strongly at the pitch of a male voice.',
      es: 'Malta: Un santuario megalítico subterráneo de hacia 4000 a. C., excavado en la roca, guardaba miles de esqueletos humanos y tiene una cámara que resuena con fuerza en el tono de una voz masculina.',
    },
    source: { label: 'Wikipedia: Hypogeum of Ħal Saflieni', url: 'https://en.wikipedia.org/wiki/Hypogeum_of_%C4%A6al_Saflieni' },
  },
  {
    id: 'skara-brae',
    years: [-3000],
    territory: 'Skara Brae',
    text: {
      cs: 'Skotsko (Orkneje): Kamenná neolitická vesnice obývaná kolem 3180 př. n. l. — starší než pyramidy v Gíze — se po tisíciletí dochovala takřka netknutá pod písečnou dunou.',
      en: 'Scotland (Orkney): A stone Neolithic village inhabited around 3180 BC — older than the pyramids of Giza — survived almost intact for millennia under a sand dune.',
      es: 'Escocia (Orcadas): Una aldea neolítica de piedra habitada hacia 3180 a. C. —más antigua que las pirámides de Guiza— sobrevivió casi intacta durante milenios bajo una duna de arena.',
    },
    source: { label: 'Wikipedia: Skara Brae', url: 'https://en.wikipedia.org/wiki/Skara_Brae' },
  },
  {
    id: 'meroe-pyramids',
    years: [-300],
    territory: 'Meroe',
    text: {
      cs: 'Súdán: Vládci království Kúš postavili u Meroe (rozkvět zhruba od 3. století př. n. l.) přes 200 pyramid — víc, než kolik jich stojí v Egyptě, a se strmějšími stěnami.',
      en: 'Sudan: The rulers of the Kingdom of Kush built over 200 pyramids at Meroe (flourishing from roughly the 3rd century BC) — more than stand in Egypt, and with steeper sides.',
      es: 'Sudán: Los gobernantes del reino de Kush levantaron en Meroe (en auge desde el siglo III a. C., aproximadamente) más de 200 pirámides: más de las que hay en Egipto, y con lados más empinados.',
    },
    source: { label: 'Wikipedia: Nubian pyramids', url: 'https://en.wikipedia.org/wiki/Nubian_pyramids' },
  },
  {
    id: 'babylon',
    years: [-1500],
    territory: 'Babylón',
    text: {
      cs: 'Irák: Babylón, velmoc už za Chammurapiho (od r. 1792 př. n. l.), je spojen s příběhy o visutých zahradách i babylonské věži. Ve 20. století si Saddám Husajn nechal postavit palác s výhledem přímo na jeho ruiny.',
      en: 'Iraq: Babylon, a great power from Hammurabi onward (from 1792 BC), is tied to the stories of the Hanging Gardens and the Tower of Babel. In the 20th century Saddam Hussein had a palace built overlooking its ruins.',
      es: 'Irak: Babilonia, gran potencia desde Hammurabi (desde 1792 a. C.), está ligada a las historias de los Jardines Colgantes y la Torre de Babel. En el siglo XX, Sadam Huseín se hizo construir un palacio con vistas a sus ruinas.',
    },
    source: { label: 'Wikipedia: Babylon', url: 'https://en.wikipedia.org/wiki/Babylon' },
  },
  {
    id: 'kaali-crater',
    years: [-1500],
    territory: 'Kaali',
    text: {
      cs: 'Estonsko: Dopad meteoritu na ostrově Saaremaa v době bronzové (odhady kolem 1500 př. n. l.) vytvořil kráter, který dlouho sloužil jako posvátné místo a otiskl se do severského folklóru.',
      en: 'Estonia: A Bronze Age meteorite impact on Saaremaa (estimates around 1500 BC) left a crater that long served as a sacred site and left its mark on Nordic folklore.',
      es: 'Estonia: El impacto de un meteorito en Saaremaa en la Edad del Bronce (estimado hacia 1500 a. C.) dejó un cráter que sirvió largo tiempo como lugar sagrado y marcó el folclore nórdico.',
    },
    source: { label: 'Wikipedia: Kaali crater', url: 'https://en.wikipedia.org/wiki/Kaali_crater' },
  },
  {
    id: 'tutankhamun-tomb',
    years: [-1000],
    territory: 'Údolí králů',
    text: {
      cs: 'Egypt: Faraon Tutanchamon byl pohřben roku 1323 př. n. l.; otevření jeho takřka nedotčené hrobky v roce 1922 dalo vzniknout novinářskému mýtu o „kletbě faraonů“.',
      en: 'Egypt: Pharaoh Tutankhamun was buried in 1323 BC; the opening of his nearly intact tomb in 1922 gave rise to the newspaper myth of the “curse of the pharaohs”.',
      es: 'Egipto: El faraón Tutankamón fue enterrado en 1323 a. C.; la apertura de su tumba casi intacta en 1922 dio origen al mito periodístico de la «maldición de los faraones».',
    },
    source: { label: 'Wikipedia: Tutankhamun', url: 'https://en.wikipedia.org/wiki/Tutankhamun' },
  },
  {
    id: 'nazca-lines',
    years: [-500],
    territory: 'Nazca',
    text: {
      cs: 'Peru: Zhruba od 500 př. n. l. vznikaly na pouštní planině stovky obřích geoglyfů, jejichž tvary jsou v celku rozpoznatelné až z výšky.',
      en: 'Peru: From roughly 500 BC, hundreds of giant geoglyphs were etched into the desert plain — their shapes only legible as wholes from the air.',
      es: 'Perú: Desde aproximadamente 500 a. C. se trazaron en la llanura desértica cientos de geoglifos gigantes, cuyas formas solo se aprecian completas desde el aire.',
    },
    source: { label: 'Wikipedia: Nazca lines', url: 'https://en.wikipedia.org/wiki/Nazca_lines' },
  },
  {
    id: 'dead-sea',
    years: [-323],
    territory: 'Mrtvé moře',
    text: {
      cs: 'Jordánsko/Izrael: Nejníže položené odkryté místo na Zemi (dnes kolem −430 m). Vodu zhruba desetkrát slanější než oceán, která nadnáší tělo a nedává ryby, popisovali s údivem už antičtí autoři.',
      en: 'Jordan/Israel: The lowest exposed place on Earth (today around −430 m). Water roughly ten times saltier than the ocean, which floats the body and holds no fish, was already described with wonder by ancient authors.',
      es: 'Jordania/Israel: El lugar emergido más bajo de la Tierra (hoy en torno a −430 m). Un agua unas diez veces más salada que el océano, que hace flotar el cuerpo y no admite peces, ya asombraba a los autores antiguos.',
    },
    source: { label: 'Wikipedia: Dead Sea', url: 'https://en.wikipedia.org/wiki/Dead_Sea' },
  },
  {
    id: 'terracotta-army',
    years: [-200],
    territory: 'Si-an',
    text: {
      cs: 'Čína: Hrobku prvního císaře Čchin Š’-chuang-tiho (zemřel 210 př. n. l.) střeží terakotová armáda. Hlavní pohřební komora zůstává neotevřena — i kvůli starověkému popisu řek z tekuté rtuti, jemuž nasvědčují měření rtuti v půdě.',
      en: 'China: The tomb of the First Emperor, Qin Shi Huang (died 210 BC), is guarded by the Terracotta Army. The central burial chamber remains unopened — partly because of the ancient account of rivers of liquid mercury, supported by soil mercury readings.',
      es: 'China: La tumba del Primer Emperador, Qin Shi Huang (muerto en 210 a. C.), está custodiada por el Ejército de Terracota. La cámara funeraria central sigue sin abrirse, en parte por el relato antiguo de ríos de mercurio líquido, avalado por mediciones de mercurio en el suelo.',
    },
    source: { label: 'Wikipedia: Terracotta Army', url: 'https://en.wikipedia.org/wiki/Terracotta_Army' },
  },
  {
    id: 'hegra',
    years: [100],
    territory: 'Hegra',
    text: {
      cs: 'Saúdská Arábie: Nabatejci vytesali kolem přelomu letopočtu do pískovcových bloků uprostřed pouště přes sto monumentálních skalních hrobek — jižní sestru slavnější Petry.',
      en: 'Saudi Arabia: Around the turn of the era the Nabataeans carved over a hundred monumental rock tombs into sandstone outcrops in the desert — the southern sister of the more famous Petra.',
      es: 'Arabia Saudita: Hacia el cambio de era, los nabateos tallaron más de cien tumbas monumentales en los bloques de arenisca del desierto: la hermana meridional de la célebre Petra.',
    },
    source: { label: 'Wikipedia: Hegra (Mada’in Salih)', url: 'https://en.wikipedia.org/wiki/Hegra_(Mada%27in_Salih)' },
  },
  {
    id: 'derinkuyu',
    years: [300],
    territory: 'Derinkuyu',
    text: {
      cs: 'Turecko: Podzemní město v kappadockém tufu, prohlubované po staletí, dokázalo při nájezdech ukrýt podle odhadů až 20 000 lidí i s dobytkem.',
      en: 'Turkey: An underground city in the Cappadocian tuff, deepened over centuries, could by some estimates shelter up to 20,000 people — livestock included — during raids.',
      es: 'Turquía: Una ciudad subterránea en la toba de Capadocia, ahondada durante siglos, pudo albergar según estimaciones hasta 20 000 personas, ganado incluido, durante las incursiones.',
    },
    source: { label: 'Wikipedia: Derinkuyu underground city', url: 'https://en.wikipedia.org/wiki/Derinkuyu_underground_city' },
  },
  {
    id: 'diquis-spheres',
    years: [300],
    territory: 'Diquís',
    text: {
      cs: 'Kostarika: Předkolumbovské kultury vyráběly zhruba od 3. století stovky téměř dokonale kulových kamenných koulí; jejich účel není znám.',
      en: 'Costa Rica: From roughly the 3rd century, pre-Columbian cultures produced hundreds of nearly perfect stone spheres; their purpose is unknown.',
      es: 'Costa Rica: Desde el siglo III aproximadamente, las culturas precolombinas produjeron cientos de esferas de piedra casi perfectas; su propósito se desconoce.',
    },
    source: { label: 'Wikipedia: Stone spheres of Costa Rica', url: 'https://en.wikipedia.org/wiki/Stone_spheres_of_Costa_Rica' },
  },
  {
    id: 'sigiriya',
    years: [500],
    territory: 'Sigiriya',
    text: {
      cs: 'Srí Lanka: Na vrcholu „Lví skály“, monolitu čnícího z džungle, si nechal král Kasjapa (od r. 477) postavit palác, k němuž se stoupalo branou v podobě obří lví tlamy.',
      en: 'Sri Lanka: On top of the “Lion Rock”, a monolith rising from the jungle, King Kashyapa (from 477) built a palace reached through a gateway shaped as a giant lion’s mouth.',
      es: 'Sri Lanka: En la cima de la «Roca del León», un monolito que emerge de la selva, el rey Kashyapa (desde 477) construyó un palacio al que se accedía por una puerta con forma de bocaza de león.',
    },
    source: { label: 'Wikipedia: Sigiriya', url: 'https://en.wikipedia.org/wiki/Sigiriya' },
  },
  {
    id: 'skellig-michael',
    years: [600],
    territory: 'Skellig Michael',
    text: {
      cs: 'Irsko: Na skalnatém ostrově v Atlantiku žili zhruba od 6.–8. století mniši v naprosté izolaci, v kamenných chýších tvaru včelích úlů.',
      en: 'Ireland: On a rocky Atlantic island, monks lived in complete isolation from roughly the 6th–8th century, in stone huts shaped like beehives.',
      es: 'Irlanda: En una isla rocosa del Atlántico, monjes vivieron en completo aislamiento desde los siglos VI–VIII aproximadamente, en cabañas de piedra con forma de colmena.',
    },
    source: { label: 'Wikipedia: Skellig Michael', url: 'https://en.wikipedia.org/wiki/Skellig_Michael' },
  },
  {
    id: 'roopkund',
    years: [800],
    territory: 'Roopkund',
    text: {
      cs: 'Indie: V ledovcovém jezeře vysoko v Himálaji leží stovky koster. Nejstarší patří skupině z 9. století, která podle jedné studie zahynula při prudkém krupobití; novější DNA výzkum ale našel i ostatky o staletí mladší, takže záhada trvá.',
      en: 'India: A glacial lake high in the Himalayas holds hundreds of skeletons. The oldest belong to a 9th-century group that one study says died in a violent hailstorm; newer DNA work also found remains centuries younger, so the mystery stands.',
      es: 'India: Un lago glaciar en lo alto del Himalaya guarda cientos de esqueletos. Los más antiguos pertenecen a un grupo del siglo IX que, según un estudio, murió por una granizada violenta; análisis de ADN más recientes hallaron también restos siglos más jóvenes, así que el misterio continúa.',
    },
    source: { label: 'Wikipedia: Roopkund', url: 'https://en.wikipedia.org/wiki/Roopkund' },
  },
  {
    id: 'lanse-aux-meadows',
    years: [1000],
    territory: 'L’Anse aux Meadows',
    text: {
      cs: 'Kanada: Kolem roku 1000 tu Vikingové založili první prokázané evropské osídlení v Severní Americe — pět století před plavbou Kryštofa Kolumba.',
      en: 'Canada: Around the year 1000, Norse settlers founded the first proven European settlement in North America — five centuries before Columbus sailed.',
      es: 'Canadá: Hacia el año 1000, colonos nórdicos fundaron aquí el primer asentamiento europeo probado de América del Norte, cinco siglos antes del viaje de Colón.',
    },
    source: { label: 'Wikipedia: L’Anse aux Meadows', url: 'https://en.wikipedia.org/wiki/L%27Anse_aux_Meadows' },
  },
  {
    id: 'fez-tanneries',
    years: [1100],
    territory: 'Fez',
    text: {
      cs: 'Maroko: Koželužny Chouara podle tradice pracují od 11. století dodnes; kůže se v kamenných kádích stále ručně barví za pomoci holubího trusu a dalších tradičních přísad.',
      en: 'Morocco: The Chouara tanneries have by tradition worked since the 11th century; hides are still hand-dyed in stone vats using pigeon droppings and other traditional ingredients.',
      es: 'Marruecos: Las curtidurías de Chouara funcionan, según la tradición, desde el siglo XI; las pieles se tiñen aún a mano en tinas de piedra con excremento de paloma y otros ingredientes tradicionales.',
    },
    source: { label: 'Wikipedie — hledat: Chouara Tannery', url: 'https://en.wikipedia.org/w/index.php?search=Chouara%20Tannery' },
  },
  {
    id: 'alamut',
    years: [1100],
    territory: 'Alamút',
    text: {
      cs: 'Írán: Horskou pevnost Alamút ovládl roku 1090 Hasan-i Sabbáh a udělal z ní základnu nizáríů — obávané sekty, z jejíhož jména vzniklo slovo „asasín“.',
      en: 'Iran: In 1090 Hassan-i Sabbah seized the mountain fortress of Alamut and made it the base of the Nizaris — the feared sect whose name gave us the word “assassin”.',
      es: 'Irán: En 1090, Hasan-i Sabbah tomó la fortaleza montañosa de Alamut y la convirtió en la base de los nizaríes, la temida secta cuyo nombre dio origen a la palabra «asesino».',
    },
    source: { label: 'Wikipedia: Alamut Castle', url: 'https://en.wikipedia.org/wiki/Alamut_Castle' },
  },
  {
    id: 'meteora',
    years: [1100],
    territory: 'Meteora',
    text: {
      cs: 'Řecko: Na vrcholcích gigantických skalních věží žili od 11. století poustevníci a později vyrostly celé kláštery; lidé i zásoby se nahoru dlouho vytahovali jen v sítích na provazech.',
      en: 'Greece: Hermits lived atop gigantic rock pillars from the 11th century, and whole monasteries later grew there; for ages, people and supplies went up only in rope-hauled nets.',
      es: 'Grecia: Desde el siglo XI vivieron ermitaños en lo alto de gigantescas torres de roca, donde luego crecieron monasterios enteros; durante mucho tiempo, personas y provisiones subían solo en redes izadas con cuerdas.',
    },
    source: { label: 'Wikipedia: Meteora', url: 'https://en.wikipedia.org/wiki/Meteora' },
  },
  {
    id: 'vardzia',
    years: [1200],
    territory: 'Vardzia',
    text: {
      cs: 'Gruzie: Královna Tamar nechala od roku 1185 vytesat do stěny hory obří skalní klášterní město o třinácti podlažích, úkryt před nájezdy z východu.',
      en: 'Georgia: From 1185, Queen Tamar had a giant thirteen-storey monastery town carved into a mountainside as a refuge from invasions from the east.',
      es: 'Georgia: Desde 1185, la reina Tamar hizo excavar en la ladera de una montaña una gigantesca ciudad monástica de trece niveles, refugio frente a las invasiones del este.',
    },
    source: { label: 'Wikipedia: Vardzia', url: 'https://en.wikipedia.org/wiki/Vardzia' },
  },
  {
    id: 'ta-prohm',
    years: [1200],
    territory: 'Ta Prohm',
    text: {
      cs: 'Kambodža: Chrám z roku 1186 v Angkoru byl při obnově záměrně ponechán v objetí džungle — jeho zdi dodnes prorůstají obří kořeny stromů.',
      en: 'Cambodia: This Angkor temple from 1186 was deliberately left in the jungle’s embrace during restoration — giant tree roots still grow through its walls.',
      es: 'Camboya: Este templo de Angkor, de 1186, se dejó deliberadamente abrazado por la selva durante la restauración: enormes raíces de árboles siguen atravesando sus muros.',
    },
    source: { label: 'Wikipedia: Ta Prohm', url: 'https://en.wikipedia.org/wiki/Ta_Prohm' },
  },
  {
    id: 'geghard',
    years: [1279],
    territory: 'Geghard',
    text: {
      cs: 'Arménie: Klášter z velké části vysekaný přímo do hory (hlavní kaple 1215) po staletí přechovával kopí, jímž měl být podle tradice proboden Ježíš.',
      en: 'Armenia: A monastery largely hewn straight into the mountain (main chapel 1215) kept for centuries the spear said by tradition to have pierced Jesus.',
      es: 'Armenia: Un monasterio en gran parte excavado en la montaña (capilla principal de 1215) custodió durante siglos la lanza que, según la tradición, atravesó a Jesús.',
    },
    source: { label: 'Wikipedia: Geghard', url: 'https://en.wikipedia.org/wiki/Geghard' },
  },
  {
    id: 'lalibela',
    years: [1279],
    territory: 'Lalibela',
    text: {
      cs: 'Etiopie: Za krále Lalibely (kolem r. 1200) byly do červené sopečné horniny vytesány monolitické kostely — celé shora dolů, z jednoho kusu skály.',
      en: 'Ethiopia: Under King Lalibela (around 1200), monolithic churches were carved into red volcanic rock — top-down, each from a single piece of stone.',
      es: 'Etiopía: Bajo el rey Lalibela (hacia 1200) se tallaron iglesias monolíticas en la roca volcánica roja, de arriba abajo, cada una de una sola pieza.',
    },
    source: { label: 'Wikipedia: Lalibela', url: 'https://en.wikipedia.org/wiki/Lalibela' },
  },
  {
    id: 'teufelsbruecke',
    years: [1279],
    territory: 'Schöllenen',
    text: {
      cs: 'Švýcarsko: K mostu přes divokou soutěsku Schöllenen (od 13. století) se váže pověst o paktu s ďáblem: postaví most výměnou za duši prvního, kdo po něm přejde — místní na něj poslali kozla.',
      en: 'Switzerland: The bridge over the wild Schöllenen gorge (13th century onward) carries the legend of a pact with the devil: he builds the bridge in exchange for the soul of the first to cross — the locals sent a goat.',
      es: 'Suiza: Al puente sobre la salvaje garganta de Schöllenen (desde el siglo XIII) lo acompaña la leyenda de un pacto con el diablo: él construye el puente a cambio del alma del primero en cruzarlo, y los lugareños enviaron una cabra.',
    },
    source: { label: 'Wikipedie — hledat: Teufelsbrücke Schöllenen', url: 'https://en.wikipedia.org/w/index.php?search=Sch%C3%B6llenen%20Gorge%20Devil%27s%20Bridge' },
  },
  {
    id: 'rapa-nui-moai',
    years: [1279],
    territory: 'Rapa Nui',
    text: {
      cs: 'Chile (Velikonoční ostrov): Zhruba od 13. století vztyčovali obyvatelé Rapa Nui stovky soch moai — monumentální kamenné předky s obřími hlavami.',
      en: 'Chile (Easter Island): From roughly the 13th century, the people of Rapa Nui raised hundreds of moai — monumental stone ancestors with enormous heads.',
      es: 'Chile (Isla de Pascua): Desde el siglo XIII aproximadamente, los habitantes de Rapa Nui erigieron cientos de moáis: ancestros monumentales de piedra con cabezas enormes.',
    },
    source: { label: 'Wikipedia: Moai', url: 'https://en.wikipedia.org/wiki/Moai' },
  },
  {
    id: 'houska-castle',
    years: [1300],
    territory: 'Houska',
    text: {
      cs: 'Česko: Hrad z konce 13. století nestojí na žádné obchodní cestě ani hranici; podle pověsti byl postaven nad skalní průrvou považovanou za „bránu do pekla“, aby ji zavřel.',
      en: 'Czechia: This late-13th-century castle guards no trade route or border; legend has it built over a rock chasm held to be a “gateway to hell”, to keep it shut.',
      es: 'Chequia: Este castillo de finales del siglo XIII no protege ninguna ruta ni frontera; según la leyenda, se construyó sobre una grieta considerada una «puerta al infierno», para mantenerla cerrada.',
    },
    source: { label: 'Wikipedia: Houska Castle', url: 'https://en.wikipedia.org/wiki/Houska_Castle' },
  },
  {
    id: 'djenne-mosque',
    years: [1300],
    territory: 'Djenné',
    text: {
      cs: 'Mali: Velká mešita v Djenné (poprvé kolem 13. století, dnešní podoba 1907) je největší stavbou z nepálených hliněných cihel na světě; obyvatelé ji každý rok při slavnosti společně omítají čerstvým bahnem.',
      en: 'Mali: The Great Mosque of Djenné (first built around the 13th century, present form 1907) is the world’s largest mud-brick building; every year the townspeople replaster it together with fresh mud at a festival.',
      es: 'Malí: La Gran Mezquita de Djenné (levantada por primera vez hacia el siglo XIII, forma actual de 1907) es el mayor edificio de adobe del mundo; cada año, sus habitantes la revocan juntos con barro fresco en una fiesta.',
    },
    source: { label: 'Wikipedia: Great Mosque of Djenné', url: 'https://en.wikipedia.org/wiki/Great_Mosque_of_Djenn%C3%A9' },
  },
  {
    id: 'poveglia',
    years: [1400],
    territory: 'Poveglia',
    text: {
      cs: 'Itálie: Ostrůvek u Benátek sloužil od morových ran (velká epidemie 1348 a další) jako karanténní stanice a masové pohřebiště; pověsti o pozdější psychiatrické léčebně z něj udělaly „nejstrašidelnější ostrov Itálie“.',
      en: 'Italy: This islet off Venice served from the plague years (the great epidemic of 1348 and later ones) as a quarantine station and mass burial ground; tales of a later mental asylum made it “Italy’s most haunted island”.',
      es: 'Italia: Este islote frente a Venecia sirvió desde las pestes (la gran epidemia de 1348 y otras) como estación de cuarentena y fosa común; los relatos sobre un manicomio posterior lo convirtieron en «la isla más embrujada de Italia».',
    },
    source: { label: 'Wikipedia: Poveglia', url: 'https://en.wikipedia.org/wiki/Poveglia' },
  },
  {
    id: 'nan-madol',
    years: [1400],
    territory: 'Nan Madol',
    text: {
      cs: 'Mikronésie: Na 92 umělých ostrůvcích propojených kanály vyrostlo z masivních čedičových sloupů kamenné město, sídlo dynastie Sau Deleur (rozkvět kolem 13.–15. století).',
      en: 'Micronesia: On 92 artificial islets linked by canals, a stone city of massive basalt columns rose as the seat of the Saudeleur dynasty (flourishing around the 13th–15th centuries).',
      es: 'Micronesia: Sobre 92 islotes artificiales unidos por canales se alzó una ciudad de piedra hecha de columnas masivas de basalto, sede de la dinastía Saudeleur (auge hacia los siglos XIII–XV).',
    },
    source: { label: 'Wikipedia: Nan Madol', url: 'https://en.wikipedia.org/wiki/Nan_Madol' },
  },
  {
    id: 'ter-apel',
    years: [1492],
    territory: 'Ter Apel',
    text: {
      cs: 'Nizozemsko: Klášter založený roku 1465, jediný venkovský klášter v zemi, který přežil reformaci; vážou se k němu pověsti o bílých paních a tajných podzemních chodbách.',
      en: 'Netherlands: A monastery founded in 1465, the only rural monastery in the country to survive the Reformation; legends of white ladies and secret underground passages cling to it.',
      es: 'Países Bajos: Un monasterio fundado en 1465, el único rural del país que sobrevivió a la Reforma; lo rodean leyendas de damas blancas y pasadizos subterráneos secretos.',
    },
    source: { label: 'Wikipedie — hledat: Ter Apel monastery', url: 'https://en.wikipedia.org/w/index.php?search=Ter%20Apel%20monastery' },
  },
  {
    id: 'machu-picchu',
    years: [1492],
    territory: 'Machu Picchu',
    text: {
      cs: 'Peru: Horské město Inků postavené kolem roku 1450 španělští dobyvatelé nikdy nenašli; světu je v roce 1911 představil Hiram Bingham.',
      en: 'Peru: The Inca mountain city built around 1450 was never found by the Spanish conquistadors; Hiram Bingham brought it to the world’s attention in 1911.',
      es: 'Perú: La ciudad inca de montaña construida hacia 1450 nunca fue hallada por los conquistadores españoles; Hiram Bingham la dio a conocer al mundo en 1911.',
    },
    source: { label: 'Wikipedia: Machu Picchu', url: 'https://en.wikipedia.org/wiki/Machu_Picchu' },
  },
  {
    id: 'buda-labyrinth',
    years: [1492],
    territory: 'Budín',
    text: {
      cs: 'Maďarsko: V jeskynním labyrintu pod Budínským hradem měl podle tradice uherský král Matyáš Korvín po roce 1462 věznit Vlada III. Napichovače — předobraz Drákuly.',
      en: 'Hungary: In the cave labyrinth under Buda Castle, tradition holds that King Matthias Corvinus imprisoned Vlad III the Impaler — the model for Dracula — after 1462.',
      es: 'Hungría: En el laberinto de cuevas bajo el castillo de Buda, la tradición dice que el rey Matías Corvino encarceló después de 1462 a Vlad III el Empalador, el modelo de Drácula.',
    },
    source: { label: 'Wikipedia: Vlad the Impaler', url: 'https://en.wikipedia.org/wiki/Vlad_the_Impaler' },
  },
  {
    id: 'snagov',
    years: [1492],
    territory: 'Snagov',
    text: {
      cs: 'Rumunsko: V klášteře na jezerním ostrově má podle tradice ležet tělo Vlada Napichovače (zemřel 1476/77). Když archeologové ve 30. letech 20. století hrob otevřeli, našli místo něj jen zvířecí kosti.',
      en: 'Romania: Tradition places the body of Vlad the Impaler (died 1476/77) in this island monastery. When archaeologists opened the grave in the 1930s, they found only animal bones.',
      es: 'Rumanía: La tradición sitúa el cuerpo de Vlad el Empalador (muerto en 1476/77) en este monasterio isleño. Cuando los arqueólogos abrieron la tumba en los años treinta, solo hallaron huesos de animales.',
    },
    source: { label: 'Wikipedia: Snagov Monastery', url: 'https://en.wikipedia.org/wiki/Snagov_Monastery' },
  },
  {
    id: 'galapagos',
    years: [1600],
    territory: 'Galapágy',
    text: {
      cs: 'Ekvádor: Souostroví objevené roku 1535 biskupem Berlangou; jeho krotká, člověka se nebojící fauna později přivedla Charlese Darwina k úvahám, z nichž vyrostla evoluční teorie.',
      en: 'Ecuador: An archipelago discovered in 1535 by Bishop Berlanga; its tame, fearless fauna later set Charles Darwin on the path to evolutionary theory.',
      es: 'Ecuador: Un archipiélago descubierto en 1535 por el obispo Berlanga; su fauna mansa y sin miedo al hombre puso más tarde a Charles Darwin en el camino de la teoría de la evolución.',
    },
    source: { label: 'Wikipedia: Galápagos Islands', url: 'https://en.wikipedia.org/wiki/Gal%C3%A1pagos_Islands' },
  },
  {
    id: 'roanoke',
    years: [1600],
    territory: 'Roanoke',
    text: {
      cs: 'USA: Obyvatelé první anglické kolonie v Americe zmizeli mezi lety 1587 a 1590 beze stopy; jediným vodítkem zůstal nápis „CROATOAN“ vyřezaný do kůlu.',
      en: 'USA: The settlers of England’s first American colony vanished without a trace between 1587 and 1590; the only clue left was the word “CROATOAN” carved into a post.',
      es: 'EE. UU.: Los colonos de la primera colonia inglesa en América desaparecieron sin dejar rastro entre 1587 y 1590; la única pista fue la palabra «CROATOAN» tallada en un poste.',
    },
    source: { label: 'Wikipedia: Roanoke Colony', url: 'https://en.wikipedia.org/wiki/Roanoke_Colony' },
  },
  {
    id: 'cachtice-bathory',
    years: [1600],
    territory: 'Čachtice',
    text: {
      cs: 'Slovensko: Na Čachtickém hradě žila Alžběta Báthoryová (1560–1614), odsouzená dobovým procesem za vraždy dívek; legenda o koupelích v krvi panen ale vznikla až dlouho po její smrti.',
      en: 'Slovakia: Čachtice Castle was home to Elizabeth Báthory (1560–1614), condemned in her day for the murders of girls; the legend of her bathing in virgins’ blood arose long after her death.',
      es: 'Eslovaquia: El castillo de Čachtice fue el hogar de Isabel Báthory (1560–1614), condenada en su época por el asesinato de muchachas; la leyenda de sus baños en sangre de vírgenes surgió mucho después de su muerte.',
    },
    source: { label: 'Wikipedia: Elizabeth Báthory', url: 'https://en.wikipedia.org/wiki/Elizabeth_B%C3%A1thory' },
  },
  {
    id: 'vasa',
    years: [1650],
    territory: 'Stockholm',
    text: {
      cs: 'Švédsko: Královská válečná loď Vasa se roku 1628 potopila po necelých 1 300 metrech první plavby, na dohled od přístavu; z hloubky ji téměř neporušenou vyzvedli až v roce 1961.',
      en: 'Sweden: The royal warship Vasa sank in 1628 less than 1,300 metres into her maiden voyage, in sight of the harbour; she was raised almost intact only in 1961.',
      es: 'Suecia: El buque de guerra real Vasa se hundió en 1628 a menos de 1300 metros de iniciar su primer viaje, a la vista del puerto; solo en 1961 fue reflotado casi intacto.',
    },
    source: { label: 'Wikipedia: Vasa (ship)', url: 'https://en.wikipedia.org/wiki/Vasa_(ship)' },
  },
  {
    id: 'tower-ravens',
    years: [1700],
    territory: 'Tower of London',
    text: {
      cs: 'Anglie: Podle tradice připisované době Karla II. (60. léta 17. století) musí v Toweru žít nejméně šest havranů — jinak prý padne koruna i říše. Havrani tam s ustřiženými letkami žijí dodnes.',
      en: 'England: By a tradition ascribed to Charles II’s time (1660s), at least six ravens must live at the Tower — or crown and realm will fall. Clipped-winged ravens live there to this day.',
      es: 'Inglaterra: Según una tradición atribuida a la época de Carlos II (años 1660), al menos seis cuervos deben vivir en la Torre, o caerán la corona y el reino. Allí viven cuervos con las alas recortadas hasta hoy.',
    },
    source: { label: 'Wikipedia: Ravens of the Tower of London', url: 'https://en.wikipedia.org/wiki/Ravens_of_the_Tower_of_London' },
  },
  {
    id: 'frankenstein-castle',
    years: [1700],
    territory: 'Frankenstein',
    text: {
      cs: 'Německo: Na hradě Frankenstein se roku 1673 narodil alchymista Johann Konrad Dippel; pověsti o jeho pokusech s vykopanými těly bývají zmiňovány jako možná inspirace románu Mary Shelleyové.',
      en: 'Germany: The alchemist Johann Konrad Dippel was born at Frankenstein Castle in 1673; tales of his experiments with exhumed bodies are often cited as a possible inspiration for Mary Shelley’s novel.',
      es: 'Alemania: El alquimista Johann Konrad Dippel nació en el castillo de Frankenstein en 1673; los relatos sobre sus experimentos con cuerpos exhumados se citan a menudo como posible inspiración de la novela de Mary Shelley.',
    },
    source: { label: 'Wikipedia: Frankenstein Castle', url: 'https://en.wikipedia.org/wiki/Frankenstein_Castle' },
  },
  {
    id: 'kumari',
    years: [1783],
    territory: 'Káthmándú',
    text: {
      cs: 'Nepál: V paláci Kumari Ghar (postaven 1757) sídlí kumárí — malá dívka uctívaná jako živoucí bohyně, vybíraná podle dvaatřiceti přísných tělesných znaků.',
      en: 'Nepal: The Kumari Ghar palace (built 1757) houses the Kumari — a young girl worshipped as a living goddess, chosen by thirty-two strict bodily signs.',
      es: 'Nepal: El palacio Kumari Ghar (construido en 1757) alberga a la Kumari, una niña venerada como diosa viviente, elegida según treinta y dos estrictas señales corporales.',
    },
    source: { label: 'Wikipedia: Kumari (goddess)', url: 'https://en.wikipedia.org/wiki/Kumari_(goddess)' },
  },
  {
    id: 'paris-catacombs',
    years: [1800],
    territory: 'Paříž',
    text: {
      cs: 'Francie: Do sítě starých lomů pod městem se od roku 1786 přenášely ostatky z přeplněných hřbitovů; katakomby dnes ukrývají kosti asi šesti milionů Pařížanů.',
      en: 'France: From 1786, remains from the city’s overflowing cemeteries were moved into the old quarry tunnels below; the catacombs now hold the bones of some six million Parisians.',
      es: 'Francia: Desde 1786, los restos de los cementerios desbordados de la ciudad se trasladaron a los antiguos túneles de cantera; las catacumbas guardan hoy los huesos de unos seis millones de parisinos.',
    },
    source: { label: 'Wikipedia: Catacombs of Paris', url: 'https://en.wikipedia.org/wiki/Catacombs_of_Paris' },
  },
  {
    id: 'lokrum',
    years: [1815],
    territory: 'Lokrum',
    text: {
      cs: 'Chorvatsko: Když museli benediktini roku 1808 za napoleonské správy opustit ostrov u Dubrovníku, měli podle pověsti obejít Lokrum s obrácenými svícemi a proklít každého budoucího majitele.',
      en: 'Croatia: When the Benedictines had to leave this island off Dubrovnik in 1808 under Napoleonic rule, legend says they circled Lokrum with upturned candles, cursing every future owner.',
      es: 'Croacia: Cuando los benedictinos tuvieron que abandonar esta isla frente a Dubrovnik en 1808, bajo la administración napoleónica, la leyenda dice que rodearon Lokrum con velas invertidas, maldiciendo a todo futuro propietario.',
    },
    source: { label: 'Wikipedia: Lokrum', url: 'https://en.wikipedia.org/wiki/Lokrum' },
  },
  {
    id: 'cele-kula',
    years: [1815],
    territory: 'Niš',
    text: {
      cs: 'Srbsko: Po bitvě na Čegru roku 1809 nechala osmanská správa postavit v Niši věž z 952 lebek padlých srbských povstalců jako výstrahu; část jí stojí dodnes.',
      en: 'Serbia: After the 1809 battle of Čegar, the Ottoman authorities built a tower in Niš from 952 skulls of fallen Serbian rebels as a warning; part of it still stands.',
      es: 'Serbia: Tras la batalla de Čegar de 1809, las autoridades otomanas levantaron en Niš una torre con 952 cráneos de rebeldes serbios caídos, como advertencia; parte de ella sigue en pie.',
    },
    source: { label: 'Wikipedia: Skull Tower', url: 'https://en.wikipedia.org/wiki/Skull_Tower' },
  },
  {
    id: 'waterloo',
    years: [1815],
    territory: 'Waterloo',
    text: {
      cs: 'Belgie: U Waterloo byl roku 1815 poražen Napoleon. Dobové zprávy tvrdí, že kosti padlých byly v dalších desetiletích vykopávány a mlety na hnojivo; rozsah tohoto obchodu historici dosud zkoumají.',
      en: 'Belgium: Napoleon was defeated at Waterloo in 1815. Period reports claim the bones of the fallen were dug up in later decades and ground into fertilizer; historians are still weighing how large that trade really was.',
      es: 'Bélgica: Napoleón fue derrotado en Waterloo en 1815. Crónicas de la época afirman que los huesos de los caídos fueron exhumados décadas después y molidos como fertilizante; los historiadores aún estudian la escala real de ese comercio.',
    },
    source: { label: 'Wikipedia: Battle of Waterloo', url: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo' },
  },
  {
    id: 'lake-hillier',
    years: [1815],
    territory: 'Middle Island',
    text: {
      cs: 'Austrálie: Jezero Hillier, popsané výpravou Matthewa Flinderse roku 1802, má trvale jasně růžovou vodu; barvu působí halofilní řasy a mikroorganismy.',
      en: 'Australia: Lake Hillier, described by Matthew Flinders’s expedition in 1802, is permanently bright pink; the colour comes from salt-loving algae and microorganisms.',
      es: 'Australia: El lago Hillier, descrito por la expedición de Matthew Flinders en 1802, es de un rosa vivo permanente; el color se debe a algas y microorganismos halófilos.',
    },
    source: { label: 'Wikipedia: Lake Hillier', url: 'https://en.wikipedia.org/wiki/Lake_Hillier' },
  },
  {
    id: 'aokigahara',
    years: [1800],
    territory: 'Aokigahara',
    text: {
      cs: 'Japonsko: Hustý les na úpatí Fudži je spojen s legendou ubasute o odkládání starých lidí; magnetitové podloží tu místy vychyluje střelku kompasu, což živí pověsti, že se v lese nelze řídit ničím.',
      en: 'Japan: The dense forest at the foot of Fuji is tied to the ubasute legend of abandoning the old; magnetite in the ground locally deflects compass needles, feeding tales that nothing can guide you inside.',
      es: 'Japón: El denso bosque al pie del Fuji está ligado a la leyenda ubasute del abandono de los ancianos; la magnetita del suelo desvía localmente las brújulas, alimentando el mito de que dentro nada puede guiarte.',
    },
    source: { label: 'Wikipedia: Aokigahara', url: 'https://en.wikipedia.org/wiki/Aokigahara' },
  },
  {
    id: 'hallstatt-ossuary',
    years: [1800],
    territory: 'Hallstatt',
    text: {
      cs: 'Rakousko: Na malém horském hřbitově se kvůli nedostatku místa hroby po letech otvíraly a lebky se ukládaly do kostnice — od 18.–19. století zdobené malovanými květinovými věnci a jmény.',
      en: 'Austria: With space short in the little mountain graveyard, graves were reopened after years and the skulls moved to the charnel house — painted from the 18th–19th century with floral wreaths and names.',
      es: 'Austria: Por falta de espacio en el pequeño cementerio de montaña, las tumbas se reabrían al cabo de años y los cráneos pasaban al osario, pintados desde los siglos XVIII–XIX con coronas florales y nombres.',
    },
    source: { label: 'Wikipedia: Hallstatt', url: 'https://en.wikipedia.org/wiki/Hallstatt' },
  },
  {
    id: 'hill-of-crosses',
    years: [1880],
    territory: 'Šiauliai',
    text: {
      cs: 'Litva: Od proticarského povstání 1831 vztyčují lidé na pahorku u Šiauliai kříže jako symbol víry a odporu; dnes jich tam stojí statisíce a sovětský režim je marně několikrát srovnal buldozery.',
      en: 'Lithuania: Since the anti-tsarist uprising of 1831, people have planted crosses on a hill near Šiauliai as a sign of faith and defiance; hundreds of thousands stand there now, and Soviet bulldozers levelled them repeatedly in vain.',
      es: 'Lituania: Desde el levantamiento antizarista de 1831, la gente planta cruces en una colina cerca de Šiauliai como signo de fe y resistencia; hoy hay cientos de miles, y las excavadoras soviéticas las arrasaron varias veces en vano.',
    },
    source: { label: 'Wikipedia: Hill of Crosses', url: 'https://en.wikipedia.org/wiki/Hill_of_Crosses' },
  },
  {
    id: 'port-arthur',
    years: [1880],
    territory: 'Port Arthur',
    text: {
      cs: 'Austrálie (Tasmánie): Britská trestanecká kolonie (1830–1877) proslulá „moderním“ vězeňským systémem, který místo bičování sázel na naprostou izolaci a ticho — pro mnohé vězně horší trest.',
      en: 'Australia (Tasmania): A British penal colony (1830–1877) infamous for its “modern” prison system that replaced flogging with total isolation and silence — for many convicts a worse punishment.',
      es: 'Australia (Tasmania): Una colonia penal británica (1830–1877) tristemente célebre por su sistema penitenciario «moderno», que sustituyó los azotes por el aislamiento y el silencio totales, un castigo peor para muchos presos.',
    },
    source: { label: 'Wikipedia: Port Arthur, Tasmania', url: 'https://en.wikipedia.org/wiki/Port_Arthur,_Tasmania' },
  },
  {
    id: 'la-recoleta',
    years: [1880],
    territory: 'Buenos Aires',
    text: {
      cs: 'Argentina: Hřbitov La Recoleta (založen 1822) je mramorové město mrtvých; k jeho nejznámějším příběhům patří Rufina Cambaceresová, roku 1902 podle tradice pohřbená zaživa.',
      en: 'Argentina: La Recoleta cemetery (founded 1822) is a marble city of the dead; among its best-known stories is Rufina Cambaceres, by tradition buried alive in 1902.',
      es: 'Argentina: El cementerio de La Recoleta (fundado en 1822) es una ciudad de mármol de los muertos; entre sus historias más conocidas está la de Rufina Cambaceres, según la tradición enterrada viva en 1902.',
    },
    source: { label: 'Wikipedia: La Recoleta Cemetery', url: 'https://en.wikipedia.org/wiki/La_Recoleta_Cemetery' },
  },
  {
    id: 'moeraki-boulders',
    years: [1880],
    territory: 'Koekohe',
    text: {
      cs: 'Nový Zéland: Na pláži Koekohe leží obří, téměř kulovité balvany — konkrece staré miliony let, které moře postupně vymývá z pobřežních jílů; zmapovány byly v polovině 19. století.',
      en: 'New Zealand: Giant, near-spherical boulders lie on Koekohe Beach — million-year-old concretions the sea slowly washes out of the coastal mudstone; they were mapped in the mid-19th century.',
      es: 'Nueva Zelanda: En la playa de Koekohe yacen enormes rocas casi esféricas: concreciones de millones de años que el mar va liberando de las arcillas costeras; se cartografiaron a mediados del siglo XIX.',
    },
    source: { label: 'Wikipedia: Moeraki Boulders', url: 'https://en.wikipedia.org/wiki/Moeraki_Boulders' },
  },
  {
    id: 'tetepare',
    years: [1880],
    territory: 'Tetepare',
    text: {
      cs: 'Šalamounovy ostrovy: Největší neobydlený ostrov jižního Tichomoří opustili jeho obyvatelé v polovině 19. století naráz — podle ústní tradice ze strachu před nájezdy lovců lebek.',
      en: 'Solomon Islands: The largest uninhabited island of the South Pacific was abandoned by its people all at once in the mid-19th century — by oral tradition, out of fear of headhunting raids.',
      es: 'Islas Salomón: La mayor isla deshabitada del Pacífico Sur fue abandonada por su gente de golpe a mediados del siglo XIX; según la tradición oral, por miedo a las incursiones de cazadores de cabezas.',
    },
    source: { label: 'Wikipedie — hledat: Tetepare Island', url: 'https://en.wikipedia.org/w/index.php?search=Tetepare%20Island' },
  },
  {
    id: 'waitomo',
    years: [1900],
    territory: 'Waitomo',
    text: {
      cs: 'Nový Zéland: Vápencové jeskyně prozkoumané roku 1887 osvětlují tisíce larev Arachnocampa luminosa — „světlušek“, jejichž modrozelené světlo pokrývá stropy jako hvězdné nebe.',
      en: 'New Zealand: Limestone caves explored in 1887 are lit by thousands of Arachnocampa luminosa larvae — “glowworms” whose blue-green light covers the ceilings like a night sky.',
      es: 'Nueva Zelanda: Las cuevas calizas exploradas en 1887 están iluminadas por miles de larvas de Arachnocampa luminosa, «gusanos de luz» cuya luz azul verdosa cubre los techos como un cielo estrellado.',
    },
    source: { label: 'Wikipedia: Waitomo Glowworm Caves', url: 'https://en.wikipedia.org/wiki/Waitomo_Glowworm_Caves' },
  },
  {
    id: 'catatumbo',
    years: [1900],
    territory: 'Catatumbo',
    text: {
      cs: 'Venezuela: Nad ústím řeky Catatumbo se blýská až 160 nocí v roce, klidně deset hodin v kuse — nejvytrvalejší bouřkový jev na světě, popisovaný už staletí a vědecky zkoumaný od konce 19. století.',
      en: 'Venezuela: Over the mouth of the Catatumbo river, lightning storms rage up to 160 nights a year, often ten hours at a stretch — the world’s most persistent thunderstorm, described for centuries and studied scientifically since the late 19th century.',
      es: 'Venezuela: Sobre la desembocadura del Catatumbo hay tormentas de rayos hasta 160 noches al año, a menudo de diez horas seguidas: la tormenta más persistente del mundo, descrita durante siglos y estudiada científicamente desde finales del siglo XIX.',
    },
    source: { label: 'Wikipedia: Catatumbo lightning', url: 'https://en.wikipedia.org/wiki/Catatumbo_lightning' },
  },
  {
    id: 'tana-toraja',
    years: [1900],
    territory: 'Tana Toraja',
    text: {
      cs: 'Indonésie (Sulawesi): Torajové ukládají mrtvé do skalních hrobů a při obřadu ma’nene je po letech vyjímají, čistí a oblékají do nových šatů — smrt tu je dlouhým vztahem, ne koncem.',
      en: 'Indonesia (Sulawesi): The Toraja lay their dead in cliff tombs and, in the ma’nene rite, take them out years later to clean and dress them anew — death here is a long relationship, not an end.',
      es: 'Indonesia (Célebes): Los toraja depositan a sus muertos en tumbas excavadas en acantilados y, en el rito ma’nene, los sacan años después para limpiarlos y vestirlos de nuevo: aquí la muerte es una larga relación, no un final.',
    },
    source: { label: 'Wikipedia: Toraja', url: 'https://en.wikipedia.org/wiki/Toraja' },
  },
  {
    id: 'quinta-regaleira',
    years: [1914],
    territory: 'Sintra',
    text: {
      cs: 'Portugalsko: Sídlo Quinta da Regaleira (postaveno 1904–1910) skrývá 27 metrů hlubokou „iniciační studnu“ — obrácenou věž se spirálovým schodištěm, odkazující na zednářskou a rosekruciánskou symboliku.',
      en: 'Portugal: The Quinta da Regaleira estate (built 1904–1910) hides a 27-metre “initiation well” — an inverted tower with a spiral staircase steeped in Masonic and Rosicrucian symbolism.',
      es: 'Portugal: La Quinta da Regaleira (construida entre 1904 y 1910) esconde un «pozo iniciático» de 27 metros: una torre invertida con escalera de caracol cargada de simbolismo masónico y rosacruz.',
    },
    source: { label: 'Wikipedia: Quinta da Regaleira', url: 'https://en.wikipedia.org/wiki/Quinta_da_Regaleira' },
  },
  {
    id: 'caminito-del-rey',
    years: [1914],
    territory: 'El Chorro',
    text: {
      cs: 'Španělsko: Stezka přišroubovaná ke kolmým stěnám soutěsky El Chorro (stavěna 1901–1905) si po smrtelných nehodách vysloužila pověst nejnebezpečnějšího chodníku světa; od rekonstrukce 2015 je opět přístupná.',
      en: 'Spain: A walkway bolted to the sheer walls of the El Chorro gorge (built 1901–1905) earned a name as the world’s most dangerous path after fatal falls; rebuilt in 2015, it is open again.',
      es: 'España: Una pasarela atornillada a las paredes verticales del desfiladero de El Chorro (construida entre 1901 y 1905) se ganó fama de sendero más peligroso del mundo tras varias caídas mortales; reconstruida en 2015, vuelve a estar abierta.',
    },
    source: { label: 'Wikipedia: Caminito del Rey', url: 'https://en.wikipedia.org/wiki/Caminito_del_Rey' },
  },
  {
    id: 'kolmanskop',
    years: [1914],
    territory: 'Kolmanskop',
    text: {
      cs: 'Namibie: Luxusní diamantové městečko založené 1908 uprostřed pouště mělo kasino i první rentgen na jižní polokouli; po vyčerpání nalezišť je pohltil písek, který dnes plní opuštěné pokoje.',
      en: 'Namibia: A luxurious diamond town founded in 1908 in the desert had a casino and the southern hemisphere’s first X-ray machine; when the fields ran dry, the sand took it back and now fills its abandoned rooms.',
      es: 'Namibia: Un lujoso pueblo diamantífero fundado en 1908 en pleno desierto tuvo casino y la primera máquina de rayos X del hemisferio sur; agotados los yacimientos, la arena lo reclamó y hoy llena sus habitaciones abandonadas.',
    },
    source: { label: 'Wikipedia: Kolmanskop', url: 'https://en.wikipedia.org/wiki/Kolmanskop' },
  },
  {
    id: 'blood-falls',
    years: [1914],
    territory: 'Taylorův ledovec',
    text: {
      cs: 'Antarktida: Z Taylorova ledovce vytéká rudě zbarvená slaná voda — „Krvavé vodopády“, objevené 1911. Barvu způsobuje železo z pradávného podledovcového jezera, které se na vzduchu mění v rez.',
      en: 'Antarctica: Red-stained brine seeps from Taylor Glacier — the “Blood Falls”, found in 1911. The colour comes from iron in an ancient subglacial lake, rusting on contact with air.',
      es: 'Antártida: Del glaciar Taylor mana una salmuera teñida de rojo: las «Cataratas de Sangre», halladas en 1911. El color procede del hierro de un antiguo lago subglacial, que se oxida al contacto con el aire.',
    },
    source: { label: 'Wikipedia: Blood Falls', url: 'https://en.wikipedia.org/wiki/Blood_Falls' },
  },
  {
    id: 'deception-island',
    years: [1914],
    territory: 'Deception Island',
    text: {
      cs: 'Antarktida: Zatopená kaldera činné sopky slouží lodím jako přírodní přístav; od roku 1906 tu fungovala velrybářská stanice a na sopečném písku dodnes prýští termální prameny.',
      en: 'Antarctica: The flooded caldera of an active volcano serves ships as a natural harbour; a whaling station ran here from 1906, and thermal springs still rise through the volcanic sand.',
      es: 'Antártida: La caldera inundada de un volcán activo sirve de puerto natural; aquí funcionó desde 1906 una estación ballenera, y aún brotan fuentes termales en la arena volcánica.',
    },
    source: { label: 'Wikipedia: Deception Island', url: 'https://en.wikipedia.org/wiki/Deception_Island' },
  },
  {
    id: 'snake-island',
    years: [1920],
    territory: 'Queimada Grande',
    text: {
      cs: 'Brazílie: Ostrov Queimada Grande hostí mimořádně hustou populaci křovináře ostrovního — kriticky ohroženého jedovatého hada, který žije jen tady. Po automatizaci majáku ve 20. letech 20. století je vstup zakázán.',
      en: 'Brazil: Queimada Grande holds an extraordinarily dense population of the golden lancehead — a critically endangered venomous snake found nowhere else. Since the lighthouse was automated in the 1920s, entry has been forbidden.',
      es: 'Brasil: Queimada Grande alberga una población extraordinariamente densa de la yarará dorada, una serpiente venenosa en peligro crítico que solo vive allí. Desde que el faro se automatizó en los años veinte, la entrada está prohibida.',
    },
    source: { label: 'Wikipedia: Ilha da Queimada Grande', url: 'https://en.wikipedia.org/wiki/Ilha_da_Queimada_Grande' },
  },
  {
    id: 'crooked-forest',
    years: [1930],
    territory: 'Gryfino',
    text: {
      cs: 'Polsko: Háj asi 400 borovic vysazených kolem roku 1930 má kmeny u země ohnuté do pravého úhlu, všechny k severu; nejpravděpodobněji jde o záměrné tvarování pěstiteli, jehož účel se ale nedochoval.',
      en: 'Poland: A grove of some 400 pines planted around 1930 has trunks bent at right angles near the ground, all pointing north; most likely the growers shaped them on purpose, but the purpose itself is lost.',
      es: 'Polonia: Un bosquecillo de unos 400 pinos plantados hacia 1930 tiene los troncos doblados en ángulo recto junto al suelo, todos hacia el norte; lo más probable es que los cultivadores los moldearan a propósito, pero el propósito se perdió.',
    },
    source: { label: 'Wikipedia: Crooked Forest', url: 'https://en.wikipedia.org/wiki/Crooked_Forest' },
  },
  {
    id: 'pamir-highway',
    years: [1938],
    territory: 'Pamír',
    text: {
      cs: 'Tádžikistán: Pamírská dálnice, dobudovaná ve 30. letech 20. století, překonává průsmyky přes 4 600 m n. m. a je druhou nejvýše vedenou mezinárodní silnicí světa.',
      en: 'Tajikistan: The Pamir Highway, completed in the 1930s, crosses passes above 4,600 m and is the world’s second-highest international road.',
      es: 'Tayikistán: La carretera del Pamir, terminada en los años treinta, cruza puertos a más de 4600 m y es la segunda carretera internacional más alta del mundo.',
    },
    source: { label: 'Wikipedia: Pamir Highway', url: 'https://en.wikipedia.org/wiki/Pamir_Highway' },
  },
  {
    id: 'rjukan-sabotage',
    years: [1945],
    territory: 'Rjukan',
    text: {
      cs: 'Norsko: Roku 1943 sabotovali norští parašutisté továrnu na těžkou vodu ve Vemorku u Rjukanu a pomohli tak překazit nacistický jaderný program — jedna z nejslavnějších diverzí druhé světové války.',
      en: 'Norway: In 1943, Norwegian commandos sabotaged the heavy-water plant at Vemork near Rjukan, helping derail the Nazi nuclear programme — one of the most celebrated special operations of the Second World War.',
      es: 'Noruega: En 1943, comandos noruegos sabotearon la planta de agua pesada de Vemork, cerca de Rjukan, ayudando a frustrar el programa nuclear nazi: una de las operaciones especiales más célebres de la Segunda Guerra Mundial.',
    },
    source: { label: 'Wikipedia: Norwegian heavy water sabotage', url: 'https://en.wikipedia.org/wiki/Norwegian_heavy_water_sabotage' },
  },
  {
    id: 'flight-19',
    years: [1945],
    territory: 'Bermudský trojúhelník',
    text: {
      cs: 'Atlantik: Zmizení pěti letounů Letu 19 v prosinci 1945 odstartovalo novodobý mýtus Bermudského trojúhelníku; statistiky pojišťoven přitom oblast nijak nevybočující z průměru neukazují.',
      en: 'Atlantic: The disappearance of Flight 19’s five aircraft in December 1945 launched the modern myth of the Bermuda Triangle — even though insurers’ statistics show nothing unusual about the area.',
      es: 'Atlántico: La desaparición de los cinco aviones del Vuelo 19 en diciembre de 1945 lanzó el mito moderno del Triángulo de las Bermudas, aunque las estadísticas de las aseguradoras no muestran nada inusual en la zona.',
    },
    source: { label: 'Wikipedia: Flight 19', url: 'https://en.wikipedia.org/wiki/Flight_19' },
  },
  {
    id: 'john-frum',
    years: [1945],
    territory: 'Tanna',
    text: {
      cs: 'Vanuatu: Na ostrově Tanna pod činnou sopkou Yasur vzkvétá od 40. let 20. století „cargo kult“ Johna Fruma — hnutí očekávající návrat tajemného dobrodince s nákladem zboží.',
      en: 'Vanuatu: On Tanna, below the active Yasur volcano, the “cargo cult” of John Frum has flourished since the 1940s — a movement awaiting the return of a mysterious benefactor with a cargo of goods.',
      es: 'Vanuatu: En Tanna, bajo el volcán activo Yasur, florece desde los años cuarenta el «culto cargo» de John Frum, un movimiento que espera el regreso de un misterioso benefactor con un cargamento de bienes.',
    },
    source: { label: 'Wikipedia: John Frum', url: 'https://en.wikipedia.org/wiki/John_Frum' },
  },
  {
    id: 'ghana-coffins',
    years: [1960],
    territory: 'Teshie',
    text: {
      cs: 'Ghana: Od 50. let 20. století vyřezávají mistři v Teshie figurální rakve ve tvaru ryb, letadel či lahví — tvar vypráví o životě a snech zesnulého.',
      en: 'Ghana: Since the 1950s, craftsmen in Teshie have carved figurative coffins shaped as fish, planes or bottles — the form telling of the dead person’s life and dreams.',
      es: 'Ghana: Desde los años cincuenta, los artesanos de Teshie tallan ataúdes figurativos con forma de peces, aviones o botellas: la forma cuenta la vida y los sueños del difunto.',
    },
    source: { label: 'Wikipedia: Fantasy coffin', url: 'https://en.wikipedia.org/wiki/Fantasy_coffin' },
  },
  {
    id: 'dolls-island',
    years: [1960],
    territory: 'Xochimilco',
    text: {
      cs: 'Mexiko: Na ostrůvku v kanálech Xochimilca věšel poustevník Julián Santana od 50. let 20. století na stromy stovky starých panenek — podle vlastních slov na usmíření ducha utonulé dívky.',
      en: 'Mexico: On an islet in the Xochimilco canals, the hermit Julián Santana hung hundreds of old dolls in the trees from the 1950s on — by his own account, to appease the spirit of a drowned girl.',
      es: 'México: En un islote de los canales de Xochimilco, el ermitaño Julián Santana colgó de los árboles cientos de muñecas viejas desde los años cincuenta; según sus propias palabras, para apaciguar el espíritu de una niña ahogada.',
    },
    source: { label: 'Wikipedia: Island of the Dolls', url: 'https://en.wikipedia.org/wiki/Island_of_the_Dolls' },
  },
  {
    id: 'area-51',
    years: [1960],
    territory: 'Nevada',
    text: {
      cs: 'USA: Přísně tajná letecká základna zřízená roku 1955 k testům špionážního letounu U-2; utajení kolem ní dalo ve 20. století vzniknout nejznámějším konspiracím o UFO. Její existenci vláda oficiálně přiznala až 2013.',
      en: 'USA: A top-secret airbase established in 1955 to test the U-2 spy plane; the secrecy around it bred the 20th century’s most famous UFO conspiracies. The government only officially acknowledged it in 2013.',
      es: 'EE. UU.: Una base aérea ultrasecreta creada en 1955 para probar el avión espía U-2; el secretismo que la rodeaba engendró las conspiraciones ovni más famosas del siglo XX. El gobierno solo reconoció oficialmente su existencia en 2013.',
    },
    source: { label: 'Wikipedia: Area 51', url: 'https://en.wikipedia.org/wiki/Area_51' },
  },
  {
    id: 'dmz-korea',
    years: [1960],
    territory: 'Korejská DMZ',
    text: {
      cs: 'Korea: Demilitarizovaná zóna vzniklá příměřím roku 1953 rozděluje poloostrov pásem téměř bez lidí — a právě proto se z něj stala nechtěná, ale unikátní přírodní rezervace.',
      en: 'Korea: The Demilitarized Zone created by the 1953 armistice divides the peninsula with a strip nearly empty of people — which is exactly why it became an unintended, unique nature reserve.',
      es: 'Corea: La Zona Desmilitarizada creada por el armisticio de 1953 divide la península con una franja casi sin gente, y justo por eso se convirtió en una reserva natural única e involuntaria.',
    },
    source: { label: 'Wikipedia: Korean Demilitarized Zone', url: 'https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone' },
  },
  {
    id: 'lake-bodom',
    years: [1960],
    territory: 'Bodom',
    text: {
      cs: 'Finsko: Čtyři stanující teenageři byli u jezera Bodom v roce 1960 v noci přepadeni; tři zavraždění, jeden těžce zraněný. Případ nebyl nikdy objasněn a je nejznámější finskou kriminální záhadou.',
      en: 'Finland: Four camping teenagers were attacked at night by Lake Bodom in 1960; three were murdered, one badly wounded. Never solved, it remains Finland’s most famous criminal mystery.',
      es: 'Finlandia: Cuatro adolescentes que acampaban junto al lago Bodom fueron atacados de noche en 1960; tres fueron asesinados y uno quedó gravemente herido. Nunca resuelto, sigue siendo el misterio criminal más famoso de Finlandia.',
    },
    source: { label: 'Wikipedia: Lake Bodom murders', url: 'https://en.wikipedia.org/wiki/Lake_Bodom_murders' },
  },
  {
    id: 'dallol',
    years: [1960],
    territory: 'Dallol',
    text: {
      cs: 'Etiopie: Sopečná oblast s kyselinovými gejzíry a sirnými prameny; měření z let 1960–66 tu zaznamenala nejvyšší průměrnou roční teplotu obydleného místa na světě. Dnešní Dallol je už opuštěný.',
      en: 'Ethiopia: A volcanic area of acid geysers and sulphur springs; measurements from 1960–66 recorded the highest average annual temperature of any inhabited place on Earth here. Dallol today stands abandoned.',
      es: 'Etiopía: Una zona volcánica de géiseres ácidos y fuentes de azufre; las mediciones de 1960–66 registraron aquí la temperatura media anual más alta de un lugar habitado en la Tierra. Hoy Dallol está abandonado.',
    },
    source: { label: 'Wikipedia: Dallol, Ethiopia', url: 'https://en.wikipedia.org/wiki/Dallol,_Ethiopia' },
  },
  {
    id: 'alcatraz-escape',
    years: [1994],
    territory: 'Alcatraz',
    text: {
      cs: 'USA: Roku 1962 zmizeli Frank Morris a bratři Anglinové z „nedobytného“ Alcatrazu na voru z pláštěnek, s hlavami z papírmaše v postelích. Zda dopluli, se nikdy nezjistilo; věznice zavřela rok nato.',
      en: 'USA: In 1962 Frank Morris and the Anglin brothers vanished from “escape-proof” Alcatraz on a raincoat raft, leaving papier-mâché heads in their beds. Whether they made it ashore was never established; the prison closed a year later.',
      es: 'EE. UU.: En 1962, Frank Morris y los hermanos Anglin desaparecieron de la «inexpugnable» Alcatraz en una balsa de impermeables, dejando cabezas de papel maché en sus camas. Nunca se supo si llegaron a tierra; la prisión cerró un año después.',
    },
    source: { label: 'Wikipedia: Alcatraz Federal Penitentiary', url: 'https://en.wikipedia.org/wiki/Alcatraz_Federal_Penitentiary' },
  },
  {
    id: 'surtsey',
    years: [1994],
    territory: 'Surtsey',
    text: {
      cs: 'Island: V roce 1963 vyrostl z podmořské erupce nový ostrov Surtsey. Vstup je povolen jen hrstce vědců, kteří na něm od začátku sledují, jak si život sám osidluje panenskou zemi.',
      en: 'Iceland: In 1963 a submarine eruption raised the new island of Surtsey. Only a handful of scientists may set foot on it, watching from day one how life colonizes virgin land on its own.',
      es: 'Islandia: En 1963, una erupción submarina hizo surgir la nueva isla de Surtsey. Solo un puñado de científicos puede pisarla, observando desde el primer día cómo la vida coloniza por sí sola una tierra virgen.',
    },
    source: { label: 'Wikipedia: Surtsey', url: 'https://en.wikipedia.org/wiki/Surtsey' },
  },
  {
    id: 'robben-island',
    years: [1994],
    territory: 'Robben Island',
    text: {
      cs: 'Jižní Afrika: Na vězeňském ostrově strávil Nelson Mandela od roku 1964 osmnáct ze svých sedmadvaceti let za mřížemi; v roce 1994, kdy náš snímek končí století apartheidu, se stal prezidentem.',
      en: 'South Africa: On the prison island, Nelson Mandela spent eighteen of his twenty-seven years behind bars from 1964; in 1994 — the year of this snapshot — he became president.',
      es: 'Sudáfrica: En la isla-prisión, Nelson Mandela pasó desde 1964 dieciocho de sus veintisiete años entre rejas; en 1994, el año de esta instantánea, se convirtió en presidente.',
    },
    source: { label: 'Wikipedia: Robben Island', url: 'https://en.wikipedia.org/wiki/Robben_Island' },
  },
  {
    id: 'darvaza',
    years: [1994],
    territory: 'Darvaza',
    text: {
      cs: 'Turkmenistán: „Brána do pekla“ — kráter v poušti Karakum, z něhož od 70. let 20. století bez přestávky hoří zemní plyn. Podle rozšířené verze jej zapálili sovětští geologové v roce 1971; přesné okolnosti vzniku ale doložené nejsou.',
      en: 'Turkmenistan: The “Door to Hell” — a Karakum desert crater whose natural gas has burned nonstop since the 1970s. The common account has Soviet geologists igniting it in 1971, though the exact origin is not documented.',
      es: 'Turkmenistán: La «Puerta del Infierno», un cráter del desierto de Karakum cuyo gas natural arde sin pausa desde los años setenta. La versión más difundida dice que geólogos soviéticos lo prendieron en 1971, aunque el origen exacto no está documentado.',
    },
    source: { label: 'Wikipedia: Darvaza gas crater', url: 'https://en.wikipedia.org/wiki/Darvaza_gas_crater' },
  },
  {
    id: 'hoxha-bunkers',
    years: [1994],
    territory: 'Albánie',
    text: {
      cs: 'Albánie: Z obavy před invazí nechal Enver Hodža od 70. let vybetonovat po celé zemi obrovské množství bunkrů — běžně se uvádí přes 170 000; dodnes jsou rozeseté po polích, plážích i městech.',
      en: 'Albania: Fearing invasion, Enver Hoxha had an enormous number of concrete bunkers poured across the country from the 1970s — a figure over 170,000 is commonly cited; they still dot fields, beaches and towns.',
      es: 'Albania: Temiendo una invasión, Enver Hoxha hizo hormigonar desde los años setenta una enorme cantidad de búnkeres por todo el país —se suele citar una cifra de más de 170 000—; aún salpican campos, playas y ciudades.',
    },
    source: { label: 'Wikipedia: Bunkers of Albania', url: 'https://en.wikipedia.org/wiki/Bunkers_of_Albania' },
  },
  {
    id: 'buzludzha',
    years: [1994],
    territory: 'Buzludža',
    text: {
      cs: 'Bulharsko: Obří komunistický památník ve tvaru létajícího talíře na vrcholu hory, otevřený 1981; po pádu režimu zchátral v jednu z nejpůsobivějších opuštěných staveb Evropy.',
      en: 'Bulgaria: A giant saucer-shaped communist monument on a mountaintop, opened in 1981; after the regime fell it decayed into one of Europe’s most striking abandoned buildings.',
      es: 'Bulgaria: Un gigantesco monumento comunista con forma de platillo sobre una cumbre, inaugurado en 1981; tras la caída del régimen se degradó hasta ser uno de los edificios abandonados más impresionantes de Europa.',
    },
    source: { label: 'Wikipedia: Buzludzha Monument', url: 'https://en.wikipedia.org/wiki/Buzludzha_Monument' },
  },
  {
    id: 'ryugyong',
    years: [1994],
    territory: 'Pchjongjang',
    text: {
      cs: 'Severní Korea: Stopatropatrová pyramida hotelu Rjugjong se staví od roku 1987 a nikdy nebyla otevřena — drží tak neslavný rekord nejvyšší neobydlené budovy světa.',
      en: 'North Korea: The 105-storey pyramid of the Ryugyong Hotel has been under construction since 1987 and has never opened — holding the dubious record of the world’s tallest unoccupied building.',
      es: 'Corea del Norte: La pirámide de 105 plantas del hotel Ryugyong está en obras desde 1987 y nunca se ha inaugurado: ostenta el dudoso récord de edificio deshabitado más alto del mundo.',
    },
    source: { label: 'Wikipedia: Ryugyong Hotel', url: 'https://en.wikipedia.org/wiki/Ryugyong_Hotel' },
  },
  {
    id: 'pripyat',
    years: [1994],
    territory: 'Pripjať',
    text: {
      cs: 'Ukrajina: Po výbuchu černobylské elektrárny v roce 1986 bylo město Pripjať evakuováno za jediné odpoledne; zůstalo zamrzlé v sovětské éře i s vybavením bytů a slavným ruským kolem, které se nikdy neroztočilo pro veřejnost.',
      en: 'Ukraine: After the Chernobyl explosion in 1986, the city of Pripyat was evacuated in a single afternoon; it stays frozen in the Soviet era, flats still furnished, its famous Ferris wheel never opened to the public.',
      es: 'Ucrania: Tras la explosión de Chernóbil en 1986, la ciudad de Prípiat fue evacuada en una sola tarde; quedó congelada en la era soviética, con los pisos aún amueblados y su famosa noria, que nunca abrió al público.',
    },
    source: { label: 'Wikipedia: Pripyat', url: 'https://en.wikipedia.org/wiki/Pripyat' },
  },
  {
    id: 'uluru',
    years: [1994],
    territory: 'Uluru',
    text: {
      cs: 'Austrálie: Posvátný pískovcový monolit spjatý s mýty Času snění byl roku 1985 vrácen domorodým Aṉangům; od roku 2019 je na něj zakázáno vystupovat.',
      en: 'Australia: The sacred sandstone monolith, bound to the Dreamtime creation stories, was returned to the Aṉangu people in 1985; climbing it has been banned since 2019.',
      es: 'Australia: El monolito sagrado de arenisca, ligado a los mitos del Tiempo del Sueño, fue devuelto al pueblo anangu en 1985; escalarlo está prohibido desde 2019.',
    },
    source: { label: 'Wikipedia: Uluru', url: 'https://en.wikipedia.org/wiki/Uluru' },
  },
  {
    id: 'kjeragbolten',
    years: [1994],
    territory: 'Kjerag',
    text: {
      cs: 'Norsko: Kjeragbolten je balvan zaklíněný ve skalní puklině 984 metrů nad Lysefjordem; od 90. let je oblíbenou — a nervy drásající — fotografickou zastávkou turistů.',
      en: 'Norway: Kjeragbolten is a boulder wedged in a mountain crevice 984 metres above the Lysefjord; since the 1990s it has been a beloved — and nerve-shredding — photo stop for hikers.',
      es: 'Noruega: Kjeragbolten es una roca encajada en una grieta a 984 metros sobre el Lysefjord; desde los años noventa es una parada fotográfica querida —y estremecedora— para los senderistas.',
    },
    source: { label: 'Wikipedia: Kjeragbolten', url: 'https://en.wikipedia.org/wiki/Kjeragbolten' },
  },
  {
    id: 'matmata',
    years: [1994],
    territory: 'Matmata',
    text: {
      cs: 'Tunisko: Berbeři v Matmatě po staletí žijí v podzemních obydlích vyhloubených do země; jedno z nich se v roce 1976 při natáčení Star Wars stalo rodným domem Luka Skywalkera a slouží jako hotel dodnes.',
      en: 'Tunisia: The Berbers of Matmata have lived for centuries in pit dwellings dug into the earth; in 1976 one of them became Luke Skywalker’s childhood home during the Star Wars shoot, and it still runs as a hotel.',
      es: 'Túnez: Los bereberes de Matmata viven desde hace siglos en viviendas excavadas en la tierra; en 1976, una de ellas se convirtió en la casa natal de Luke Skywalker durante el rodaje de Star Wars, y sigue funcionando como hotel.',
    },
    source: { label: 'Wikipedia: Matmata, Tunisia', url: 'https://en.wikipedia.org/wiki/Matmata,_Tunisia' },
  },
  {
    id: 'blue-hole',
    years: [1994],
    territory: 'Lighthouse Reef',
    text: {
      cs: 'Belize: Velkou modrou díru — kruhový podmořský závrt hluboký přes 120 metrů s krápníky z dob ledových — proslavila výprava Jacquesa Cousteaua v roce 1971.',
      en: 'Belize: The Great Blue Hole — a circular marine sinkhole over 120 metres deep, with ice-age stalactites — was made famous by Jacques Cousteau’s 1971 expedition.',
      es: 'Belice: El Gran Agujero Azul, un sumidero marino circular de más de 120 metros de profundidad con estalactitas de las glaciaciones, se hizo famoso por la expedición de Jacques Cousteau en 1971.',
    },
    source: { label: 'Wikipedia: Great Blue Hole', url: 'https://en.wikipedia.org/wiki/Great_Blue_Hole' },
  },
  {
    id: 'salar-de-uyuni',
    years: [1994],
    territory: 'Salar de Uyuni',
    text: {
      cs: 'Bolívie: Největší solná pláň světa (přes 10 000 km²) se v období dešťů mění v dokonalé zrcadlo oblohy; pod krustou leží jedny z největších světových zásob lithia.',
      en: 'Bolivia: The world’s largest salt flat (over 10,000 km²) turns into a perfect mirror of the sky in the rainy season; beneath the crust lie some of the world’s largest lithium reserves.',
      es: 'Bolivia: El mayor salar del mundo (más de 10 000 km²) se convierte en la temporada de lluvias en un espejo perfecto del cielo; bajo la costra yacen unas de las mayores reservas de litio del planeta.',
    },
    source: { label: 'Wikipedia: Salar de Uyuni', url: 'https://en.wikipedia.org/wiki/Salar_de_Uyuni' },
  },
  {
    id: 'khongoryn-els',
    years: [1994],
    territory: 'Gobi',
    text: {
      cs: 'Mongolsko: Duny Khongoryn Els v poušti Gobi „zpívají“ — sesouvající se písek vydává hluboký dunivý tón slyšitelný na kilometry; odtud jejich přezdívka Zpívající písky.',
      en: 'Mongolia: The Khongoryn Els dunes in the Gobi “sing” — sliding sand gives off a deep booming tone heard kilometres away, earning them the name Singing Sands.',
      es: 'Mongolia: Las dunas de Khongoryn Els, en el Gobi, «cantan»: la arena al deslizarse emite un tono grave y retumbante audible a kilómetros, lo que les valió el nombre de Arenas Cantoras.',
    },
    source: { label: 'Wikipedie — hledat: Khongoryn Els', url: 'https://en.wikipedia.org/w/index.php?search=Khongoryn%20Els' },
  },
  {
    id: 'chocolate-hills',
    years: [1994],
    territory: 'Bohol',
    text: {
      cs: 'Filipíny: Přes tisíc pravidelných kuželovitých pahorků na ostrově Bohol získává v období sucha čokoládovou barvu; za přírodní památku byly vyhlášeny roku 1988.',
      en: 'Philippines: Over a thousand regular cone-shaped mounds on Bohol turn chocolate-brown in the dry season; they were declared a natural monument in 1988.',
      es: 'Filipinas: Más de mil montículos cónicos y regulares en Bohol adquieren color chocolate en la estación seca; fueron declarados monumento natural en 1988.',
    },
    source: { label: 'Wikipedia: Chocolate Hills', url: 'https://en.wikipedia.org/wiki/Chocolate_Hills' },
  },
  {
    id: 'beer-temple',
    years: [1994],
    territory: 'Sisaket',
    text: {
      cs: 'Thajsko: Mniši z Wat Pa Maha Chedi Kaew začali v 80. letech stavět chrámový areál z vysbíraných pivních lahví; zdi z více než milionu zelených a hnědých lahví se nemusejí nikdy natírat.',
      en: 'Thailand: The monks of Wat Pa Maha Chedi Kaew began building a temple complex from collected beer bottles in the 1980s; walls of over a million green and brown bottles never need painting.',
      es: 'Tailandia: Los monjes de Wat Pa Maha Chedi Kaew empezaron en los años ochenta a construir un complejo de templos con botellas de cerveza recogidas; los muros de más de un millón de botellas verdes y marrones nunca necesitan pintura.',
    },
    source: { label: 'Wikipedia: Wat Pa Maha Chedi Kaew', url: 'https://en.wikipedia.org/wiki/Wat_Pa_Maha_Chedi_Kaew' },
  },
  {
    id: 'point-nemo',
    years: [1994],
    territory: 'Bod Nemo',
    text: {
      cs: 'Tichý oceán: Bod Nemo, přesně vypočtený roku 1992, je místo nejvzdálenější od jakékoli pevniny (přes 2 600 km). Kosmické agentury nad ním řízeně ukončují družice — okolí je „hřbitovem kosmických lodí“.',
      en: 'Pacific Ocean: Point Nemo, precisely computed in 1992, is the spot farthest from any land (over 2,600 km). Space agencies deorbit craft over it — the surrounding seabed is a “spacecraft cemetery”.',
      es: 'Océano Pacífico: El Punto Nemo, calculado con precisión en 1992, es el lugar más alejado de cualquier tierra (más de 2600 km). Las agencias espaciales desorbitan naves sobre él: el fondo circundante es un «cementerio de naves espaciales».',
    },
    source: { label: 'Wikipedia: Pole of inaccessibility', url: 'https://en.wikipedia.org/wiki/Pole_of_inaccessibility' },
  },
  {
    id: 'kotor',
    years: [1994],
    territory: 'Kotor',
    text: {
      cs: 'Černá Hora: Středověké město v zálivu připomínajícím fjord, od roku 1979 na seznamu UNESCO; proslulé je i láskou ke kočkám, které tu mají vlastní muzeum a status neoficiálního symbolu města.',
      en: 'Montenegro: A medieval town in a fjord-like bay, UNESCO-listed since 1979; it is also famous for its love of cats, which have their own museum and the status of unofficial town symbol.',
      es: 'Montenegro: Una ciudad medieval en una bahía que recuerda a un fiordo, en la lista de la UNESCO desde 1979; también es famosa por su amor a los gatos, que tienen museo propio y estatus de símbolo extraoficial de la ciudad.',
    },
    source: { label: 'Wikipedia: Kotor', url: 'https://en.wikipedia.org/wiki/Kotor' },
  },
  {
    id: 'naica-crystals',
    years: [2000],
    territory: 'Naica',
    text: {
      cs: 'Mexiko: Horníci v dole Naica narazili roku 2000 na jeskyni s obřími krystaly sádrovce (selenitu) dlouhými až 12 metrů — v 58° horku a stoprocentní vlhkosti v ní lze bez ochrany vydržet jen minuty.',
      en: 'Mexico: In 2000, miners at Naica broke into a cave of giant gypsum (selenite) crystals up to 12 metres long — at 58 °C and full humidity, an unprotected person can last only minutes inside.',
      es: 'México: En 2000, los mineros de Naica dieron con una cueva de cristales gigantes de yeso (selenita) de hasta 12 metros; a 58 °C y humedad total, una persona sin protección solo resiste minutos dentro.',
    },
    source: { label: 'Wikipedia: Cave of the Crystals', url: 'https://en.wikipedia.org/wiki/Cave_of_the_Crystals' },
  },
  {
    id: 'cano-cristales',
    years: [2000],
    territory: 'Caño Cristales',
    text: {
      cs: 'Kolumbie: „Řeka pěti barev“ — na dně Caño Cristales rozkvétá endemická vodní rostlina Macarenia clavigera a barví řeku od července do listopadu do ruda.',
      en: 'Colombia: The “river of five colours” — on the bed of Caño Cristales the endemic water plant Macarenia clavigera blooms, turning the river red from July to November.',
      es: 'Colombia: El «río de los cinco colores»: en el lecho del Caño Cristales florece la planta acuática endémica Macarenia clavigera, tiñendo el río de rojo de julio a noviembre.',
    },
    source: { label: 'Wikipedia: Caño Cristales', url: 'https://en.wikipedia.org/wiki/Ca%C3%B1o_Cristales' },
  },
  {
    id: 'visoko',
    years: [2010],
    territory: 'Visoko',
    text: {
      cs: 'Bosna a Hercegovina: Od roku 2005 tvrdí amatérský badatel Semir Osmanagić, že kopce u Visoka jsou nejstarší pyramidy světa; geologové je považují za přírodní útvary a tvrzení odmítají jako pseudoarcheologii.',
      en: 'Bosnia and Herzegovina: Since 2005, amateur researcher Semir Osmanagić has claimed the hills near Visoko are the world’s oldest pyramids; geologists consider them natural formations and reject the claim as pseudoarchaeology.',
      es: 'Bosnia y Herzegovina: Desde 2005, el investigador aficionado Semir Osmanagić sostiene que las colinas de Visoko son las pirámides más antiguas del mundo; los geólogos las consideran formaciones naturales y rechazan la afirmación como pseudoarqueología.',
    },
    source: { label: 'Wikipedie — hledat: Bosnian pyramid claims', url: 'https://en.wikipedia.org/w/index.php?search=Bosnian%20pyramid%20claims' },
  },
  {
    id: 'lake-natron',
    years: [2010],
    territory: 'Natron',
    text: {
      cs: 'Tanzanie: Extrémně zásadité jezero Natron konzervuje těla uhynulých zvířat sodou a solí, takže vypadají jako „zkamenělá“; proslavila je fotografická série z roku 2013. Zároveň je největším hnízdištěm plameňáků malých.',
      en: 'Tanzania: The extremely alkaline Lake Natron preserves the bodies of dead animals with soda and salt so they look “turned to stone”; a 2013 photo series made them famous. It is also the greatest breeding ground of lesser flamingos.',
      es: 'Tanzania: El extremadamente alcalino lago Natron conserva con sosa y sal los cuerpos de animales muertos, que parecen «petrificados»; una serie fotográfica de 2013 los hizo célebres. Es además el mayor criadero de flamencos enanos.',
    },
    source: { label: 'Wikipedia: Lake Natron', url: 'https://en.wikipedia.org/wiki/Lake_Natron' },
  },
  {
    id: 'baobab-avenue',
    years: [2010],
    territory: 'Morondava',
    text: {
      cs: 'Madagaskar: Alej mohutných baobabů Grandidierových, z nichž některé jsou staré stovky let, získala v roce 2007 status chráněné přírodní památky — vypadají, jako by rostly kořeny vzhůru.',
      en: 'Madagascar: The avenue of towering Grandidier’s baobabs, some centuries old, gained protected natural monument status in 2007 — they look as if planted roots-up.',
      es: 'Madagascar: La avenida de imponentes baobabs de Grandidier, algunos con siglos de edad, obtuvo en 2007 el estatus de monumento natural protegido; parecen plantados con las raíces hacia arriba.',
    },
    source: { label: 'Wikipedia: Avenue of the Baobabs', url: 'https://en.wikipedia.org/wiki/Avenue_of_the_Baobabs' },
  },
  {
    id: 'son-doong',
    years: [2010],
    territory: 'Sơn Đoòng',
    text: {
      cs: 'Vietnam: Sơn Đoòng, poprvé kompletně prozkoumaná roku 2009, je objemem největší známá jeskyně světa — propadlými stropy do ní prší světlo a uvnitř roste vlastní džungle s vlastním mikroklimatem.',
      en: 'Vietnam: Sơn Đoòng, first fully surveyed in 2009, is the largest known cave by volume — light rains in through collapsed ceilings, and a jungle with its own microclimate grows inside.',
      es: 'Vietnam: Sơn Đoòng, explorada por completo por primera vez en 2009, es la cueva más grande conocida por volumen; la luz entra por techos derrumbados y dentro crece una selva con su propio microclima.',
    },
    source: { label: 'Wikipedia: Sơn Đoòng Cave', url: 'https://en.wikipedia.org/wiki/S%C6%A1n_%C4%90o%C3%B2ng_Cave' },
  },
  {
    id: 'nyiragongo',
    years: [2010],
    territory: 'Nyiragongo',
    text: {
      cs: 'DR Kongo: Sopka Nyiragongo chová v kráteru největší lávové jezero světa; její mimořádně tekutá láva se při erupci 2002 valila na město Goma rychlostí desítek kilometrů v hodině.',
      en: 'DR Congo: Nyiragongo holds the world’s largest lava lake in its crater; its unusually fluid lava raced toward the city of Goma at tens of kilometres per hour in the 2002 eruption.',
      es: 'RD del Congo: El Nyiragongo alberga en su cráter el mayor lago de lava del mundo; su lava, inusualmente fluida, corrió hacia la ciudad de Goma a decenas de kilómetros por hora en la erupción de 2002.',
    },
    source: { label: 'Wikipedia: Mount Nyiragongo', url: 'https://en.wikipedia.org/wiki/Mount_Nyiragongo' },
  },
  {
    id: 'svalbard-vault',
    years: [2010],
    territory: 'Špicberky',
    text: {
      cs: 'Norsko (Špicberky): Globální úložiště semen, otevřené 2008 v permafrostu, je „bankou poslední záchrany“ pro plodiny lidstva; první výběr si vyžádala syrská válka v roce 2015.',
      en: 'Norway (Svalbard): The Global Seed Vault, opened in 2008 in the permafrost, is humanity’s “bank of last resort” for crops; the first withdrawal was forced by the Syrian war in 2015.',
      es: 'Noruega (Svalbard): La Bóveda Global de Semillas, abierta en 2008 en el permafrost, es el «banco de último recurso» de los cultivos de la humanidad; la primera retirada la forzó la guerra de Siria en 2015.',
    },
    source: { label: 'Wikipedia: Svalbard Global Seed Vault', url: 'https://en.wikipedia.org/wiki/Svalbard_Global_Seed_Vault' },
  },
  {
    id: 'underwater-waterfall',
    years: [2010],
    territory: 'Le Morne',
    text: {
      cs: 'Mauricius: U poloostrova Le Morne Brabant vytváří písek strhávaný proudy do hlubin dokonalou iluzi podmořského vodopádu — nejlépe viditelnou z letadla; snímky ji proslavily kolem roku 2010.',
      en: 'Mauritius: Off the Le Morne Brabant peninsula, sand dragged into the deep by currents creates a perfect illusion of an underwater waterfall — best seen from the air; photographs made it famous around 2010.',
      es: 'Mauricio: Frente a la península de Le Morne Brabant, la arena arrastrada a las profundidades por las corrientes crea la ilusión perfecta de una cascada submarina, visible sobre todo desde el aire; las fotos la hicieron famosa hacia 2010.',
    },
    source: { label: 'Wikipedia: Le Morne Brabant', url: 'https://en.wikipedia.org/wiki/Le_Morne_Brabant' },
  },
  {
    id: 'spotted-lake',
    years: [2010],
    territory: 'Kliluk',
    text: {
      cs: 'Kanada: Mineralizované jezero Kliluk („Spotted Lake“), posvátné pro národ Okanaganů a roku 2001 jim navrácené, se v létě odpařuje do desítek barevných minerálních jezírek.',
      en: 'Canada: The mineral lake Kliluk (“Spotted Lake”), sacred to the Okanagan people and returned to them in 2001, evaporates each summer into dozens of coloured mineral pools.',
      es: 'Canadá: El lago mineral Kliluk («Spotted Lake»), sagrado para el pueblo okanagan y devuelto a ellos en 2001, se evapora cada verano en decenas de pozas minerales de colores.',
    },
    source: { label: 'Wikipedia: Spotted Lake', url: 'https://en.wikipedia.org/wiki/Spotted_Lake' },
  },
];
