import type { LocaleCode } from './strings';

/**
 * Hand-curated translations of territory names for the tooltip, the panel
 * title and the Wikipedia search — the places where a Czech or Spanish reader
 * meets a name first.
 *
 * The dataset record itself always stays verbatim: the NAME/SUBJECTO rows in
 * the panel show exactly what the file contains, and a glossed title carries
 * the original as its hover text. A name not in this table renders as-is —
 * a missing translation is better than a guessed one, so only well-known
 * entities are listed, spelling variants (and upstream typos) included.
 *
 * Keys are lower-cased, trimmed dataset names.
 */
const GLOSSES: Record<string, { cs: string; es: string }> = {
  /* --- modern states & colonial empires --- */
  'russian empire': { cs: 'Ruské impérium', es: 'Imperio ruso' },
  'ussr': { cs: 'SSSR', es: 'URSS' },
  'russia': { cs: 'Rusko', es: 'Rusia' },
  'white russia': { cs: '„Bílé“ Rusko', es: 'Rusia «blanca»' },
  'far eastern ssr': { cs: 'Dálněvýchodní republika', es: 'República del Extremo Oriente' },
  'france': { cs: 'Francie', es: 'Francia' },
  'portugal': { cs: 'Portugalsko', es: 'Portugal' },
  'spain': { cs: 'Španělsko', es: 'España' },
  'united kingdom': { cs: 'Spojené království', es: 'Reino Unido' },
  'united kingdom of great britain and ireland': { cs: 'Spojené království Velké Británie a Irska', es: 'Reino Unido de Gran Bretaña e Irlanda' },
  'england': { cs: 'Anglie', es: 'Inglaterra' },
  'england and ireland': { cs: 'Anglie a Irsko', es: 'Inglaterra e Irlanda' },
  'scotland': { cs: 'Skotsko', es: 'Escocia' },
  'ireland': { cs: 'Irsko', es: 'Irlanda' },
  'kingdom of ireland': { cs: 'Irské království', es: 'Reino de Irlanda' },
  'united states': { cs: 'Spojené státy', es: 'Estados Unidos' },
  'united states of america': { cs: 'Spojené státy americké', es: 'Estados Unidos de América' },
  'usa': { cs: 'USA', es: 'EE. UU.' },
  'canada': { cs: 'Kanada', es: 'Canadá' },
  'brazil': { cs: 'Brazílie', es: 'Brasil' },
  'mexico': { cs: 'Mexiko', es: 'México' },
  'peru': { cs: 'Peru', es: 'Perú' },
  'bolivia': { cs: 'Bolívie', es: 'Bolivia' },
  'colombia': { cs: 'Kolumbie', es: 'Colombia' },
  'ecuador': { cs: 'Ekvádor', es: 'Ecuador' },
  'paraguay': { cs: 'Paraguay', es: 'Paraguay' },
  'uruguay': { cs: 'Uruguay', es: 'Uruguay' },
  'australia': { cs: 'Austrálie', es: 'Australia' },
  'new south wales': { cs: 'Nový Jižní Wales', es: 'Nueva Gales del Sur' },
  'western australia (uk)': { cs: 'Západní Austrálie (brit.)', es: 'Australia Occidental (británica)' },
  'queensland (uk)': { cs: 'Queensland (brit.)', es: 'Queensland (británico)' },
  'china': { cs: 'Čína', es: 'China' },
  'india': { cs: 'Indie', es: 'India' },
  'japan': { cs: 'Japonsko', es: 'Japón' },
  'empire of japan': { cs: 'Japonské císařství', es: 'Imperio del Japón' },
  'korea': { cs: 'Korea', es: 'Corea' },
  "korea, democratic people's republic of": { cs: 'Severní Korea (KLDR)', es: 'Corea del Norte (RPDC)' },
  'korea, republic of': { cs: 'Jižní Korea', es: 'Corea del Sur' },
  'vietnam': { cs: 'Vietnam', es: 'Vietnam' },
  'burma': { cs: 'Barma', es: 'Birmania' },
  'indonesia': { cs: 'Indonésie', es: 'Indonesia' },
  'philippines': { cs: 'Filipíny', es: 'Filipinas' },
  'cambodia': { cs: 'Kambodža', es: 'Camboya' },
  'laos': { cs: 'Laos', es: 'Laos' },
  'nepal': { cs: 'Nepál', es: 'Nepal' },
  'bhutan': { cs: 'Bhútán', es: 'Bután' },
  'ceylon': { cs: 'Cejlon', es: 'Ceilán' },
  'mongolia': { cs: 'Mongolsko', es: 'Mongolia' },
  'kazakhstan': { cs: 'Kazachstán', es: 'Kazajistán' },
  'afghanistan': { cs: 'Afghánistán', es: 'Afganistán' },
  'pakistan': { cs: 'Pákistán', es: 'Pakistán' },
  'iran': { cs: 'Írán', es: 'Irán' },
  'iraq': { cs: 'Irák', es: 'Irak' },
  'syria': { cs: 'Sýrie', es: 'Siria' },
  'lebanon': { cs: 'Libanon', es: 'Líbano' },
  'israel': { cs: 'Izrael', es: 'Israel' },
  'jordan': { cs: 'Jordánsko', es: 'Jordania' },
  'turkey': { cs: 'Turecko', es: 'Turquía' },
  'saudi arabia': { cs: 'Saúdská Arábie', es: 'Arabia Saudita' },
  'yemen': { cs: 'Jemen', es: 'Yemen' },
  'oman': { cs: 'Omán', es: 'Omán' },
  'qatar': { cs: 'Katar', es: 'Catar' },
  'egypt': { cs: 'Egypt', es: 'Egipto' },
  'algeria': { cs: 'Alžírsko', es: 'Argelia' },
  'tunisia': { cs: 'Tunisko', es: 'Túnez' },
  'morocco': { cs: 'Maroko', es: 'Marruecos' },
  'libya': { cs: 'Libye', es: 'Libia' },
  'sudan': { cs: 'Súdán', es: 'Sudán' },
  'ethiopia': { cs: 'Etiopie', es: 'Etiopía' },
  'mali': { cs: 'Mali', es: 'Malí' },
  'niger': { cs: 'Niger', es: 'Níger' },
  'chad': { cs: 'Čad', es: 'Chad' },
  'nigeria': { cs: 'Nigérie', es: 'Nigeria' },
  'ghana': { cs: 'Ghana', es: 'Ghana' },
  'benin': { cs: 'Benin', es: 'Benín' },
  'senegal': { cs: 'Senegal', es: 'Senegal' },
  'mauritania': { cs: 'Mauritánie', es: 'Mauritania' },
  'sierra leone': { cs: 'Sierra Leone', es: 'Sierra Leona' },
  'liberia': { cs: 'Libérie', es: 'Liberia' },
  'congo': { cs: 'Kongo', es: 'Congo' },
  'zaire': { cs: 'Zair', es: 'Zaire' },
  'zaire (belgium)': { cs: 'Belgické Kongo', es: 'Congo Belga' },
  'belgian congo': { cs: 'Belgické Kongo', es: 'Congo Belga' },
  'angola': { cs: 'Angola', es: 'Angola' },
  'mozambique': { cs: 'Mosambik', es: 'Mozambique' },
  'burundi': { cs: 'Burundi', es: 'Burundi' },
  'tanzania, united republic of': { cs: 'Tanzanie', es: 'Tanzania' },
  'south africa': { cs: 'Jižní Afrika', es: 'Sudáfrica' },
  'union of south africa': { cs: 'Jihoafrická unie', es: 'Unión Sudafricana' },
  'swaziland': { cs: 'Svazijsko', es: 'Suazilandia' },
  'madagascar': { cs: 'Madagaskar', es: 'Madagascar' },
  'french west africa': { cs: 'Francouzská západní Afrika', es: 'África Occidental Francesa' },
  'french equatorial africa': { cs: 'Francouzská rovníková Afrika', es: 'África Ecuatorial Francesa' },
  'french guiana': { cs: 'Francouzská Guyana', es: 'Guayana Francesa' },
  'greenland': { cs: 'Grónsko', es: 'Groenlandia' },
  'iceland': { cs: 'Island', es: 'Islandia' },
  'norway': { cs: 'Norsko', es: 'Noruega' },
  'sweden': { cs: 'Švédsko', es: 'Suecia' },
  'finland': { cs: 'Finsko', es: 'Finlandia' },
  'denmark': { cs: 'Dánsko', es: 'Dinamarca' },
  'denmark-norway': { cs: 'Dánsko-Norsko', es: 'Dinamarca-Noruega' },
  'sweden–norway': { cs: 'Švédsko-Norsko', es: 'Suecia-Noruega' },
  'netherlands': { cs: 'Nizozemsko', es: 'Países Bajos' },
  'belgium': { cs: 'Belgie', es: 'Bélgica' },
  'luxembourg': { cs: 'Lucembursko', es: 'Luxemburgo' },
  'germany': { cs: 'Německo', es: 'Alemania' },
  'italy': { cs: 'Itálie', es: 'Italia' },
  'switzerland': { cs: 'Švýcarsko', es: 'Suiza' },
  'swiss confederation': { cs: 'Švýcarské spřísežnectví', es: 'Confederación Suiza' },
  'austria': { cs: 'Rakousko', es: 'Austria' },
  'hungary': { cs: 'Uhersko / Maďarsko', es: 'Hungría' },
  'imperial hungary': { cs: 'Uherské království', es: 'Reino de Hungría' },
  'poland': { cs: 'Polsko', es: 'Polonia' },
  'poland-lithuania': { cs: 'Polsko-litevská unie', es: 'Polonia-Lituania' },
  'polish–lithuanian commonwealth': { cs: 'Republika obou národů (Polsko-Litva)', es: 'Mancomunidad polaco-lituana' },
  'lithuania': { cs: 'Litva', es: 'Lituania' },
  'ukraine': { cs: 'Ukrajina', es: 'Ucrania' },
  'byelarus': { cs: 'Bělorusko', es: 'Bielorrusia' },
  'czechoslovakia': { cs: 'Československo', es: 'Checoslovaquia' },
  'czech republic': { cs: 'Česko', es: 'Chequia' },
  'slovakia': { cs: 'Slovensko', es: 'Eslovaquia' },
  'romania': { cs: 'Rumunsko', es: 'Rumanía' },
  'bulgaria': { cs: 'Bulharsko', es: 'Bulgaria' },
  'greece': { cs: 'Řecko', es: 'Grecia' },
  'serbia': { cs: 'Srbsko', es: 'Serbia' },
  'croatia': { cs: 'Chorvatsko', es: 'Croacia' },
  'macedonia': { cs: 'Makedonie', es: 'Macedonia' },
  'yugoslavia': { cs: 'Jugoslávie', es: 'Yugoslavia' },
  'cyprus': { cs: 'Kypr', es: 'Chipre' },
  'georgia': { cs: 'Gruzie', es: 'Georgia' },
  'armenia': { cs: 'Arménie', es: 'Armenia' },
  'haiti': { cs: 'Haiti', es: 'Haití' },
  'dominican republic': { cs: 'Dominikánská republika', es: 'República Dominicana' },
  'nicaragua': { cs: 'Nikaragua', es: 'Nicaragua' },
  'costa rica': { cs: 'Kostarika', es: 'Costa Rica' },
  'guatemala': { cs: 'Guatemala', es: 'Guatemala' },
  'honduras': { cs: 'Honduras', es: 'Honduras' },
  'el salvador': { cs: 'Salvador', es: 'El Salvador' },
  'belize': { cs: 'Belize', es: 'Belice' },
  'fiji': { cs: 'Fidži', es: 'Fiyi' },
  'tonga': { cs: 'Tonga', es: 'Tonga' },
  'samoa': { cs: 'Samoa', es: 'Samoa' },
  'papua new guinea': { cs: 'Papua-Nová Guinea', es: 'Papúa Nueva Guinea' },
  'hong kong': { cs: 'Hongkong', es: 'Hong Kong' },
  'hainan': { cs: 'Chaj-nan', es: 'Hainán' },
  'xinjiang': { cs: 'Sin-ťiang', es: 'Sinkiang' },
  'tibet': { cs: 'Tibet', es: 'Tíbet' },
  'prussia': { cs: 'Prusko', es: 'Prusia' },
  'bavaria': { cs: 'Bavorsko', es: 'Baviera' },
  'saxony': { cs: 'Sasko', es: 'Sajonia' },
  'sardinia': { cs: 'Sardinie', es: 'Cerdeña' },
  'sicily': { cs: 'Sicílie', es: 'Sicilia' },
  'naples': { cs: 'Neapolsko', es: 'Nápoles' },
  'milan': { cs: 'Milánsko', es: 'Milán' },
  'genoa': { cs: 'Janov', es: 'Génova' },
  'venice': { cs: 'Benátky', es: 'Venecia' },
  'papal states': { cs: 'Papežský stát', es: 'Estados Pontificios' },
  'navarre': { cs: 'Navarra', es: 'Navarra' },
  'castile': { cs: 'Kastilie', es: 'Castilla' },
  'granada': { cs: 'Granada', es: 'Granada' },
  'britany': { cs: 'Bretaň', es: 'Bretaña' },

  /* --- empires, khanates, medieval & ancient polities --- */
  'holy roman empire': { cs: 'Svatá říše římská', es: 'Sacro Imperio Romano Germánico' },
  'austrian empire': { cs: 'Rakouské císařství', es: 'Imperio austríaco' },
  'spanish habsburg': { cs: 'Španělští Habsburkové', es: 'Habsburgo español' },
  'ottoman empire': { cs: 'Osmanská říše', es: 'Imperio otomano' },
  'byzantine empire': { cs: 'Byzantská říše', es: 'Imperio bizantino' },
  'eastern roman empire': { cs: 'Východořímská říše', es: 'Imperio romano de Oriente' },
  'western roman empire': { cs: 'Západořímská říše', es: 'Imperio romano de Occidente' },
  'roman empire': { cs: 'Římská říše', es: 'Imperio romano' },
  'roman republic': { cs: 'Římská republika', es: 'República romana' },
  'frankish kingdom': { cs: 'Franská říše', es: 'Reino franco' },
  'franks': { cs: 'Frankové', es: 'Francos' },
  'carolingian empire': { cs: 'Karolinská říše', es: 'Imperio carolingio' },
  'teutonic knights': { cs: 'Řád německých rytířů', es: 'Orden Teutónica' },
  'kievan rus': { cs: 'Kyjevská Rus', es: 'Rus de Kiev' },
  'kyivan rus': { cs: 'Kyjevská Rus', es: 'Rus de Kiev' },
  'novgorod': { cs: 'Novgorod', es: 'Nóvgorod' },
  'grand duchy of moscow': { cs: 'Moskevské velkoknížectví', es: 'Gran Ducado de Moscú' },
  'tsardom of muscovy': { cs: 'Moskevské carství', es: 'Zarato moscovita' },
  'ryazan': { cs: 'Rjazaňské knížectví', es: 'Principado de Riazán' },
  'golden horde': { cs: 'Zlatá horda', es: 'Horda de Oro' },
  'khanate of the golden horde': { cs: 'Zlatá horda', es: 'Kanato de la Horda de Oro' },
  'white horde': { cs: 'Bílá horda', es: 'Horda Blanca' },
  'nogai horde': { cs: 'Nogajská horda', es: 'Horda Nogái' },
  'crimean khanate': { cs: 'Krymský chanát', es: 'Kanato de Crimea' },
  'mongol empire': { cs: 'Mongolská říše', es: 'Imperio mongol' },
  'great khanate': { cs: 'Velký chanát', es: 'Gran Kanato' },
  'chagatai khanate': { cs: 'Čagatajský chanát', es: 'Kanato de Chagatai' },
  'ilkhanate': { cs: 'Ílchanát', es: 'Ilkanato' },
  'timurid empire': { cs: 'Timurovská říše', es: 'Imperio timúrida' },
  'timurid emirates': { cs: 'Timurovské emiráty', es: 'Emiratos timúridas' },
  'quazaq khanate': { cs: 'Kazašský chanát', es: 'Kanato kazajo' },
  'khiva khanate': { cs: 'Chivský chanát', es: 'Kanato de Jiva' },
  'central asian khanates': { cs: 'Středoasijské chanáty', es: 'Kanatos de Asia Central' },
  'kara khitai khaganate': { cs: 'Karakitanská říše', es: 'Kanato kara kitai' },
  'kimek-kipchak khaganate': { cs: 'Kimecko-kypčacký kaganát', es: 'Kaganato kimek-kipchak' },
  'cuman-kipchak confederation': { cs: 'Kumánsko-kypčacká konfederace', es: 'Confederación cumano-kipchak' },
  'cuman khanates': { cs: 'Kumánské chanáty', es: 'Kanatos cumanos' },
  'khazars': { cs: 'Chazaři', es: 'Jázaros' },
  'volga bulgars': { cs: 'Povolžští Bulhaři', es: 'Búlgaros del Volga' },
  'bulgar khanate': { cs: 'Bulharský chanát', es: 'Kanato búlgaro' },
  'bulgars': { cs: 'Bulhaři (Protobulhaři)', es: 'Protobúlgaros' },
  'avars': { cs: 'Avaři', es: 'Ávaros' },
  'hunnic empire': { cs: 'Hunská říše', es: 'Imperio huno' },
  'ostrogoths': { cs: 'Ostrogóti', es: 'Ostrogodos' },
  'celts': { cs: 'Keltové', es: 'Celtas' },
  'celtic kingdoms': { cs: 'Keltská království', es: 'Reinos celtas' },
  'celtiberians': { cs: 'Keltiberové', es: 'Celtíberos' },
  'celltic hallsatt culture': { cs: 'Keltská halštatská kultura', es: 'Cultura celta de Hallstatt' },
  'urnfield cultures': { cs: 'Kultury popelnicových polí', es: 'Culturas de los campos de urnas' },
  'n. european bronze age cultures': { cs: 'Severoevropské kultury doby bronzové', es: 'Culturas nórdicas de la Edad del Bronce' },
  'milograd culture': { cs: 'Milogradská kultura', es: 'Cultura de Milogrado' },
  'danes': { cs: 'Dánové', es: 'Daneses' },
  'kalmar union': { cs: 'Kalmarská unie', es: 'Unión de Kalmar' },
  'slavonic tribes': { cs: 'Slovanské kmeny', es: 'Tribus eslavas' },
  'illyrians': { cs: 'Ilyrové', es: 'Ilirios' },
  'thrace': { cs: 'Thrákie', es: 'Tracia' },
  'dacia': { cs: 'Dácie', es: 'Dacia' },
  'macedon': { cs: 'Makedonie (antická)', es: 'Macedonia antigua' },
  'greek city-states': { cs: 'Řecké městské státy', es: 'Ciudades-estado griegas' },
  'minoan': { cs: 'Mínojská civilizace', es: 'Civilización minoica' },
  'empire of alexander': { cs: 'Říše Alexandra Velikého', es: 'Imperio de Alejandro Magno' },
  'seleucid kingdom': { cs: 'Seleukovská říše', es: 'Reino seléucida' },
  'achaemenid empire': { cs: 'Achaimenovská říše', es: 'Imperio aqueménida' },
  'parthian empire': { cs: 'Parthská říše', es: 'Imperio parto' },
  'sasanian empire': { cs: 'Sásánovská říše', es: 'Imperio sasánida' },
  'persia': { cs: 'Persie', es: 'Persia' },
  'safavid empire': { cs: 'Safíovská říše', es: 'Imperio safávida' },
  'elam': { cs: 'Elam', es: 'Elam' },
  'assyria': { cs: 'Asýrie', es: 'Asiria' },
  'hittites': { cs: 'Chetité', es: 'Hititas' },
  'scythians': { cs: 'Skythové', es: 'Escitas' },
  'cimerians': { cs: 'Kimmeriové', es: 'Cimerios' },
  'semites': { cs: 'Semité', es: 'Semitas' },
  'umayyad caliphate': { cs: 'Umajjovský chalífát', es: 'Califato omeya' },
  'abbasid caliphate': { cs: 'Abbásovský chalífát', es: 'Califato abasí' },
  'fatimid caliphate': { cs: 'Fátimovský chalífát', es: 'Califato fatimí' },
  'mamluke sultanate': { cs: 'Mamlúcký sultanát', es: 'Sultanato mameluco' },
  'seljuk empire': { cs: 'Seldžucká říše', es: 'Imperio selyúcida' },
  'almoravid dynasty': { cs: 'Almorávidé', es: 'Dinastía almorávide' },
  'emirate of sicily': { cs: 'Sicilský emirát', es: 'Emirato de Sicilia' },
  'buwayhid emirates': { cs: 'Bújovské emiráty', es: 'Emiratos buyíes' },
  'emirate of the white sheep turks': { cs: 'Ak Kojunlu (Turci bílé ovce)', es: 'Ak Koyunlu (turcos de la Oveja Blanca)' },
  'arabs': { cs: 'Arabové', es: 'Árabes' },
  'arabia': { cs: 'Arábie', es: 'Arabia' },
  'arabia (nejd)': { cs: 'Arábie (Nadžd)', es: 'Arabia (Néyed)' },
  'bedouins': { cs: 'Beduíni', es: 'Beduinos' },
  'arabian pastoral nomads': { cs: 'Arabští pastevečtí nomádi', es: 'Nómadas pastores de Arabia' },
  'berbers': { cs: 'Berbeři', es: 'Bereberes' },
  'berber tribes': { cs: 'Berberské kmeny', es: 'Tribus bereberes' },
  'tuareg nomadic tribes': { cs: 'Tuaregové', es: 'Tuareg' },
  'touareg': { cs: 'Tuaregové', es: 'Tuareg' },
  'tuaregs': { cs: 'Tuaregové', es: 'Tuareg' },
  'saharan pastoral nomads': { cs: 'Saharští pastevečtí nomádi', es: 'Nómadas pastores del Sáhara' },
  'saharan nomadic tribes': { cs: 'Saharské kočovné kmeny', es: 'Tribus nómadas del Sáhara' },
  'mughal empire': { cs: 'Mughalská říše', es: 'Imperio mogol' },
  'sultanate of delhi': { cs: 'Dillíský sultanát', es: 'Sultanato de Delhi' },
  'maratha confederacy': { cs: 'Maráthská konfederace', es: 'Confederación maratha' },
  'british raj': { cs: 'Britská Indie', es: 'Raj británico' },
  'mauryan empire': { cs: 'Maurjovská říše', es: 'Imperio Maurya' },
  'gupta empire': { cs: 'Guptovská říše', es: 'Imperio Gupta' },
  'kushan empire': { cs: 'Kušánská říše', es: 'Imperio kushán' },
  'magadha': { cs: 'Magadha', es: 'Magadha' },
  'vedic aryans': { cs: 'Védští Árjové', es: 'Arios védicos' },
  'dravidians': { cs: 'Drávidové', es: 'Drávidas' },
  'hindu kingdoms': { cs: 'Hinduistická království', es: 'Reinos hindúes' },
  'islamic and hindu states': { cs: 'Islámské a hinduistické státy', es: 'Estados islámicos e hindúes' },
  'saka kingdom': { cs: 'Sacké království', es: 'Reino saka' },
  'simhala': { cs: 'Sinhálské království', es: 'Reino cingalés' },
  'palas': { cs: 'Pálovská říše', es: 'Imperio Pala' },
  'manchu empire': { cs: 'Mandžuská říše (Čching)', es: 'Imperio manchú (Qing)' },
  'qing empire': { cs: 'Říše Čching', es: 'Imperio Qing' },
  'ming chinese empire': { cs: 'Říše Ming', es: 'Imperio Ming' },
  'ming empire': { cs: 'Říše Ming', es: 'Imperio Ming' },
  'song empire': { cs: 'Říše Sung', es: 'Imperio Song' },
  'tang empire': { cs: 'Říše Tchang', es: 'Imperio Tang' },
  'sui empire': { cs: 'Říše Suej', es: 'Imperio Sui' },
  'han': { cs: 'Říše Chan', es: 'Imperio Han' },
  'han empire': { cs: 'Říše Chan', es: 'Imperio Han' },
  'jin': { cs: 'Říše Ťin', es: 'Imperio Jin' },
  'jin empire': { cs: 'Říše Ťin', es: 'Imperio Jin' },
  'zhou states': { cs: 'Státy dynastie Čou', es: 'Estados Zhou' },
  'zhow states': { cs: 'Státy dynastie Čou', es: 'Estados Zhou' },
  'chinese warlords': { cs: 'Čínští vojenští vládci', es: 'Señores de la guerra chinos' },
  'xiongnu': { cs: 'Siung-nuové (Xiongnu)', es: 'Xiongnu' },
  'göktürks': { cs: 'Köktürkové', es: 'Köktürks' },
  'western gokturk khaganate': { cs: 'Západoturkický kaganát', es: 'Kaganato köktürk occidental' },
  'ouighurs': { cs: 'Ujguři', es: 'Uigures' },
  'ruanruan': { cs: 'Žuan-žuani', es: 'Ruanruan' },
  'oghuz turks': { cs: 'Oguzové', es: 'Turcos oguzes' },
  'turcik tribes': { cs: 'Turkické kmeny', es: 'Tribus túrquicas' },
  'mongols': { cs: 'Mongolové', es: 'Mongoles' },
  'tibetan empire': { cs: 'Tibetská říše', es: 'Imperio tibetano' },
  'tufan empire': { cs: 'Tibetská říše (Tufan)', es: 'Imperio tibetano (Tufan)' },
  'tibetans': { cs: 'Tibeťané', es: 'Tibetanos' },
  'zhangzhung kingdom': { cs: 'Království Žang-žung', es: 'Reino de Zhangzhung' },
  'silla': { cs: 'Silla', es: 'Silla' },
  'paekche': { cs: 'Pekče', es: 'Baekje' },
  'koguryo': { cs: 'Kogurjo', es: 'Goguryeo' },
  'paleo-koreans': { cs: 'Paleokorejci', es: 'Paleocoreanos' },
  'imperial japan (fujiwara)': { cs: 'Císařské Japonsko (Fudžiwarové)', es: 'Japón imperial (Fujiwara)' },
  'shogun japan (kamakura)': { cs: 'Šógunát Kamakura', es: 'Shogunato Kamakura' },
  'ainu': { cs: 'Ainuové', es: 'Ainu' },
  'đại việt': { cs: 'Dai Viet', es: 'Đại Việt' },
  'champa': { cs: 'Čampa', es: 'Champa' },
  'khmer empire': { cs: 'Khmerská říše', es: 'Imperio jemer' },
  'ayutthaya': { cs: 'Ajutthajské království', es: 'Reino de Ayutthaya' },
  'rattanakosin kingdom': { cs: 'Království Rattanakosin', es: 'Reino de Rattanakosin' },
  'arakan': { cs: 'Arakan', es: 'Arakán' },
  'thai': { cs: 'Thajci', es: 'Tailandeses' },
  'malays': { cs: 'Malajci', es: 'Malayos' },
  'malaysian islamic states': { cs: 'Malajské islámské státy', es: 'Estados islámicos malayos' },
  'minang': { cs: 'Minangkabau', es: 'Minangkabau' },
  'brunei': { cs: 'Brunej', es: 'Brunéi' },
  'dutch east indies': { cs: 'Nizozemská východní Indie', es: 'Indias Orientales Neerlandesas' },
  'netherlands indies': { cs: 'Nizozemská východní Indie', es: 'Indias Orientales Neerlandesas' },
  'tuʻi tonga empire': { cs: 'Říše Tuʻi Tonga', es: 'Imperio Tuʻi Tonga' },
  'polynesians': { cs: 'Polynésané', es: 'Polinesios' },
  'austronesians': { cs: 'Austronésané', es: 'Austronesios' },
  'rapa nui': { cs: 'Rapa Nui (Velikonoční ostrov)', es: 'Rapa Nui (Isla de Pascua)' },

  /* --- Africa & the Americas: kingdoms, colonies, cultures --- */
  'kush': { cs: 'Kúš', es: 'Kush' },
  'meroe': { cs: 'Meroe', es: 'Meroe' },
  'axum': { cs: 'Aksum', es: 'Axum' },
  'alwa': { cs: 'Alwa (Alodie)', es: 'Alwa (Alodia)' },
  'makkura': { cs: 'Makurie', es: 'Makuria' },
  'blemmyes': { cs: 'Blemmyové', es: 'Blemios' },
  'guanches': { cs: 'Guančové', es: 'Guanches' },
  'songhai': { cs: 'Songhajská říše', es: 'Imperio songhai' },
  'bornu-kanem': { cs: 'Kanem-Bornu', es: 'Kanem-Bornu' },
  'mossi states': { cs: 'Mossijské státy', es: 'Estados mossi' },
  'oyo': { cs: 'Ojská říše', es: 'Imperio de Oyo' },
  'lunda': { cs: 'Lundská říše', es: 'Imperio lunda' },
  'expansionist kingdom of merina': { cs: 'Merinské království', es: 'Reino merina' },
  'bantu': { cs: 'Bantuové', es: 'Bantúes' },
  'bantou': { cs: 'Bantuové', es: 'Bantúes' },
  'khoisan': { cs: 'Khoisanové', es: 'Pueblos joisanos' },
  'khoiasan': { cs: 'Khoisanové', es: 'Pueblos joisanos' },
  'west african cereal farmers': { cs: 'Západoafričtí pěstitelé obilnin', es: 'Agricultores de cereales de África Occidental' },
  'mandes': { cs: 'Mandeové', es: 'Pueblos mandé' },
  'islamic city-states': { cs: 'Islámské městské státy', es: 'Ciudades-estado islámicas' },
  'inca empire': { cs: 'Říše Inků', es: 'Imperio inca' },
  'maya chiefdoms and states': { cs: 'Mayská náčelnictví a státy', es: 'Cacicazgos y estados mayas' },
  'maya city-states': { cs: 'Mayské městské státy', es: 'Ciudades-estado mayas' },
  'anasazi': { cs: 'Anasaziové', es: 'Anasazi' },
  'hopewell culture': { cs: 'Hopewellská kultura', es: 'Cultura Hopewell' },
  'glades culture': { cs: 'Kultura Glades', es: 'Cultura Glades' },
  'swift creek culture': { cs: 'Kultura Swift Creek', es: 'Cultura Swift Creek' },
  'thule': { cs: 'Thulská kultura', es: 'Cultura Thule' },
  'dorset': { cs: 'Dorsetská kultura', es: 'Cultura Dorset' },
  'inuit': { cs: 'Inuité', es: 'Inuit' },
  'innu': { cs: 'Innuové', es: 'Innu' },
  'cree': { cs: 'Kríové', es: 'Crees' },
  'cheyenne': { cs: 'Čejeni', es: 'Cheyenes' },
  'athabaskan': { cs: 'Athabaskové', es: 'Atabascanos' },
  'athabascan': { cs: 'Athabaskové', es: 'Atabascanos' },
  'tupis': { cs: 'Tupiové', es: 'Tupíes' },
  'shuar': { cs: 'Šuárové', es: 'Shuar' },
  'vice-royalty of new spain': { cs: 'Místokrálovství Nové Španělsko', es: 'Virreinato de Nueva España' },
  'vice-royalty of peru': { cs: 'Místokrálovství Peru', es: 'Virreinato del Perú' },
  'vice royalty of peru': { cs: 'Místokrálovství Peru', es: 'Virreinato del Perú' },
  'vice-royalty of new granada': { cs: 'Místokrálovství Nová Granada', es: 'Virreinato de Nueva Granada' },
  'viceroyalty of the río de la plata': { cs: 'Místokrálovství Río de la Plata', es: 'Virreinato del Río de la Plata' },
  'vice-royalty of brazil': { cs: 'Místokrálovství Brazílie', es: 'Virreinato de Brasil' },
  'viceroyalty of brazil': { cs: 'Místokrálovství Brazílie', es: 'Virreinato de Brasil' },
  'kingdom of brazil': { cs: 'Brazilské království', es: 'Reino de Brasil' },
  'luisiana': { cs: 'Louisiana', es: 'Luisiana' },
  "rupert's land": { cs: 'Rupertova země', es: 'Tierra de Rupert' },

  /* --- broad cultural / subsistence groupings --- */
  'australian aboriginal hunter-gatherers': { cs: 'Australští domorodí lovci a sběrači', es: 'Cazadores-recolectores aborígenes de Australia' },
  'aboriginal tribes': { cs: 'Domorodé kmeny', es: 'Tribus aborígenes' },
  'tasmanian hunter-gatherers': { cs: 'Tasmánští lovci a sběrači', es: 'Cazadores-recolectores de Tasmania' },
  'amazon hunter-gatherers': { cs: 'Amazonští lovci a sběrači', es: 'Cazadores-recolectores del Amazonas' },
  'andean hunter-gatherers': { cs: 'Andští lovci a sběrači', es: 'Cazadores-recolectores andinos' },
  'caribbean hunter-gatherers': { cs: 'Karibští lovci a sběrači', es: 'Cazadores-recolectores del Caribe' },
  'savanna hunter-gatherers': { cs: 'Savanoví lovci a sběrači', es: 'Cazadores-recolectores de la sabana' },
  'desert hunter-gatherers': { cs: 'Pouštní lovci a sběrači', es: 'Cazadores-recolectores del desierto' },
  'subarctic forest hunter-gatherers': { cs: 'Subarktičtí lesní lovci a sběrači', es: 'Cazadores-recolectores del bosque subártico' },
  'paleo-siberian hunter-gatherers': { cs: 'Paleosibiřští lovci a sběrači', es: 'Cazadores-recolectores paleosiberianos' },
  'finno-ugric taiga hunter-gatherers': { cs: 'Ugrofinští lovci a sběrači tajgy', es: 'Cazadores-recolectores ugrofineses de la taiga' },
  'eastern north amercian hunter-gatherers': { cs: 'Lovci a sběrači východu Severní Ameriky', es: 'Cazadores-recolectores del este de Norteamérica' },
  'arctic marine mammal hunters': { cs: 'Arktičtí lovci mořských savců', es: 'Cazadores árticos de mamíferos marinos' },
  'patagonian shellfish and marine mammal hunters': { cs: 'Patagonští lovci měkkýšů a mořských savců', es: 'Cazadores patagónicos de mariscos y mamíferos marinos' },
  'plain bison hunters': { cs: 'Lovci bizonů z plání', es: 'Cazadores de bisontes de las llanuras' },
  'plateau fichers and hunter gatherers': { cs: 'Rybáři a lovci náhorních plošin', es: 'Pescadores y cazadores-recolectores de las mesetas' },
  'north american pacifi foraging, hunting and fishing peoples': { cs: 'Lovci, sběrači a rybáři severoamerického Pacifiku', es: 'Pueblos cazadores, recolectores y pescadores del Pacífico norteamericano' },
  'pampas cultures': { cs: 'Kultury pamp', es: 'Culturas de las Pampas' },
  'shellfish gatherers': { cs: 'Sběrači měkkýšů', es: 'Recolectores de mariscos' },
  'hunters-gatherers': { cs: 'Lovci a sběrači', es: 'Cazadores-recolectores' },
  'steppe mesolithic hunter-foragers': { cs: 'Stepní mezolitičtí lovci a sběrači', es: 'Cazadores-recolectores mesolíticos de la estepa' },
  'manioc farmers': { cs: 'Pěstitelé manioku', es: 'Agricultores de mandioca' },
  'maize farmers': { cs: 'Pěstitelé kukuřice', es: 'Agricultores de maíz' },
  'austro-asiatic rice farmers': { cs: 'Austroasijští pěstitelé rýže', es: 'Cultivadores de arroz austroasiáticos' },
  'papuan neolithic farmers': { cs: 'Papuánští neolitičtí zemědělci', es: 'Agricultores neolíticos papúes' },
  'iranian pastoralists': { cs: 'Íránští pastevci', es: 'Pastores iranios' },
  'siberians': { cs: 'Sibiřské národy', es: 'Pueblos siberianos' },
  'tungus': { cs: 'Tunguzové', es: 'Tunguses' },
  'saami': { cs: 'Sámové', es: 'Samis' },
  'sámi': { cs: 'Sámové', es: 'Samis' },
  'neanderthal': { cs: 'Neandertálci', es: 'Neandertales' },
  'karasuk culture': { cs: 'Karasukská kultura', es: 'Cultura Karasuk' },
  'andronovo': { cs: 'Andronovská kultura', es: 'Cultura de Andrónovo' },
  'antarctica': { cs: 'Antarktida', es: 'Antártida' },
};

/**
 * Returns the display translation for a dataset name in the given language, or
 * null when there is none — English uses the original, and an unknown name is
 * shown as-is rather than machine-guessed.
 */
export function glossName(name: string, locale: LocaleCode): string | null {
  if (locale === 'en') return null;
  const entry = GLOSSES[name.trim().toLowerCase()];
  if (!entry) return null;
  return entry[locale] ?? null;
}
